### ISSUE TITLE
[Bug] Notification only coming in when opening the home app.

### ISSUE THREAD

**Issue by arkadicolson** [ztalbot2000/homebridge-cmd4#100]
Notification only coming in when opening the home app.

**Describe The Bug:**
Notifications are only showing on my iphone when opening the home app. So Push does not seem to be working.

**To Reproduce:**
Using the MotionDetection plugin

**Expected Behaviour:**
Push notification also when the home app is not active.

**Paste of Logs:**

**Cmd4 Config:**
                {
                    "type": "MotionSensor",
                    "displayName": "Zonnepanelen",
                    "motionDetected":           "FALSE",
                    "StatusActive":             "TRUE",
                    "StatusFault":              "NO_FAULT",
                    "StatusTampered":           "NOT_TAMPERED",
                    "StatusLowBattery":         "BATTERY_LEVEL_NORMAL",
                    "Name":                     "Zonnepanelen",
                    "Manufacturer":             "Fluvius",
                    "Model":                    "Digitale meter",
                    "SerialNumber":             "12345",
                    "StateChangeResponseTime":   3,
                    "state_cmd":                "/opt/zonnepanelen.sh",
                    "polling": true,
                    "interval": 10,
                    "timeout": 1750
                }

**Environment:**
Node.js Version: v12.21.0
Npm Version: v6.14.11
Homebridge Version: v1.3.1
Homebridge-cmd4 Version: 2.4.2
Operating System: Raspbian
Process Supervisor: hb-service

**Comment by ztalbot2000** [comment]
Hi,
  I''m going to leave this open until I do a bit more research to see if things have changed. From what I knew, homebridge cannot initiate the response to HomeKit (your phone).  Cmd4 just calls the Homebridge API of setValue after the poll is complete. So Homebridge is aware of the state change even though your phone is closed.  I'd normally close the ticket with this response.
If you are aware of other plugins that give you your expected outcome, please let me know. I'd like to see what they are doing to confirm my suspicions.
So I'm wondering if the Homebridge API updateValue will generate that message to HomeKit (Your phone).  I have only known that updateValue is for processes which take too long.
please bare with me, I'm kinda swamped.
take care,
John Talbot

**Comment by ztalbot2000** [comment]
I thought I'd give you an update.

So I changed polling to call Homebridge's updateValue as I previously mentioned instead of setValue. From the debug messages, all looks well. I then tried this for a garageDoorOpenner and not only did I NOT get a notification, but the Home App did not even update when I opened it. I'm not giving up though.
There is an interesting Homebridge issue listed [here](https://github.com/homebridge/HAP-NodeJS/issues/543).
Reading through it, there may be a caveat in that the characteristic has to support it.  You would think that the state of a garage door qualifies, but I'm not sure.
So I'm still leaving this open for some further investigation, but the solution may not be as easy as I expect or possible in your case anyway.

**Comment by arkadicolson** [comment]
Hi

Thanks for looking into this. I'm using the homebridge-homewizard v0.1.0 
plugin which notifies me correctly on door sensors. You can use this 
plugin to check the code.

Thanks!
Arkadi

**Comment by ztalbot2000** [comment]
You don't know how much I appreciate that!  I will definetly have a look,
because /I'm not having much luck.

Thank-you,
John

**Comment by ztalbot2000** [comment]
Hi,

  Good news bad news.  The code for homeWizard uses the same getValue
setValue routines.  I tried a GarageDoorOpener with no notifications.  The
homeWizard does not use platform plugins.  So I tried the same garage door
opener configured as a Standalone plugin and notification works fine.

So I'm working on it.

ttfn,
John

**Comment by arkadicolson** [comment]
Ok great. Thanks!

Arkadi

**Comment by arkadicolson** [comment]
Hi

I'm still running version 2.4.2 Last time I tried to update to the 
latest 3 version I did not succeed and I had no time yet to try again. 
Should I first update to the last version?

Please find below one example of cmd4 plugin which has the problem.

       {
             "platform": "Cmd4",
             "name": "Cmd4",
             "outputConstants": false,
             "accessories": [
                 {
                     "type": "ContactSensor",
                     "displayName": "Zonnepanelen",
                     "contactSensorState": "CONTACT_DETECTED",
                     "StatusActive":             "TRUE",
                     "StatusFault":              "NO_FAULT",
                     "StatusTampered":           "NOT_TAMPERED",
                     "StatusLowBattery": "BATTERY_LEVEL_NORMAL",
                     "Name":                     "Zonnepanelen",
                     "Manufacturer":             "Fluvius",
                     "Model":                    "Digitale meter",
                     "SerialNumber":             "12345",
                     "StateChangeResponseTime":   3,
                     "state_cmd": "/opt/zonnepanelen.sh",
                     "polling": true,
                     "interval": 10,
                     "timeout": 1750
                 }
         }


Met vriendelijke groeten
Arkadi Colson

Smartschool • Digitaal Schoolplatform
Smartbit bvba • Hoogstraat 13 • 3670 Meeuwen
www.smartschool.be • info@smartschool.be
T +32 11 64 08 80 • F +32 11 64 08 81

**Comment by ztalbot2000** [comment]
V3 has come a long way, but I will try your config.json with v2 and then
see what happens when I move Cmd4 to v3.  Stay tuned ...

**Comment by arkadicolson** [comment]
Hi

I managed to update my scripts and config tot the latest 3 version of 
cmd4 and the notification are delivered correctly now. So it was 
probably something with the old 2.4 version...

Arkadi

**Comment by ztalbot2000** [comment]
Hi,

I guess this is closed then?

V3 has fetch:< Always | Polled | Cached > which you most likely want
Polled. Setting this means that only those characteristics you want polled
will use your state_cmd. The purpose is to not hammer your device with
needless requests of characteristics that never change. Without this IOS will
still fetch every characteristic directly from your device.

Your config has polled-true, which means that automatically only  required
characteristics get polled. You can also set polling another way,
specifically for each characteristic in v3.

I was going to send you a new config anyway.  you may wish to try it.

{
   "platform": "Cmd4",
   "name": "Cmd4",
   "outputConstants": false,
   "fetch": "Polled",
   "accessories": [
   {
      "type": "ContactSensor",
      "displayName": "Zonnepanelen",
      "contactSensorState": "CONTACT_DETECTED",
      "StatusActive": "TRUE",
      "StatusFault": "NO_FAULT",
      "StatusTampered": "NOT_TAMPERED",
      "StatusLowBattery": "BATTERY_LEVEL_NORMAL",
      "Name": "Zonnepanelen",
      "Manufacturer": "Fluvius",
      "Model": "Digitale meter",
      "SerialNumber": "12345",
      "StateChangeResponseTime": 3,
      "state_cmd": "/opt/zonnepanelen.sh",
      "polling": [ { "characteristic": "contactSensorState", "interval":
10, "timeout": 1750 }]
   }]
}

ttfn,
John

**Comment by arkadicolson** [comment]
Yes, this issue can be closed. Your config is working. Thanks for that!

Arkadi

**Comment by ztalbot2000** [comment]
Closed as problem was resolved.
