### ISSUE TITLE
[Support] Terminate running process on update

### ISSUE THREAD

**Issue by hunhejj** [ztalbot2000/homebridge-cmd4#105]
I am trying to integrate an RF controlled window cover. Basically I send the RF signal, then wait for x seconds in the script and finally I set the state to `closed` assuming that the cover actually closed by then. 

However what happens if I send another command during this interval? Ideally the original process would be stopped gracefully, i.e. that it could still persist its state, e.g for how long it has been run, then the next command is performed.

Is that possible with CMD4?

**Comment by ztalbot2000** [comment]
Hi,

Homebridge does not work that way.  It is a node.js tool so the second
request would be sent during the first requests running time. In other
words you cannot guarantee that the second process would not overlap the
first.
State information is usually less than 5 seconds as defined by Homebridge
or it generates a message that the process took to long.

Ttyl,
John

**Comment by ztalbot2000** [comment]
You could however write your script to keep track of what is happening and then act accordingly.
