### ISSUE TITLE
Set characteristic is using cache

### ISSUE THREAD

**Issue by jameswestcott** [ztalbot2000/homebridge-cmd4#108]
I'm trying to set up the television accessory...
When "Cmd4_Mode" is set to "Polled" the RemoteKey characteristic seems to be setting a cache value and not setting the value on the device. This is with the characteristic not being polled. When "Cmd4_Mode" is set to "Always" the device is set as expected. On your diagram you say all set characteristics are set on the device regardless of the "Cmd4_Mode"

Log entry: [4/19/2021, 19:52:54] [Cmd4] Setting (Cached) AnthemAmp RemoteKey 15

Config:
{
            "platform": "Cmd4",
            "name": "Cmd4",
            "allowTLV8": false,
            "outputConstants": false,
            "restartRecover": true,
            "Cmd4_Mode": "Polled",
            "accessories": [
                {
                    "Type": "Television",
                    "DisplayName": "AnthemAmp",
                    "ConfiguredName": "AnthemAmp",
                    "PublishExternally": true,
                    "Category": "TELEVISION",
                    "Active": "INACTIVE",
                    "ActiveIdentifier": 1,
                    "SleepDiscoveryMode": "ALWAYS_DISCOVERABLE",
                    "RemoteKey": "SELECT",
                    "LinkedTypes": [
                        {
                            "Type": "InputSource",
                            "Identifier": 3,
                            "DisplayName": "WatchAppleTV",
                            "ConfiguredName": "WatchAppleTV",
                            "CurrentVisibilityState": "SHOWN",
                            "InputSourceType": "HDMI",
                            "IsConfigured": "CONFIGURED"
                        },
                        {
                            "Type": "InputSource",
                            "Identifier": 7,
                            "DisplayName": "WatchChromecast",
                            "ConfiguredName": "WatchChromecast",
                            "CurrentVisibilityState": "SHOWN",
                            "InputSourceType": "HDMI",
                            "IsConfigured": "CONFIGURED"
                        },
                        {
                            "Type": "InputSource",
                            "Identifier": 1,
                            "DisplayName": "WatchSky",
                            "ConfiguredName": "WatchSky",
                            "CurrentVisibilityState": "SHOWN",
                            "InputSourceType": "HDMI",
                            "IsConfigured": "CONFIGURED"
                        },
                        {
                            "Type": "InputSource",
                            "Identifier": 5,
                            "DisplayName": "WatchMediaPlayer",
                            "ConfiguredName": "WatchMediaPlayer",
                            "CurrentVisibilityState": "SHOWN",
                            "InputSourceType": "HDMI",
                            "IsConfigured": "CONFIGURED"
                        },
                        {
                            "Type": "InputSource",
                            "Identifier": 6,
                            "DisplayName": "WatchTV",
                            "ConfiguredName": "WatchTV",
                            "CurrentVisibilityState": "SHOWN",
                            "InputSourceType": "HDMI",
                            "IsConfigured": "CONFIGURED"
                        },
                        {
                            "Type": "InputSource",
                            "Identifier": 9,
                            "DisplayName": "ListenRoon",
                            "ConfiguredName": "ListenRoon",
                            "CurrentVisibilityState": "SHOWN",
                            "InputSourceType": "HDMI",
                            "IsConfigured": "CONFIGURED"
                        },
                        {
                            "Type": "InputSource",
                            "Identifier": 4,
                            "DisplayName": "ListenAppleTV",
                            "ConfiguredName": "ListenAppleTV",
                            "CurrentVisibilityState": "SHOWN",
                            "InputSourceType": "HDMI",
                            "IsConfigured": "CONFIGURED"
                        },
                        {
                            "Type": "InputSource",
                            "Identifier": 8,
                            "DisplayName": "ListenChromecast",
                            "ConfiguredName": "ListenChromecast",
                            "CurrentVisibilityState": "SHOWN",
                            "InputSourceType": "HDMI",
                            "IsConfigured": "CONFIGURED"
                        },
                        {
                            "Type": "InputSource",
                            "Identifier": 2,
                            "DisplayName": "ListenSky",
                            "ConfiguredName": "ListenSky",
                            "CurrentVisibilityState": "SHOWN",
                            "InputSourceType": "HDMI",
                            "IsConfigured": "CONFIGURED"
                        }
                    ],
                    "Manufacturer": "cmd4",
                    "Model": "Television",
                    "SerialNumber": "00001",
                    "StateChangeResponseTime": 3,
                    "State_cmd": "node C:\\Users\\james\\.homebridge\\instance5\\cmd4\\television1.js",
                    "polling": [
                        {
                            "Characteristic": "Active",
                            "Interval": 600,
                            "Timeout": 5000
                        },
                        {
                            "Characteristic": "ActiveIdentifier",
                            "Interval": 600,
                            "Timeout": 5000
                        }
                    ]
              }
}

**Comment by jameswestcott** [comment]
As an update, if I poll the RemoteKey characteristic then it works as expected. I am assuming though that I should be able to set any characteristic on the device rather than the cache without polling it?

**Comment by ztalbot2000** [comment]
Hi James,

You can only set a characteristic if it is writeable.  Both Homebridge and
Cmd4 Portals should show the properties of every characteristic.

Ttyl,
John

**Comment by ztalbot2000** [comment]
I just checked.  Remote key is wtiteable
