### ISSUE TITLE
[Support] Using default json, Homebridge has an error of "state_cmd" missing and restarts

### ISSUE THREAD

**Issue by kylewhirl** [ztalbot2000/homebridge-cmd4#110]
**Describe Your Problem:**
I am having an issue setting up a dummy accessory. I want the accessory to do nothing, but the provided config.json causes issues for me. I understand that you need a state_cmd for the plugin to work, but I have no idea what this should be for a default setup. It is not included in the config

[**Link to Logs:**]()

**Paste of Logs:**
```

```

**Cmd4 Config:**

```json


```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **homebridge-cmd4 Version**: 
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by ztalbot2000** [comment]
Hi,

I am not quite sure what you mean by a dummy accessory, however you do not
need any state_cmd if you set the accessories Cmd4_Mode to "Demo". In this
mode, all the characteristics will be used first from the config.json and
then whatever they are in memory, which is known as "Cached".

I hope this helps.
John Talbot

**Comment by kylewhirl** [comment]
This worked thank you so much

**Comment by kylewhirl** [comment]
Actually it half worked. The accessory doesn’t turn off, only on. It gets stuck when turning off

**Comment by ztalbot2000** [comment]
Hi,

Can you send me your config.json?

Thanks,
John

**Comment by kylewhirl** [comment]
{
            "platform": "Cmd4",
            "name": "Cmd4",
            "allowTLV8": false,
            "outputConstants": false,
            "restartRecover": true,
            "Cmd4_Mode": "Demo",
            "accessories": [
                {
                    "Type": "AirPurifier",
                    "DisplayName": "My_AirPurifier",
                    "Active": "ACTIVE",
                    "CurrentAirPurifierState": "INACTIVE",
                    "TargetAirPurifierState": "MANUAL",
                    "LockPhysicalControls": "CONTROL_LOCK_DISABLED",
                    "Name": "Air Purifier",
                    "SwingMode": "SWING_DISABLED",
                    "RotationSpeed": 0,
                    "Manufacturer": "Hosome",
                    "Model": "1010",
                    "SerialNumber": "A659B",
                    "StateChangeResponseTime": 1
                }
            ]
        }
        
This is the config part for the cmd4 plugin

**Comment by ztalbot2000** [comment]
Hi Kyle,

Thanks for the file.  I'll test it shortly.

Ttyl,
John

**Comment by ztalbot2000** [comment]
Hi Kyle,

  I set up your config.json, which looks okay.  I turned on Debug mode so
that I can see what Cmd4 is doing ( homebridge -D ). I then removed all my
Home accessories and just added yours.
The behavior is not 100% what I expected, but there are so many accessories
and characteristics, I cannot possibly try them all from the Home App.
What I did find was that I could tap on the device, The icon would turn
white and go on, but the icon would have a spinning wheel. The debug logs
did show the device going on.
Knowing a little about how the Home App behaves, I went out of the app and
back in.  The spinning wheel disappeared and the icon was still white
(On).  The same could be said for turning it "off".
When the device was on, I could press on its white icon and change all the
parameters.  The debug logs confirmed this and these states were affected
immediately ( no spinning icon).

I have a feeling I know why the behavior is not quite what we would expect
and will look into it, but this may be more to do with Demo mode and the
"Active" characteristic requiring confirmation from a device that the
state_cmd would have.

If you really want to play with a state_cmd and non Demo mode, there are
examples in the distribution; Specifically State.js or AnyDevice.js.

I'll leave this open for now as I look further into the spinning icon.

Ttyl,
John

**Comment by ztalbot2000** [comment]
Hello again Kyle,

  I did spend more time investigating this accessory type.  I'm right in
that the AirPurifier is one of the odd Accessories that Demo mode may not
behave as expected.  In order for the accessory to change state from Active
to Inactive, another set of characteristics come into play and that being
CurrentAirPurifierState and TargetAirPurifierState. It's further confused
by the latter states not being 1:1.

  I'll try Cmd4 in non demo mode with a state_cmd that can control the
characteristic differences to make sure it does behave as it is supposed to.

Ttyl,
John

**Comment by ztalbot2000** [comment]
Hi Kyle

I modified the State.js in the Cmd4 distribution, calling it Purifier. I
altered the config.json to use the state_cmd of the AirPurifier.  The path
to the AirPurifier script of .homebridge/Cmd4Scripts/AirPurifier is
important as to maintain dummy state information between calls it creates
and writes to .homebridge/Cmd4Scripts/Cmd4States

The device does go on and you can change the rotation speed. when turning
off, the icon spinner happens until the polked characteristic of
CurrentAirPurifierState is queried from the AirPurifier script, which it
updates during the Active/Inactive cycles.

So all this does resolve the issue.  I'll put the AirPurifier script in the
Examples path for others to look at in the future.
I'm more interested though in Cmd4 handling multiple related
characteristics and therefore will keep this open for a while.

**Comment by kylewhirl** [comment]
Okay. Thank you so much for the help! I really appreciate it

**Comment by ztalbot2000** [comment]
Closed as per previous comments

**Comment by shipham2302** [comment]
Can anyone help me to create a dummy Air Purifier? 

Just install the plugin and set up the config inside the plugin. Everything works fine but i can't find a way get ì "Off". It stuck with "Turning off.." and spinning wheel. 

Config is the same as the docs provided only without "state_cmd" and "polling". 
When i tried to use them, it throw error that directory not found. 

Can anyone provide me a complete working config for this accessory?
