### ISSUE TITLE
Non Virtual usage?

### ISSUE THREAD

**Issue by MrDrache333** [ztalbot2000/homebridge-cmd4#12]
I would like to use this plugin for controlling different switches and Devices with the Shell...all Scripts i used previusly with the cmdswitch2 Plugin...this plugin is interesting because i can choose from a huge number of differend characterristics and Device Types...but how i can actually Control a real Device with this plugin? Like with the cmd_on and cmd_off Argument...?

**Comment by ztalbot2000** [comment]
Hi,

  I'm glad you found my homebridge-cmd4 plugin.  You most certainly can control a real device and with all the possible options too.

   Maybe I should create a section in the README about porting from the original home bridge.  I just did not want to trample on the other fellas work, but it is something I will think about as many have found homebridge-cmd4 more useful.

   Everything. Is possible, it all depends on your scripting ability. It all starts with the homebridge config.json file. The one I provide has all the possible options,  so I will give you an example of controlling a real light.

1) Edit your .homebridge/.config.json file
2) Copy and paste all the lines between the braces {} for My_Dimmable_Light.  Don't forget the comma after the bracket to signify that there are more entries afterwards.
3)In the new copied section, change My_Dimmable_Light to Your_Dimmable_Light. Adding spaces really complicates scripting, so I would avoid doing that.
4)Change the state_cmd from "node .homebridge/Cmd4Scripts/State.js" to "node .homebridge/Cmd4Scripts/YourState.js"
There are a couple of points I would like make about the this line.
- The command executied by homebridge-cmd4 would be exactly what you would write here, plus options that will be discussed later.
- This command is executed from your $HOME directory. You can try it yourself for debugging purposes.
- No environmental variables or any shortcuts in your .bashrc file or any .rc file are used. This is a big no no in scripting. When debugging, keep this in mind as it may fool you.
- The command that is executed does not have to be a nodejs script. It could have been an executable or bash script, so long as it accepts and responds to the format of homebridge-cmd4, which is the HAP spec.
- An example instead would be "my_light.sh" or "/usr/local/bin/perl .homebridge/my_scripts/my_light.pl"
5) Create the script  .homebridge/Cmd4Scripts/YourState.js.   As noted in the previous item, this could be a bash script, perl or whatever.
6) UnLike the original cmd tool, homebridge-cmd4 responds to options. If you read the top of the State.js file, it does give some information.
Your new script must accept and respond accordingly.  They are not random and are spelled out in the HAP spec, but I will continue with an example.
The parameters are:
   Get <accessory name> <characteristic>
   Set <accessory name> <characteristic> <value>

The "Get" or "Set" would be $1 in your script.
The characteristic would be $2
The value would be $3 if the first option was "Set"

so unlike the original cmd tool, the script sends these options.

What you want to do in your script is up to you.  You could have your script execute another command that actually does something like turn on or dim a real light. 
6)Lastly, the YourState.js file has to respond with an exit code of 0 for PASS or something else for fail.


Study the existing State.js file as it has all the pieces of the puzzle you need.  I'll leave this issue open until I update the README accordingly.

Take care,
John Talbot

**Comment by ztalbot2000** [comment]
I updated the README with an example of migrating from Homebridge-cmdswitch2 which gives a real example
