### ISSUE TITLE
[Feature Request] Grouped Accessoires iOS13

### ISSUE THREAD

**Issue by crbyxwpzfl** [ztalbot2000/homebridge-cmd4#121]
I like [this feature](https://github.com/arachnetech/homebridge-mqttthing/issues/201) of an other homebridge plugin. 
With IOS 13 it's now possible to have different tiles (accessorise) grouped into one tile. While long pressing on it it will reveal them.
For example it's possible to have two switches grouped:

![](https://user-images.githubusercontent.com/32489848/73169444-bf194380-4104-11ea-99cc-54ddeea53117.PNG)

I have no idea how much effort it would be to implement this.<br>
Just thought I post it here.

**Comment by ztalbot2000** [comment]
Hmm, I wonder how it's done.  I will have a look.

Ttyl,
John

**Comment by uswong** [comment]
I thought this can be done already with cmd4 using "linkedTypes".  I have done it and the example below is using the type "Switch" as parent but displayed as "Fan" in HomeApp with a type "Fan" as "linkedTypes".  The config.json file for that is attached for your reference.

![image](https://user-images.githubusercontent.com/96530237/149058524-5ade4757-df66-468c-9c2b-5858ab322eef.png)

                {
                    "type": "Switch",
                    "displayName": "Aircon Fan",
                    "on": "FALSE",
                    "name": "Aircon Fan",
                    "manufacturer": "Advantage Air Australia",
                    "model": "e-zone",
                    "serialNumber": "Daikin e-zone",
                    "queue": "A",
                    "polling": [
                        {
                            "characteristic": "on"
                        }
                    ],
                    "state_cmd": "'/usr/local/lib/node_modules/homebridge-cmd4-advantageair/AdvAir.sh'",
                    "state_cmd_suffix": "${IP}",
                    "linkedTypes": [
                        {
                            "type": "Fan",
                            "displayName": "Fan Speed",
                            "on": "TRUE",
                            "rotationSpeed": 100,
                            "name": "Fan Speed",
                            "manufacturer": "Advantage Air Australia",
                            "model": "e-zone",
                            "serialNumber": "Daikin e-zone",
                            "queue": "A",
                            "polling": [
                                {
                                    "characteristic": "on"
                                },
                                {
                                    "characteristic": "rotationSpeed"
                                }
                            ],
                            "state_cmd": "'/usr/local/lib/node_modules/homebridge-cmd4-advantageair/AdvAir.sh'",
                            "state_cmd_suffix": "${IP} fanSpeed"
                        }
                    ]
                },

**Comment by crbyxwpzfl** [comment]
wow how did you figure this out. Amazing! thank you @uswong! <br>
thank you @ztalbot2000, too!! You are always so quick with your response really appreciate it!
