### ISSUE TITLE
[Feature Request] A Countdown Timer Accessory

### ISSUE THREAD

**Issue by uswong** [ztalbot2000/homebridge-cmd4#122]
Hi John, it would be wonderful and very useful if you could create a Countdown Timer as part of your cmd4 accessories.   I have been trying to have a countdown timer to set the timer on my aircon system and have been using Lightbulb/brightness, Fan/rotationSpeed as a proxy timer, but instead of asking Siri to set the timer for 30 minutes for example, I have to say "hey siri, please set the timer for 30%.  The tile display on home app is also not very intuitive.

Apple has a native timer which looks like this: 
![image](https://user-images.githubusercontent.com/96530237/149431027-f534473d-2e13-403f-9bba-9eafb1459076.png)

Don't have to be like this, but if you can create similar accessory like lightbulb/brightness or fan/rotationSpeed but with time units instead of % will be a big improvement already.

Hopefully this is not something too difficult for you to make.

Cheers,
Ung Sing

**Comment by mitch7391** [comment]
Hey Ung Sing, I have for quite a while wondered how I will approach the 'timer' in our air con systems and also been wondering when someone would finally request it haha... Now remember cmd4 can only produce accessories that HomeKit has already and typically (like our Lightbulb for zone percentage), you have to find something that will be close enough in how it displays. It is, I believe also constrained by data types defined by HomeKit.

I know thanks to my B-Hyve irrigation system that you have 'zones' which look lie switches and you can input a run time; might be a bit of a stretch and not sure if you can have them separate of the controller, but could be an idea off the top of my head... Here is the service type [irrigation system](https://developers.homebridge.io/#/service/IrrigationSystem) and the characteristic [`RemainingDuration`](https://developers.homebridge.io/#/characteristic/RemainingDuration). The characteristic tells us it is also used by the [Valve](https://developers.homebridge.io/#/service/Valve) service type; which could be used instead.

**Comment by uswong** [comment]
Haha.... Mitch, I am looking into how I can get the timer done on our AA E-zone system.  Tested using lightbulb/brightness and also tried valve/setDuration/remainingDuration.  Lightbulb/brightness is more straight forward but need to say % rather than minutes to Siri which is a bit strange and confusing.  I will try again using valve or irrigation to mimic our E-zone timer.  When I am relatively happy with it, I will share that with you.  I was just thinking this morning that if John can create a count down timer accessory and our wish of getting the timer into homekit will be sorted. :)

**Comment by mitch7391** [comment]
@ztalbot2000 and @uswong anything extra to add to this or do you think it is good to close out?

**Comment by uswong** [comment]
Yes, I think we can close this one.
