### ISSUE TITLE
Set ventilation off does not work

### ISSUE THREAD

**Issue by arkadicolson** [ztalbot2000/homebridge-cmd4#123]
Hi

I have a ventilation unit which I control with cmd4. The set from 0% to 100% does work well!. However when I shutdown (or 0%) the ventilation button in Homekit the script is not triggered. I can see "[1/19/2022, 8:55:44 AM] [Cmd4] Setting (Cached) Ventilatie On false" in the Homebridge logs. Is this something related to a cache setting?

v1.3.9
Timezone	GMT+0100
OS	Raspbian GNU/Linux Buster (10)
Node.js Version	v14.18.3
Npm Version	v6.14.15

` {
            "platform": "Cmd4",
            "name": "Cmd4",
            "outputConstants": false,
            "accessories": [
                {
                    "type": "Fan",
                    "displayName": "Ventilatie",
                    "on": "TRUE",
                    "rotationDirection": "CLOCKWISE",
                    "rotationSpeed": 100,
                    "name": "Ventilatie",
                    "manufacturer": "VENTRO",
                    "model": "VENTRO-275",
                    "polling": [
                        {
                            "characteristic": "rotationSpeed",
                            "interval": 10,
                            "timeout": 9000
                        }
                    ],
                    "serialNumber": "2894745",
                    "outputConstants": true,
                    "stateChangeResponseTime": 3,
                    "state_cmd": "/opt/ventilatie.sh"
                }
}
`

**Comment by arkadicolson** [comment]
Never mind. The on characteristic should be defined...

**Comment by arkadicolson** [comment]
Hmmmm
Now I see
[1/19/2022, 10:24:45 AM] [Cmd4] getValue: On function for: Ventilatie returned an empty string "". Perhaps your device is busy?
in the logs. I indeed do not return anything on this because the only relevant char is rotationSpeed. When setting rotationSpeed to 0 it is off. Is there a way to handle this?

**Comment by arkadicolson** [comment]
Never mind again ;-) Fixed it, bug in my script

**Comment by arkadicolson** [comment]
closed

**Comment by ztalbot2000** [comment]
Hi,


Sorry, I have been indisposed for awhile. Now that I know of this, I will
investigate.

Ttyl,
John

**Comment by ztalbot2000** [comment]
Hi,

  So you had closed this and I never noticed.  I think you figured out that
"On" was not polled, thus always retrieved from cache.

Ttyl,
John

**Comment by arkadicolson** [comment]
Yes indeed, I figured it out myself as you say with polling ;-)


Best regards
Arkadi Colson
