### ISSUE TITLE
EVE doesn't show history graph.

### ISSUE THREAD

**Issue by banboobee** [ztalbot2000/homebridge-cmd4#124]
Hi ztalbot2000, 

Thanks for your plug-in CMD4, I've been using it for more than years to monitor temperatures. Thank you very much.

But found that EVE doesn't display the history graph in these days. After struggling for a while for digging, following
changes against to V6.0.4 were needed to show the graph in EVE. It just replaces two 'this' to 'this.platform'.

If the changes are correct, its my pleasure that they'll be annotated to your code.

Thanks in advance.

# diff -c Cmd4Accessory.js*
*** Cmd4Accessory.js    2022-01-16 15:09:32.489061997 +0900
--- Cmd4Accessory.js~   2022-01-16 14:32:00.000000000 +0900
***************
*** 1206,1212 ****
              this.loggingService = new FakeGatoHistoryService
              (
                 this.eve,
!                this.platform,
                 { [ constants.STORAGE ] : constants.FS,
                   [ constants.PATH ]   : this.storagePath
                 }
--- 1206,1212 ----
              this.loggingService = new FakeGatoHistoryService
              (
                 this.eve,
!                this,
                 { [ constants.STORAGE ] : constants.FS,
                   [ constants.PATH ]   : this.storagePath
                 }
***************
*** 1218,1224 ****
              this.loggingService = new FakeGatoHistoryService
              (
                 this.eve,
!                this.platform,
                 { [ constants.STORAGE ] : constants.GOOGLE_DRIVE,
                   [ constants.FOLDER ]  : this.folder,
                   [ constants.KEYPATH ] : this.keyPath }
--- 1218,1224 ----
              this.loggingService = new FakeGatoHistoryService
              (
                 this.eve,
!                this,
                 { [ constants.STORAGE ] : constants.GOOGLE_DRIVE,
                   [ constants.FOLDER ]  : this.folder,
                   [ constants.KEYPATH ] : this.keyPath }

**Comment by ztalbot2000** [comment]
Hi,

  I love users who figure things out  for themselves. It makes my life so
much easier.  I will make the changes in the next 24 hours.

Take care,
John

**Comment by banboobee** [comment]
Thank you for your prompt response.

I'm happy to hear that the changes are accepted.

You too, take care always.

**Comment by ztalbot2000** [comment]
Hi,

  Quick question as the diff you give is different from proposed to
existing and does not match your comments, but I still kinda understand
what you want and just want clarification.

I believe you want me to change the two occurrences of
new FakeGatoHistoryService( this.eve, this, ...

to
new FakeGatoHistoryService( this.eve, this.platform, ...

is there a reason you want it changed to !this.platform
The diff also has it as the previous of
new FakeGatoHistoryService( this.eve, !this
where the existing source has it as just this  and not !this

I'm taking your word of it here as the API for FakeGatoHistoryService has
the second parameter as a Accessory and not a Platform, but god knows if
you have it working, I'll accept it

ttyl,
John

**Comment by ztalbot2000** [comment]
Hi,

  So I did not hear back from you.  I made the change that I think you
wanted.  Please let me know if this works for you.

ttyl,
John

**Comment by banboobee** [comment]
Sorry for late response due to TZ difference.

I updated to v.6.1.0. It's working and EVE shows the history graph. 

Thank you very much.

I can't understand what you mean at a glance (e.g. second parameter of FakeGatoHistoryService).
I will review your comment and reply later day.

**Comment by ztalbot2000** [comment]
Hi,

 Changed the second parameter to this.platform
You had it in your diff as !this.platform

I'm glad it works.

Ttyl,
John

**Comment by banboobee** [comment]
Now I understand what you mean.

Yes, '!' shouldn't be annotated. It's clearly wrong in semantically as you thought.

The diff output was in 'context format' (diff -c), and '!' at first column means that 'this line has changes'.
But blanks are removed in pasted diff output, and that makes you confused.

I'm very sorry for your inconveniences.

**Comment by ztalbot2000** [comment]
Hi,

All good. I'm glad it worked.

Ttyl,
John
