### ISSUE TITLE
Misleading example(s)

### ISSUE THREAD

**Issue by flobernd** [ztalbot2000/homebridge-cmd4#13]
Hi there,

I just tested your plugin and got the string values `true`/`false` passed for the `On` characteristic instead of `0`/`1` like described in the README.

You might want to fix this.

Best regards

**Comment by ztalbot2000** [comment]
Hmmm,
   The Hap spec says:
// UUID: 00000025-0000-1000-8000-0026BB765291
// Type: public.hap.characteristic.on
// Permissions: Paired Read, Paired Write, Notify
// Format: bool, 0 (false) and 1 (true)

I do not know why you see the string 'true' and 'false'. Clearly that is not what it was before or none of my switches will work.  I will have to do a deep dive into why.  Thanks for sending your other issue.  The script was useful in debugging this one.  It could also explain why you are seeing the delay.  They easily could be related if homebridge polls for something and expects 1 or 0 and not true or false.
Stay tuned

**Comment by flobernd** [comment]
Some implicit type conversion might going on (I remember javascript beeing very _special_ about this). `0` and `1` should implicitly be converted to `bool`, so testing for the **numeric** values shouldn't be a problem. 
The problem is, that your plugin passes the arguments for the bash scripts as string (which is fine, as I do not see a way to keep type information while passing values from javascript to bash).
But maybe ... just maybe there is different behavior for different `node-js` versions or even platforms in terms of the implicit conversion to string. Sometimes `string = false` might result in `"false"` and sometimes it might result in `0`.

As I said, I did not digg into your code yet, but are you using the implicit conversion for passing the arguments to bash? Implementing a manual conversion would fix this inconsistency in this case (btw. `true`/`false` strings instead of `1`/`0` look more sane to me for `bool` values anyways).

I'm using the latest version of homebridge and your plugin. The log string is printed with `true`/`false` instead of `1`/`0` as well (the error itself is "intended", as I did not implement switching my computer off yet):

```
[10/11/2018, 3:30:37 PM] [CustomDevices] Cmd4 Set On function failed for COMPUTER Error:Command failed: bash ~/.homebridge/Cmd4Scripts/COMPUTER.sh Set 'COMPUTER' 'On' 'false'
```

Let me know, if you need more information/log or if I should test more cases.

**Comment by MrDrache333** [comment]
Copyed some code i use for my PiHole DNS-Server...for the SET Command you have to use _true_  and _false_...

`#!/bin/bash

if [ "$1" = "Get" ]; then
   # $2 would be the name 'PiHole'
   # $3 would be the charactersistic 'On'
   state=$(pihole status | grep -c Enabled)
   if [[ "$state" = "0" ]]; then
     echo "$state"
     exit 0
   elif [[ "$state" = "1" ]]; then
     echo "$state"
     exit 0
   fi
fi

if [ "$1" = "Set" ]; then
   # $2 would be the name 'PiHole'
   # $3 would be the the charactersistic 'On'
   # $4 would be '0' for 'Off', '1' for 'On'

   if [ $4 = true ]; then
      pihole enable
      exit $?
   elif [ $4 = false ]; then
      pihole disable
      exit $?
   fi
fi

exit -1`

**Comment by flobernd** [comment]
Just took a look and you are indeed using implicit type conversion:
https://github.com/ztalbot2000/homebridge-cmd4/blob/master/index.js#L1246

You might want to change this for boolean values, if there really is inconsistency on different `node-js` versions or platforms.

**Comment by ztalbot2000** [comment]
Thanks for finding this.  The fault was not with homebridge-cmd4,  It just output whatever value is.  It was supposed to be 0/1, based on the HAP spec.  Strangely enough I realized this when retrieving the  value stored by State,js, I translate it to 0/1
When I added the bash script just recently, I forgot this.
