### ISSUE TITLE
[Support] Garagedoor state_cmd want pass Set commands

### ISSUE THREAD

**Issue by arkadicolson** [ztalbot2000/homebridge-cmd4#132]
Hi

I'm trying to get garagedoor working with this config

```
                {
                    "type": "GarageDoorOpener",
                    "displayName": "Garagepoort_2",
                    "currentDoorState": "OPEN",
                    "targetDoorState": "OPEN",
                    "obstructionDetected": "FALSE",
                    "lockCurrentState": "UNSECURED",
                    "lockTargetState": "UNSECURED",
                    "name": "Garagepoort_2",
                    "manufacturer": "Somebody",
                    "model": "Anything",
                    "serialNumber": "1232321321345",
                    "stateChangeResponseTime": 10,
                    "state_cmd": "/opt/garagepoort_2.sh",
                    "polling": [
                        {
                            "characteristic": "currentDoorState",
                            "interval": 540,
                            "timeout": 8000
                        },
                        {
                            "characteristic": "obstructionDetected",
                            "interval": 540,
                            "timeout": 8000
                        },
                        {
                            "characteristic": "lockCurrentState",
                            "interval": 540,
                            "timeout": 8000
                        }
                    ]
                },

```
I just started with this simple test script:
```
#!/bin/sh
echo ">> $1 $2 $3 $4" >> /tmp/homebridge_scripts.log
if [ "$1" = "Get" ]; then
        if [ "$3" = "ObstructionDetected" ]; then
                echo FALSE
        elif [ "$3" = "CurrentDoorState" ]; then
                echo CLOSED
        elif [ "$3" = "LockCurrentState" ]; then
                echo SECURED
        fi
else
        echo "SET"
fi

```
Get commands are displayed in /tmp/homebridge_scripts.log but I do not see any Set commands when pushing the garagedoor in the home app

```
==> /tmp/homebridge_scripts.log <==
>> Get Garagepoort_2 CurrentDoorState 
>> Get Garagepoort_2 ObstructionDetected 
>> Get Garagepoort_2 LockCurrentState 
```

I do see this in the homebridge log:

```
[10/14/2022, 2:55:42 PM] [Cmd4] Setting (Cached) Garagepoort_2 TargetDoorState 0
[10/14/2022, 2:55:42 PM] [Cmd4] Also Setting (Cached) Garagepoort_2 CurrentDoorState 0

```
but I cannot catch it in my state_cmd script. Any idea why? Something cache related?

* **Node.js Version**: v16.17.1
* **NPM Version**: 8.15.0
* **Homebridge Version**:8.15.0
* **homebridge-cmd4 Version**: v6.3.0
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

**Comment by ztalbot2000** [comment]
Hi,

   On your IOS device, you would have to trigger the GarageDoor to be
opened for a "Set" command to occur. I just noticed you did this, so let's
continue.
A GarageDoor does not request to change the "CurrentDoorState".
instead it sends a "TargetDoorState" of OPEN or CLOSED
I think you got this too.
The problem I see is the debug log of
"Setting ( Cached )  Garagepoort_2 TargetDoorState 0"
The key issue being "Cached" which is not executing your script.

I think you need to poll for "lockTargetState" which I believe resolve the
issue.

You should see CMD4 displaying a debug log that it is executing your script.



You should also to remember to always exit the script properly.
exit 0

Ttyl,
John

**Comment by ztalbot2000** [comment]
Hello again.

  Did you have any success?

In the homebridge-cmd4 distribution in the sub path of Extras/Cmd4Scripts
there is a javascript file called State.js.
Every possible "Get/Set" option is listed there and it could be used as a
state_cmd.
What is also important is that it handles persistence of TargetDoorState
and Setting currentDoorState afterwards, so the door does not get stuck
openning.
I might have misspoke with polling for "lockTargetState" it might have been
"targetDoorState".  The state.js file has the proper documentation, as does
the Homebridge-Cmd4 github documentation.
If your still stuc, just ask and I'll create a proper config.json and send
it to you.

Ttyl,
John

**Comment by ztalbot2000** [comment]
Here is a config.json for a working GarageDoorOpener
{
                    "type": "GarageDoorOpener",
                    "name": "My_GarageDoorOpener",
                    "displayName": "My_GarageDoorOpener",
                    "manufacturer": "GarageDoorMan",
                    "currentDoorState": "OPEN",
                    "targetDoorState": "OPEN",
                    "obstructionDetected": "FALSE",
                    "lockCurrentState": "UNSECURED",
                    "lockTargetState": "UNSECURED",
                    "polling": [
                        {
                            "characteristic": "currentDoorState"
                        },
                        {
                            "characteristic": "targetDoorState"
                        },
                        {
                            "characteristic": "obstructionDetected"
                        },
                        {
                            "characteristic": "lockCurrentState"
                        }
                    ],
                    "stateChangeResponseTime": 10,
                    "state_cmd_prefix": "node",
                    "state_cmd": ".homebridge/Cmd4Scripts/State.js"
                },

The State.js file as I previously mentioned is distributed with Cmd4.
If you still have problems, just reopen the issue.

Take care,
John

**Comment by arkadicolson** [comment]
Hi

Sorry for the late answer but it works again. Polling lockTargetState 
did the trick. Thanks for your help!

Arkadi
