### ISSUE TITLE
[Support] How to run on_cmd and off_cmd

### ISSUE THREAD

**Issue by edgarfroes** [ztalbot2000/homebridge-cmd4#133]
**Describe Your Problem:**
As per the old [homebridge-cmdswitch2](https://github.com/luisiam/homebridge-cmdswitch2) lib, I want to execute scripts when toggling a switch or a fan. I can't find documented properties that are similar to `on_cmd` and `off_cmd` anywhere. I've also tried trial and error and I failed.

Did I miss something?

**Comment by ztalbot2000** [comment]
Hi,

  Have a look at:
Cmd4 Portal:
https://ztalbot2000.github.io/homebridge-cmd4/#
Cmd4 Developers guide:
https://github.com/ztalbot2000/homebridge-cmd4/blob/master/docs/Developers.md

There is no need to move from cmdswitch2 for just on/off of a switch; It
still does the trick nicely. Cmd4 was originally built off of it, but I
wanted more.

What you are specifically looking for is the state_cmd. With hundreds of
properties besides on/off the state_cmd you provide gets passed 'Get' or
'Set' '<device name>' '<characteristic>' '<value?>'

I.e. for a switch called "My_Switch" and a state_cmd of "/home/pi/state.sh"
for Set on what would be executed would be:

/home/pi/state.sh 'Set' 'My_Switch' 'On' 1'

You also need to poll for 'on' as it is a read/write characteristic.

For Get what would be sent is:
/home/pi/state.sh 'Get' 'My_Switch' 'On'

If you understand this, there are tons of examples and scripts available,
including for a switch. The Cmd4 distribution ships with them in the Extras
subdirectory of Cmd4 or on GitHub


Take care,
John

**Comment by edgarfroes** [comment]
Hey @ztalbot2000, thanks for the fast reply. I think that I'm doing something wrong. Here's my code:

```
    "accessories": [
        {
            "accessory": "Cmd4",
            "name": "My_Switch",
            "type": "Switch",
            "outputConstants": false,
            "displayName": "My_Switch",
            "on": "sh /Users/edgar/.homebridge/test/ac_state.sh",
            "manufacturer": "Custom Manufacturer",
            "model": "Custom Model",
            "stateChangeResponseTime": 3,
            "state_cmd": "sh /Users/edgar/.homebridge/test/ac_on.sh"
        }
    ],
```

The `ac_on.sh` script will set the return of `ac_state.sh` to `TRUE`. There also an `ac_off.sh` that sets `ac_state.sh` to `FALSE`, of which I don't know where to call.

Does the `state_cmd` property sends parameters to the `ac_on.sh` script? I'm not being able to understand the docs.

**Comment by ztalbot2000** [comment]
Hi,

  You need to poll for "on" as it's a read/write variable. Otherwise the
value will be just Get/Set from cache

 "polling": [ { "characteristic": "on", "interval": 5000 }
                        ],

Ttyl,
John

**Comment by ztalbot2000** [comment]
Hi again,

  If you set debug: true you will see the state_cmd you configured being
executed (permitting you add the polling in the last response).  If you see
the state_cmd in the debug logs, you will understand what and how the
parameters are used.

Ttyl,
John

**Comment by ztalbot2000** [comment]
If you are still having issues, just reply to this now closed ticket
