### ISSUE TITLE
Create a dummy Air Purifier. Stuck at "turning off.." and a spinning wheel

### ISSUE THREAD

**Issue by shipham2302** [ztalbot2000/homebridge-cmd4#140]
Can anyone help me to create a dummy Air Purifier?

Just install the plugin and set up the config inside the plugin. Everything works fine but i can't find a way get it "Off" completely. It stuck with "Turning off.." and spinning wheel.

Config is the same as the docs provided only without "state_cmd" and "polling".
When i tried to use them, it throw error that directory not found.

Can anyone provide me a complete working config for this accessory?

**Comment by ztalbot2000** [comment]
Hi Shi,

  Can you please send me the config.json you were using and the platform
you were running Homebridge on.

Thanks,
John

**Comment by ztalbot2000** [comment]
Here is a config.json I just tested

{
         "platform": "Cmd4",
         "name": "Cmd4",
         "allowTLV8": false,
         "outputConstants": false,
         "restartRecover": true,
         "debug": true,
         "cmd4_Mode": "Demo",
         "accessories": [
         {
            "type": "AirPurifier",
            "displayName": "My_AirPurifier",
            "active": "ACTIVE",
            "currentAirPurifierState": "INACTIVE",
            "targetAirPurifierState": "MANUAL",
            "lockPhysicalControls": "CONTROL_LOCK_DISABLED",
            "name": "Air Purifier",
            "swingMode": "SWING_DISABLED",
            "rotationSpeed": 0,
            "manufacturer": "Hosome",
            "model": "1010",
            "serialNumber": "A659B",
            "stateChangeResponseTime": 1
        } ]
      }

From within HomeKit I can turn the device On and Off.  I will note that the AirPurifier says "Turning on..." when you turn it on and stays this way.  I noticed this for a GarageDoorOpener over a year ago. From what I determined HomeKit/HomeBridge did not like/respond properly to an update status message for accessories that are multi-state and they never fixed it.  This is not however the issue you are talking about. 

As I can turn On/Off the device with the config above.  I'll close the issue.

John Talbot
