### ISSUE TITLE
[Bug]Problem to run a program from the plugin

### ISSUE THREAD

**Issue by mat2824** [ztalbot2000/homebridge-cmd4#145]
Hello, I want to use this plugin to control lightbulb, and I have to start my program from the cmd4 plugin. I don't understand why I can start my program from other plugin and not that one. 
My config:
{
    "platform": "Cmd4",
    "name": "Cmd4",
    "accessories": [
        {
            "type": "Lightbulb",
            "displayName": "Lumière de test",
            "on": "/path/prog.sh"
        }
    ]
}
I try differents things for on and that not work. If I try since homebridge terminal, Its works.
Has anyone encountered the same difficulties can help me please ?

**Comment by ztalbot2000** [comment]
Hi,

  I'm glad you figured it out.

Take care,
John
