### ISSUE TITLE
Savant Integration

### ISSUE THREAD

**Issue by ffichman** [ztalbot2000/homebridge-cmd4#148]
Hello, I'm trying to create a Savant profile to control some devices on the homebridge such as: Xbox Power, PlayStation. Would it be possible to integrate by sending the savant command to a childbridge using CMD4?

**Comment by ztalbot2000** [comment]
Hi,

   If you can create a script that will do what you want, then Cmd4 can
execute it. For example:

  YourScript.sh Set Savant On
Or
  YourScript.sh Set Savant Off

You have to write the script though.

Ttyl,
John

**Comment by ffichman** [comment]
savant is an automation system, its profile would have to send a command to the homebridge. In the case of power on off of xbox or playstation.

**Comment by ztalbot2000** [comment]
Hi,

   I don't think you understand what Cmd4 is all about. Cmd4 has no knowledge on how to talk to any device. It is an interface between HomeKit/Homebridge and the scripts you must write to do what you want. If you have a script that turns on or off a device for example, Cmd4 can run it.
