### ISSUE TITLE
[Support] Stuck with node module not found error

### ISSUE THREAD

**Issue by ipearx** [ztalbot2000/homebridge-cmd4#149]
I'm using a simple script run with the following command:
```
/usr/bin/node /home/pi/victronmodbus/inverter.js
```
Running on the command line works no problems. But when run by cmd4 I get the following log error.
Things I've checked/tried:
 - removing my node folders and doing an npm install again.
- This is imported from a previous install. I used to use node as the command, tried that and also /usr/bin/node to ensure it's using the version of node I think it should be.
- ensured the permissions are open for all users for all the files I'm trying to run.

No doubt I'm doing something stupid. God I hate node...

**Paste of Logs:**
```
getValue On function failed for Inverter cmd: /usr/bin/node /home/pi/victronmodbus/inverter.js Get 'Inverter' 'On' Failed.  Generated Error: Error: Command failed: /usr/bin/node /home/pi/victronmodbus/inverter.js Get 'Inverter' 'On'
node:internal/modules/cjs/loader:1228
  throw err;
  ^

Error: Cannot find module '/home/pi/victronmodbus/inverter.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.18.0
```

**Cmd4 Config:**
```json


        {
            "platform": "Cmd4",
            "name": "Cmd4",
            "outputConstants": false,
            "debug": true,
            "accessories": [
                {
                    "type": "LightSensor",
                    "displayName": "Battery",
                    "statusActive": "TRUE",
                    "currentAmbientLightLevel": "0",
                    "name": "Battery",
                    "polling": true,
                    "state_cmd": "/usr/bin/node /home/pi/victronmodbus/battery.js"
                },
                {
                    "type": "Switch",
                    "displayName": "Inverter",
                    "on": "FALSE",
                    "name": "Inverter",
                    "polling": true,
                    "state_cmd": "/usr/bin/node /home/pi/victronmodbus/inverter.js"
                }
            ]
        }
```

**Environment:**

Node.js Path	/opt/homebridge/bin
Storage Path	/var/lib/homebridge
Config Path	/var/lib/homebridge/config.json
Plugin Path	/var/lib/homebridge/node_modules

* **Node.js Version**:  v20.18.0
* **NPM Version**: 10.8.2
* **Homebridge Version**:  v1.8.4
* **homebridge-cmd4 Version**v8.0.1
* **Operating System**: Raspbian
* **Process Supervisor**:  Manual homebridge install whichever that does.

Thanks in advance!

**Comment by ztalbot2000** [comment]
Hi,

   Yup I've seen this. It's a rookie mistake. The problem is that when
anything is run from a process started by the system, the system does not
have the same environment as your userid does. For instance there is
something in your profile that makes your command work, but not by the
Homebridge user. I usually found Unix users trying to get cron to do
something for them that worked fine when they ran it itself.
  Do I have an answer for you, yes and no. There is no possible way for me
to know every system, shell or program. I can tell you that if you create a
shell without your profile you will recreate the problem you are having and
then can figure out what the issue is.
So run:
env -i bash --norc --noprofile
Then run your command that you want Cmd4 to run and see if that recreates
the problem. Somewhere an env diffference between both will show what's
missing. It could be very well where/how your node_modules is set up on
your system.
Write back if you figure it out or need more help.
John

**Comment by ipearx** [comment]
Thanks for that, weirdly dropping into bash with no profile has no problems and works as expected. That's why I was using the full path names for the files, to make sure paths weren't an issue (I've had that plenty of times with CRON jobs!). Must be a permission issue or something.

At the end of the day I'm just trying to run a script, but it can't find the filename.  Maybe I should try bun, and see if that works! Will report back soon...

```
pi@puretrack-1:~ $ env -i bash --norc --noprofile
bash-5.2$ /usr/bin/node /home/pi/victronmodbus/battery.js
99
bash-5.2$ /usr/bin/node /home/pi/victronmodbus/inverter.js
bash-5.2$ /usr/bin/node /home/pi/victronmodbus/inverter.js Get
1
```

**Comment by ztalbot2000** [comment]
Hi,

  So you have learned already the cron issue. you're not a newbie to the
problem. I don't believe it's a chroot problem either. You could make sure
the /home/pi and /hime/pie/victronmodbus directories have 755 permissions.
Somehow I don't think that's the issue though.
Is /usr/bin/node a symbolic link to the real node application?
I've seen where node tries to figure out its node_modules path based on its
own path, but that does not explain why it works when you run the command
in a clean shell. I also assume you tried just "node
/home/pi/victronmodbus/inverter.js"
report your findings back. This is making me curious.

John

**Comment by ipearx** [comment]
OK I switched to bun, installed that, made it available to the homebridge user.

I then made a test script
```javascript
console.log('1');
```
Same error:

```
[07/10/2024, 21:02:52] [Cmd4] getValue: On function for Inverter streamed to stderr: error: Module not found "/home/pi/victronmodbus/test.js"

[07/10/2024, 21:02:52] [Cmd4] getValue On function failed for Inverter cmd: /home/homebridge/.bun/bin/bun /home/pi/victronmodbus/test.js Get 'Inverter' 'On' Failed.  Generated Error: Error: Command failed: /home/homebridge/.bun/bin/bun /home/pi/victronmodbus/test.js Get 'Inverter' 'On'
error: Module not found "/home/pi/victronmodbus/test.js"
```

I must be doing something very stupid...

**Comment by ztalbot2000** [comment]
Hi,

  Yeah it's something stupid. How about changing the first line of
inverter.js to
#!/usr/bin/node
Chmodding the inverter.js script to 755
Then have the cmd4 just call /home/pi/victronmodbus/inverter.js
This should be no difference either, but maybe an interesting result.
I'm trying to remember if it should be
#!/usr/bin/node $*
But it's 3 AM here ;-)

John

**Comment by ztalbot2000** [comment]
Hi,

  Got a cat by the tail here.
I've never seen

/home/homebridge/.bun/bin/bun

Before. Could you move your script to the /home/homebridge directory?

In the morning if you have not got it going, I'll set up a Pi with your
environment.

John

**Comment by ztalbot2000** [comment]
Hi,

  Can't sleep. Keep thinking about your problem.
Try to su to the user homebridge. You may have to go through root to do it.
sudo su
su - homebridge
/usr/bin/node /home/pi/victronmodbus/inverter.js


John

**Comment by ztalbot2000** [comment]
Hi,

  Inside your inverter.js or test.js file you are importing a module. I bet
this modules path is not relative to the current path. For example the
process is run by homebridge, the executable is in Pi's path where there is
also a node_modules directory. This node_modules directory would never be
found by homebridge. When you run it from your shell, it of course would be.
 So moving it all to the Homebridge users directory should solve the
problem. Also becoming the Homebridge user would also show the problem when
you run the Cmd4 state_cmd.

I think I can sleep now.

John

**Comment by ztalbot2000** [comment]
Hi,
  Got to read everything online, not just from email.
  Your test.js having only console.log("1") means it should not be using ~pi/modbusinverter/node_modules; However node will still be looking for node_modules for internals. I still suggest you su to homebridge with no profile and try running your /usr/bin/node /home/pi/modbusinverter/inverter.js.
The error is not complaining about command not found but modules not found. Surprisingly if you run a nodejs script and the node_modules directory cannot be found, it looks like the error is like it cannot find the script.

**Comment by ipearx** [comment]
Well done I think you cracked the issue. It worked when:
- I moved it all to the homebridge home directory.
- Changed ownership of all the files to homebridge.
- I added a shebang at the start of each script and just call the script.
That now works as expected.

Thank you for your help! Hopefully this thread helps someone else in the future.

**Comment by ztalbot2000** [comment]
Hi,

  I'm glad you got it working. Scripts can be tricky when run from a
process.

Take care,,
John
