### ISSUE TITLE
Garage Door issue

### ISSUE THREAD

**Issue by dmkpoznan** [ztalbot2000/homebridge-cmd4#15]
Hi,

At first I want to say thank You for this module. It's great!

I have problem with GarageDoorOpener.

Two problems:

1) My garage doors (default closed) is saying "Opening..." after fresh Homebridge start. CurrentDoorState returning right value (1, as doors are closed). Something is wrong with TargetDoorState. Any ideas?

2) I have another gate, that is working similar to garage doors, but is auto-closing after some interval of time. I write some bash scripts to operate this gate using Cmd4 and everything is working smooth, but after auto-closing (again, as above - CurrentDoorState returning right value - 1 - as gate is closed) gate switch to "Opening..." state.

Please, help. I'm out of ideas digging in sources and analyzing HomeKit SDK.

Thanks!

**Comment by ztalbot2000** [comment]
Hi,

  Have you set polling and interval?   There is no way for homebridge to
get updates, unless it queries the device itself.

TTFN,
John

**Comment by ztalbot2000** [comment]
Set interval too

**Comment by dmkpoznan** [comment]
Yes, I have polling enabled and interval set to 1 second (as far as I see in code it's multiplied by 1000 ms, as I understand).

**Comment by dmkpoznan** [comment]
Can I switch default target value to be closed, somehow?

**Comment by dmkpoznan** [comment]
Ok, I added line of code to change default state to be CLOSED and it's look like it's working. I will test it more, but main question: maybe we will add config option for switching default state of garage doors to be CLOSED? I can create pull request at the end.

**Comment by ztalbot2000** [comment]
Hi,

  The default state for the Garage Door opener of open  is not a concern as
they are just an example of what you can do with HomeBridge-Cmd4.

Take care,
  I am happy you have things working,
John Talbot

**Comment by dmkpoznan** [comment]
Ok, I found what I need here:

https://github.com/KraigM/homebridge-gpio-garagedoor/blob/b698f597f447dde5d48db84fbfdb0ee0642b12f1/lib/DoorSensorPort.ts

The part with "handle external state". I'm trying now implementing sth similar in Cmd4 BUT I'm not familiar with structure of services here, so this could tak a while. Maybe You have fast idea & solution how to?

**Comment by dmkpoznan** [comment]
I'm testing, but this looks like fixed problem with updating external state:

`      service.getCharacteristic(Characteristic.CurrentDoorState)
      .on('get', (callback) => {
        this.getValue("CurrentDoorState", callback);
//external state fix here:
        var isClosed = service.getCharacteristic(Characteristic.CurrentDoorState).value;
        var targetState = service.getCharacteristic(Characteristic.TargetDoorState).value;
                if ((isClosed == 0 && targetState == 1)
                                || (isClosed == 1 && targetState == 0)) {
                                service.getCharacteristic(Characteristic.TargetDoorState)
                                        .setValue(isClosed == 1 ? Characteristic.TargetDoorState.CLOSED : Characteristic.TargetDoorState.OPEN);
                        }

                if ((isClosed == 3 && targetState == 0)
                                || (isClosed == 2 && targetState == 1)) {
                                service.getCharacteristic(Characteristic.TargetDoorState)
                                        .setValue(isClosed == 3 ? Characteristic.TargetDoorState.CLOSED : Characteristic.TargetDoorState.OPEN);
                        }

      });
`

**Comment by ztalbot2000** [comment]
Hi,

  You do not have to change the CMD-4 module at all.  Just alter or create
your own script and or scripts  similar to State.js in whatever language
you choose.  The received data format is at the top and also in the README
file.

ttfn,
John Talbot

**Comment by dmkpoznan** [comment]
Ok, but how I can change Target State from my code after detecting external state change (for example garage doors opened by manual button on engine)?

When Target State will be not changed the status of garage doors will be “opening...” or “closing...” instead of “Closed” or “Opened”.

In State.js example this problem also exists.

**Comment by ztalbot2000** [comment]
Closed as per previous correspondence
