### ISSUE TITLE
Where to put State.js when running Homebridge as systemd service?

### ISSUE THREAD

**Issue by dieserNiko** [ztalbot2000/homebridge-cmd4#18]
Hey,

first of all thanks for this great plugin! 

Sadly I'm kinda stuck at the moment... in your readme you said I'd have to put the State.js file in ~/.homebridge/Cmd4Scripts but I'm running Homebridge as systemd service and my main directory (which contains the config.json etc) are located at /var/homebridge so I put my Cmd4Scripts folder with the State.js file in there... I just tested my first On/Off script but I'm not sure if it doesn't work as expected because I made a mistake in the script or if the state.js file doesn't work because it's in the right place.

I hope my question is no duplicate.

Thanks in advance,
Niko :)

**Comment by dieserNiko** [comment]
Ok, in the meantime I got the script based on the PS4.sh to work, but the Homebridge logs output on each polling interval shows the following:
`[Cmd4] Cmd4 getGeneric On function for: Stairs cmd: bash /var/homebridge/Cmd4Scripts/stairs.sh Get 'Stairs' 'On' failed.
[2/26/2019, 11:06:54 AM] [Cmd4] { Error: Command failed: bash /var/homebridge/Cmd4Scripts/stairs.sh Get 'Stairs' 'On'
    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:188:13)
    at maybeClose (internal/child_process.js:978:16)
    at Socket.stream.socket.on (internal/child_process.js:395:11)
    at Socket.emit (events.js:188:13)
    at Pipe._handle.close (net.js:610:12)
  killed: false,
  code: 255,
  signal: null,
  cmd:
   "bash /var/homebridge/Cmd4Scripts/stairs.sh Get 'Stairs' 'On'" }
[2/26/2019, 11:06:54 AM] [Cmd4] 1
[2/26/2019, 11:06:54 AM] [Cmd4]`
and the Home App shows "No Response" for my "Stairs" accessory which I use to test my scripts.

I also changed the State.js a bit so it references to "/var/homebridge/Cmd4Scripts" instead of  "./homebridge/Cmd4Scripts" but if I type `node State.js Get Stairs On` it answers `Unknown Device for:Set: Device:Stairs`. 

Any idea what could be the reason for all of this and what I could change to fix it? 🤔

**Comment by ztalbot2000** [comment]
In this case you would have to modify the homebridge  config.json file so that the state_cmd options point to the correct path.  If you look at the config.json file, you will get the idea.

Thanks for trying my plugin,
John Talbot

**Comment by dieserNiko** [comment]
Yes I know how to set the path, but if I run `bash /var/homebridge/Cmd4Scripts/stairs.sh Get 'Stairs' 'On'` from the console it works and in the homebridge logs it also shows the right output after the error (second last line, the output is 1) but I get the error in Homebridges-cmd4 anyway… so what could cause this?

**Comment by ztalbot2000** [comment]
Try running

DEBUG=* homebridge -D .

In the README it also says that the return of the request for ON is either
1 or 0.  This is based on the hap spec and I cannot change it.  Maybe that
is your issue with your script?

ttfn,
John Talbot

**Comment by dieserNiko** [comment]
Hmm Okey I’ll try to start with -D, didnt’t try that until now… I wrote the script so that I can either use it with script.sh Set Name On 1/0 or true/false so that shouldn’t be the problem… and I also don’t really understand the error as it works anyway… maybe the debug option gives me a better idea… thanks for the tip! :)

**Comment by ztalbot2000** [comment]
Hi,

   If you do not see enough debug messages, edit hombridge-cmd4/index.js
and uncomment out the lines with DEBUG in them.  They are most helpful.

John Talbot

**Comment by dieserNiko** [comment]
Hi, so I tried it now with all the debug options and I even changed the path of my script to make sure there is no permission problem and this is still what I get, even if I run it from the console and not as a service:

> [2/27/2019, 9:06:06 AM] [Cmd4] DEBUG: Cmd4 getValue On function for: Stairs cmd: bash /home/homebridge/scripts/stairs.sh Get 'Stairs' 'On'
> [...]
> [2/27/2019, 9:06:06 AM] [Cmd4] Cmd4 getGeneric On function for: Stairs cmd: bash /home/homebridge/scripts/stairs.sh Get 'Stairs' 'On' failed.
> [2/27/2019, 9:06:06 AM] [Cmd4] { Error: Command failed: bash /home/homebridge/scripts/stairs.sh Get 'Stairs' 'On'
> 
>     at ChildProcess.exithandler (child_process.js:294:12)
>     at ChildProcess.emit (events.js:188:13)
>     at maybeClose (internal/child_process.js:978:16)
>     at Socket.stream.socket.on (internal/child_process.js:395:11)
>     at Socket.emit (events.js:188:13)
>     at Pipe._handle.close (net.js:610:12)
>   killed: false,
>   code: 255,
>   signal: null,
>   cmd: "bash /home/homebridge/scripts/stairs.sh Get 'Stairs' 'On'" }
> [2/27/2019, 9:06:06 AM] [Cmd4] 1
> 
> [2/27/2019, 9:06:06 AM] [Cmd4] 

I have no clue what could still cause this error... do those Js errors make any sense to you?

Niko

**Comment by dieserNiko** [comment]
Okay, I just found out that I was just a bit stupid and didn't copy the script as it is in the example... I just left out the `exit 0` after every single answer which produced the errors... 

Thanks for your help anyway and keep going, I love this plugin :)
Niko

**Comment by ztalbot2000** [comment]
Can you send me the script you are running ?

**Comment by dieserNiko** [comment]
Okay, so here is my script I am running now and which is working fine:

> #!/bin/bash
> 
> if [ "$1" = "Get" ]; then
>    # $2 would be the name 'Test'
>    # $3 would be the charactersistic 'On'
>    if [ -f '/home/homebridge/scripts/RemoteSockets/entertainment.stat' ]; then
>       echo "1"
>       exit 0
>    else
>       echo "0"
>       exit 0
>    fi
> fi
> 
> if [ "$1" = "Set" ]; then
>    # $2 would be the name 'Test'
>    # $3 would be the the charactersistic 'On'
>    # $4 would be '0' for 'On' and '1' for 'Off'
> 
>    if [ "$4" = "true" ] || [ "$4" = "0" ]; then
>       /usr/bin/python /home/homebridge/scripts/RemoteSockets/entertainmenton.py
>       exit 0
>    fi
>    if [ "$4" = "false" ] || [ "$4" = "1" ]; then
>       /usr/bin/python /home/homebridge/scripts/RemoteSockets/entertainmentoff.py
>       exit 0
>    fi
> fi
> 
> exit -1

and before I forgot every `exit 0` and that's why it didn't work ¯\_(ツ)_/¯

**Comment by ztalbot2000** [comment]
I don't know if you sent me your config.json file, but if you have not, may
I have it too?

**Comment by dieserNiko** [comment]
Sure, sorry 😅 here you go :)

> {
>     "bridge": {
>         "name": "piBridge v3",
>         "username": "A0:FE:91:BB:C4:D9",
>         "port": 51826,
>         "pin": "012-34-567",
>         "ssdp": 1900
>     },
>     "platforms": [
>         {
>             "platform": "config",
>             "name": "Config",
>             "port": 8080,
>             "auth": "form",
>             "theme": "red",
>             "restart": "sudo -n systemctl restart homebridge",
>             "temp": "/sys/class/thermal/thermal_zone0/temp",
>             "sudo": true,
>             "log": {
>                 "method": "systemd",
>                 "service": "homebridge"
>             }
>         },
>         {
>             "platform": "Alexa",
>             "name": "Alexa",
>             "username": "dieserNiko",
>             "password": "qejGun-padri9-poxnaw",
>             "pin": "012-34-567"
>         },
>         {
>             "platform": "Cmd4",
>             "name": "Cmd4",
>             "accessories": [
>                 {
>                     "type": "Lightbulb",
>                     "name": "Stairs",
>                     "on": false,
>                     "state_cmd": "bash /home/homebridge/scripts/stairs.sh",
>                     "polling": false,
>                     "interval": 60,
>                     "timeout": 2000
>                 },
>                 {
>                     "type": "Outlet",
>                     "name": "Chargers",
>                     "on": false,
>                     "state_cmd": "bash /home/homebridge/scripts/outlets.sh",
>                     "polling": false,
>                     "interval": 60,
>                     "timeout": 2000
>                 },
>                 {
>                     "type": "Lightbulb",
>                     "name": "Stripes",
>                     "on": false,
>                     "state_cmd": "bash /home/homebridge/scripts/outlets.sh",
>                     "polling": false,
>                     "interval": 60,
>                     "timeout": 2000
>                 },
>                 {
>                     "type": "Fan",
>                     "name": "Fan",
>                     "on": false,
>                     "state_cmd": "bash /home/homebridge/scripts/outlets.sh",
>                     "polling": false,
>                     "interval": 60,
>                     "timeout": 2000
>                 }
>             ]
>         }
>     ],
>     "accessories": [
>         {
>             "accessory": "BlindsHTTP",
>             "name": "Canvas",
>             "up_url": "http://localhost:8888/canvasup",
>             "down_url": "http://localhost:8888/canvasdown",
>             "stop_url": "http://localhost:8888/canvasstop",
>             "motion_time": "40000",
>             "http_method": "PUT",
>             "trigger_stop_at_boundaries": true
>         },
>         {
>             "name": "Entertainment",
>             "accessory": "Script2",
>             "on": "/home/homebridge/scripts/RemoteSockets/entertainmenton.py",
>             "off": "/home/homebridge/scripts/RemoteSockets/entertainmentoff.py",
>             "fileState": "/home/homebridge/scripts/RemoteSockets/entertainment.stat",
>             "on_value": "true",
>             "exact_match": true
>         },
>         {
>             "name": "LED Stripes",
>             "accessory": "Script2",
>             "on": "/home/homebridge/scripts/RemoteSockets/stripeson.py",
>             "off": "/home/homebridge/scripts/RemoteSockets/stripesoff.py",
>             "fileState": "/home/homebridge/scripts/RemoteSockets/stripes.stat",
>             "on_value": "true",
>             "exact_match": true
>         },
>         {
>             "name": "Ventilator",
>             "accessory": "Script2",
>             "on": "/home/homebridge/scripts/RemoteSockets/fanon.py",
>             "off": "/home/homebridge/scripts/RemoteSockets/fanoff.py",
>             "fileState": "/home/homebridge/scripts/RemoteSockets/fan.stat",
>             "on_value": "true",
>             "exact_match": true
>         },
>         {
>             "name": "Ventilator für 30 Minuten",
>             "accessory": "Script2",
>             "on": "/home/homebridge/scripts/dummy.py",
>             "off": "/home/homebridge/scripts/dummy.py",
>             "on_value": "true",
>             "exact_match": true
>         },
>         {
>             "accessory": "Script2",
>             "on": "/home/homebridge/scripts/dummy.py",
>             "off": "/home/homebridge/scripts/RemoteSockets/shutdownsafe.sh",
>             "on_value": "true",
>             "exact_match": true,
>             "name": "Safe Shutdown"
>         },
>         {
>             "accessory": "Script2",
>             "on": "/home/homebridge/scripts/dummy.py",
>             "off": "/home/homebridge/scripts/dummy.py",
>             "on_value": "true",
>             "exact_match": true,
>             "name": "Ff30m Dummy"
>         },
>         {
>             "name": "Leinwand",
>             "accessory": "Script2",
>             "on": "/home/homebridge/scripts/Canvas/down.py",
>             "off": "/home/homebridge/scripts/Canvas/up.py",
>             "on_value": "true",
>             "exact_match": true
>         },
>         {
>             "name": "WebSwitch UIMode",
>             "accessory": "Script2",
>             "on": "/home/homebridge/scripts/day.sh",
>             "off": "/home/homebridge/scripts/night.sh",
>             "fileState": "/var/www/html/css/style_night.css",
>             "on_value": "true",
>             "exact_match": true
>         },
>         {
>             "accessory": "RaspberryPiTemperature",
>             "name": "PiTemperature"
>         },
>         {
>             "accessory": "HTTP-SWITCH",
>             "name": "Papierlampe",
>             "httpMethod": "GET",
>             "onUrl": "http://localhost:1080/devices/10001e24e3/on",
>             "offUrl": "http://localhost:1080/devices/10001e24e3/off",
>             "statusUrl": "http://localhost:1080/devices/10001e24e3/status"
>         },
>         {
>             "accessory": "HTTP-SWITCH",
>             "name": "Deckenlicht",
>             "httpMethod": "GET",
>             "onUrl": "http://localhost:1080/devices/10001e0190/on",
>             "offUrl": "http://localhost:1080/devices/10001e0190/off",
>             "statusUrl": "http://localhost:1080/devices/10001e0190/status"
>         },
>         {
>             "accessory": "HTTP-SWITCH",
>             "name": "Ladegeräte",
>             "httpMethod": "GET",
>             "onUrl": "http://localhost:1080/devices/10001d6ebc/on",
>             "offUrl": "http://localhost:1080/devices/10001d6ebc/off",
>             "statusUrl": "http://localhost:1080/devices/10001d6ebc/status"
> },
>         {
>             "accessory": "MagicHome",
>             "name": "Bett",
>             "ip": "10.0.0.37",
>             "setup": "RGBW",
>             "purewhite": false
>         },
>         {
>             "accessory": "MagicHome",
>             "name": "Decken LED",
>             "ip": "10.0.0.38",
>             "setup": "RGBW",
>             "purewhite": false
>         },
>         {
>             "accessory": "MagicHome",
>             "name": "Couch",
>             "ip": "10.0.0.39",
>             "setup": "RGBW",
>             "purewhite": false
>         }
>     ]
> }

**Comment by ztalbot2000** [comment]
So I think I found the issue.  It is really a documentation thing.  If you
look at State.js you will see:

if (length >= 2) io = process.argv[2];

if (length >= 3) device = process.argv[3];

if (length >= 4) characteristic  = process.argv[4];

if (length >= 5) option  = process.argv[5];

so if your config.json file says "state_cmd": "bash /path/test"
then the $1 is 'bash' and not 'Get'
so in your case change $1 to $2,   $2 to $3.  etc

I can update the documentation if this answers your question.  Let me know
if you have resolved it based on this answer.

Thanks,
John Talbot

**Comment by ztalbot2000** [comment]
I may have the explanation wrong, but the answer is correct.  Sorry I got
to go to lunch and am answering quickly.

**Comment by dieserNiko** [comment]
No problem, it’s working fine now so i‘m absolutely happy with it :)

But if you like, you could give another example than the PS4.sh as it is not so easy to understand if you never worked with the PlayStation waker tool, it is a bit complicated to understand and I really needed some time to get what the script does and how it does it!

**Comment by ztalbot2000** [comment]
I just pushed out 1.2.7
Mainly the documentation was changed, but I did verify the Raspbian Stretch install as well as an example bash PS4.sh script.

ttfn,
John Talbot
