### ISSUE TITLE
Feature request: integrate fakegato-history module 

### ISSUE THREAD

**Issue by TimofeyK** [ztalbot2000/homebridge-cmd4#19]
First of all - HUGE thank you for this plugin!!! I successfully connected my dumb aircon wi-fi controller and Oregon BLE weather station to HomeKit using simple bash scripts

This issue is to ask you to please consider integrating support for fakegato-history to be used with temperature/humidity sensors

This module saves a log with temp/humidity values and exposes it to Eve app. The app draws very nice graphs so you can see historical values

https://www.npmjs.com/package/fakegato-history  

Thank you again!

**Comment by ztalbot2000** [comment]
Interesting,

  I will have a look but cannot promise anything.  My only concern is that
it means my plugin requires another, but if I can figure out how to only
use the fakegato if it is installed, I will try.  If I close this request,
it is not because.I will not do it, it is just to show that there are no
outstanding issues.  This is more of a feature.

ttfn,
John Talbot

**Comment by TimofeyK** [comment]
Thanks John!

Fakegato-history doesn’t not require manual install, it’s installed as a dependency to the Homebridge plugin

I used it as a part of https://github.com/hannseman/homebridge-mi-hygrothermograph and I did not need installing it separately

**Comment by ztalbot2000** [comment]
Thanks for the clarification.  I will see what I can do.  I'm working on my
CNC at the moment and it is so close to be fully calibrated.  This document
is not complete but the video is cool.

http://benicegames.com/CNC/MyCNCBook.pdf


http://www.benicegames.com/CNC/CNCDrawing.mp4

BeNiceGames is my web site for my free IOS apps, I also use it as a place
to put files, instead of attaching them.



ttfn,
John Talbot

**Comment by ztalbot2000** [comment]
I started coding this.  I do not know when it will be done. The API is okay, but incomplete for many devices, I will see what I can do with what is available.
The only thing I do. not like is the note that when using GoogleDrive to store the history on, you can potentially corrupt the data with multiple writes at the same time. This is a red flag in that they do not know how to handle concurrency.  
Homebridge-cmd4 handles concurrency for state information by having each devices status placed into a different file.  See files in Cmd4States directory.
So I am working on it.  I will close this but as I previously mentioned, it is not forgotten.  I will also update the logs of this issue as time goes on.

P.S.  I just got some new parts for my CNC, so I will probably start again tomorrow on this.
ttfn,
John Talbot

**Comment by ztalbot2000** [comment]
Just to let you know that I made significant progress on this feature. Everything is coded and testing of a fake thermostat works. FakeGato is not by default part of Homebridge like you mentioned. It is part of Eve. I was able to include it as an option defined in your config.json file if storage of fs is defined for the accessory.
All this still needs to be documented in my ReadMe.  You might have it all in a week.

TTFN,
John

**Comment by TimofeyK** [comment]
What I meant is that fakegato-history is an npm module that will be automatically installed as a dependency when installing your plugin. Sorry, I did not word it clearly enough!

**Comment by ztalbot2000** [comment]
Hi Tim,

    You are right and thank you ever so much for the clarification!  I was
not seeing it this way because I was adding in the functionality and not
installing it as npm would.. I can rip out the part where I check for the
availability of  the fakegatoHistory module and let npm handle it.  This
makes things cleaner and easier for the user to understand.

ttfn,
John Talbot

**Comment by ztalbot2000** [comment]
Hi Tim,,


 I  just checked everything into GitHub for this feature request you asked for.  I have not made an npm module of it yet. If you could give it a go by copying the index.js to the /usr/local/lib/node_modules/homebridge-cmd4 directory, make the appropriate config.json changes as detailed in the README.md or in the config.json file I include in Extras; It would be much appreciated.
Any feedback you give will be very helpful..

ttfn,
John Talbot

**Comment by TimofeyK** [comment]
Hi John,

It works partially so far

I loaded the new index.js (had to install fakegato-history and moment npm modules manually) and made changes to config as described

I have 3 temp, 3 humidity, thermostat and fan devices created via cmd4
I've found persist.json flies created for all sensors + thermostat and surprisingly for fan as well
So far Eve app recognised services for temperature/ humidity sensors + thermostat but values for thermostat sensor are all 50deg, for temp/humidity are all null and not changing

Below is the content of persist files

Homebridge_T0_persist.json
{"firstEntry":0,"lastEntry":2,"usedMemory":2,"refTime":575268616,"initialTime":1553575816,"history":["noValue",{"time":1553575816,"setRefTime":1},{"temp":null,"humidity":null,"ppm":null,"time":1553575816}]}

Homebridge_Aircon_persist.json
{"firstEntry":0,"lastEntry":29,"usedMemory":29,"refTime":575268095,"initialTime":1553575295,"history":["noValue",{"time":1553575295,"setRefTime":1},{"time":1553575295,"currentTemp":50,"setTemp":25,"valvePosition":0},{"time":1553575295,"currentTemp":50,"setTemp":25,"valvePosition":0},

**Comment by TimofeyK** [comment]
I think I know why "null" in temp/humidity sensors log:

         case  "TemperatureSensor":
         {
            this.loggingService.addEntry({time: moment().unix(), temp:**this.temperature**, humidity:**this.humidity**, ppm:this.ppm});
            break;
         }

These characteristics called "currentTemperature" and "currentRelativeHumidity". Thermostat log has "currentTemperature" and shows default value of 50 deg

But both this. currentTemperature  and this. currentRelativeHumidity  aren't set to the actual HK values in the code

**Comment by ztalbot2000** [comment]
Hi Tim,

   Thanks so much for trying it out.  You did well debugging to get it
going and I'll look into why it is not changing.

John Talbot

**Comment by ztalbot2000** [comment]
Hi Tim,

   homebridge-cmd4 never stored internally the accessories current state. It just returned to the app what was retrieved. fakegato would just write the log of the initial value in the config.json file. This is what you were seeing.
  I made the change to Homebridge-cmd4 to update the variables of the state retrieved so that they are correctly written to the fakegato log.
  I changed index.js.   I also changed config.json to not poll everything by default.

Let me know what you think when you get time.
John Talbot

**Comment by TimofeyK** [comment]
Nearly there!

1. Thermostat sensor started logging temp correctly
2. Temperature and Humidity logs still had 'null' values. Then I noticed in the code that it still has wrong variable names in the addEntry method, must be a copy-past issue
              this.loggingService.addEntry({time: moment().unix(), temp:**this.temperature**, humidity:**this.humidity**, ppm:this.ppm});
I changed them to currentTemperature and currentRelativeHumidity and the logging to files started working correctly BUT... 
3. Eve app shows the same values for all 3 different Temperature sensors and same values for all Humidity sensors. I have 3 of each and they are named T0, T1 and T2 + H0, H1 and H2. Eve app shows T0 and H0 for all sensors. Also if I delete stored measurements in the app for one sensor it deletes them for all sensors. Somehow the app shows the same log for all sensors

**Comment by TimofeyK** [comment]
Correction to the N3 above: Eve app shows measurements for the same sensor for all 3 sensors of the type but it’s not always T0. At some point it started showing values from another sensor

**Comment by ztalbot2000** [comment]
Tim,

   Thank again for your great debug work.  I jut got it logging data and
did not investigate further. You have done more than I. Fantastic wok on
your side.

Ill see what else i can find.  I certainly have never tried it with
multiple device of the same type.

TTFN,
John

**Comment by ztalbot2000** [comment]
Hi Tim,
   Fakegato accessory attributes do not map very well. I did the best I could all considering.
I did test multiple accessories with the same type and could not find an issue. The latest changes made just have those you requested, plus some other mapping fixes and documentation.

Let me know if all goes well.

ttfn,
John Talbot

**Comment by ztalbot2000** [comment]
I just remembered something I wanted to tell you.  It is best that you do not put spaces in the accessory names because that can throw off command line parsing.  I do not know if you do this, but just in case.

TTFN,
John

**Comment by TimofeyK** [comment]
Hi John,

Thanks a lot for all your efforts! Still the same result, unfortunately. I can see that all persist.json files have correct values logged but Eve app still shows the same set of values for all accessories of the same type. Maybe this is fakegato's own issue or even Eve app's bug. And this is, after all, a hack to feed fake data to an official Eve app!

Device names in my config are T0, T1, T2, H0 etc so no spaces

For now I removed fakegato-history from the Platform level and only added for one Temperature and one Humidity sensor. In this config it works correctly

BTW, is there a way to configure CMD4 for a single device with multiple characteristic? All my sensors measure both temperature and humidity but I had to configure them as separate devices

**Comment by ztalbot2000** [comment]
Hey Tim.

  So fakegato Thermo has both temperature and humidity, so if you configure
it as a thermostat, you will get both.  FakeGato does not map well to the
Hap spec.

I see as you see the stuff being logged correctly.  I will see what IOS
does with multiple accessories of the same type.  Right now I think it is a
FakeGato thing though.

TTFN,
John

**Comment by ztalbot2000** [comment]
A thermostat does not poll for humidity,but i can change that.
John

**Comment by TimofeyK** [comment]
Sorry, I again didn't explain in full. I have 3 temperature/humidity sensors which I had to configure as 6 separate accessories. This does not make sense to expose them as Thermostats because I will get all CoolingHeating modes etc and mandatory characteristics

What I meant is that native HomeKit devices and also some other Homebridge plugins expose a single device with multiple services such Temperature, Humidity etc.

Example: https://github.com/hannseman/homebridge-mi-hygrothermograph/blob/master/lib/accessory.js - this one exposes one accessory with Temperature, Humidity, Battery and Fakegato-History services

I guess in CMD4 this isn't possible because of its architecture and the fact that you support **all** kind of devices based on HAP spec

**Comment by ztalbot2000** [comment]
Hi Tim,

   This is true if you create custom accessories that have custom
characteristics.  Essentially you can add any characteristic to an
accessory, but Homebridge-cmd4 follows the hap spec which defines only
certain characteristics for each accessory.
I would have to think on how to handle that.  It may not be as easy as a
custom plugin.

TTFN,
John

**Comment by TimofeyK** [comment]
Eureka! 

I think I found how to resolve the Eve app mixing up measurements!
I came across this issue which mentions requirement of a unique serial number for devices of the same type: https://github.com/simont77/fakegato-history/issues/60

That makes sense, all my sensor had the same Serial number constructed by the CMD4 code

I changed one line to add accessory name to the serial number to make it unique (and also dropped the space, just in case)

.setCharacteristic(Characteristic.SerialNumber, "Cmd4" + this.config.type + this.config.name);

Configured all 6 sensors again and... it works now! :-)

**Comment by ztalbot2000** [comment]
Hey Tim,

  This is great news!  I will implement this.

My fake sensors were running all night and I had measurements in the history logs in Eve this morning.  I had made some other changes and if I do not  need to implement them, that would be good. Are you getting history measurements?   They do not appear immediately and that was one of my concerns. It must be a fakegato thing.

Let me know if yours has history measurements.

ttfn,
John

**Comment by ztalbot2000** [comment]
Hey Tim,

   From the code, I guess we could have also added a unique serial number to the config.json file instead.  I don't know if the SerialNumber gets parsed anyway, but I will add it too.

ttfn,
John

**Comment by ztalbot2000** [comment]
no I got that wrong. ignore last message

**Comment by TimofeyK** [comment]
Everything works beautifully since I changed serial numbers
I had a problem when Eve app would read only one measurement after I reset history files and reinstalled the app but that was likely app’s problem because it started working after I rebooted the phone

I don’t think there is a real need to have a configurable serial number 

Initial measurements  appear with a delay, that’s true. I think it takes up to 20 min to start receiving measurements for the first time. Also they don’t update if you’re not on wi-fi I think

For Cmd4 I think it’s good for release as is with only serial number change 

Thank you!

**Comment by ztalbot2000** [comment]
Thanks Tim,

   I agree with your findings.   I was testing the install process as
dependencies are added with fakegato and moment.  It all checks out so I
will be submitting everything shortly.  Under changes of 2.30 I will be
giving you credit as your help was extremely valuable.

ttfn,
John Talbot

**Comment by ztalbot2000** [comment]
Hi Tim,

  The final changes were checked in and a new npm package released.  Thanks for all your help.

John

**Comment by ztalbot2000** [comment]
Hi Tim,

   In branch b_v2.0_dev I've rewritten mostly everything, except the get/set methods so everything in that regard is the same.
  I remembered that you had a device with two types of characteristics.  This branch supports the ability to add any characteristic to an accessory.  You may wish to try this on your Homebridge setup.  fakegato is also improved, as is polling and adding in TV ....

Let me know what you think.  I will be away for a few days so I am only able to put it in a branch, though everything looks good.

**Comment by TimofeyK** [comment]
Thank you John!

I am away myself so will install 2.0 when I am back in 2 weeks

**Comment by TimofeyK** [comment]
Hi John,

Sorry it took me very long time to finally update to 2.x, I had a new arrival in the family and didn't have time to touch my setup

After updating to the latest build and re-configuring Fakegato I am having a new issue with the history "stuck" on the same value for long period of time then update to the actual value, then stay on that value for long time again

I am sure that values passed to the plugin were correct and changed over time because they stay in a sqlite table from where the plugin reads them  

Also I can see actual current values when I open Home app

It looks as if polling wasn't working properly and feed a stale value to fakegato (or fakegato fudging values because nothing returned from the plugin) and values only update when I open Home app and a new value is explicitly read by the plugin

My config for sensors is:

`                 {
`                    "type": "TemperatureSensor",
`                   "name": "TH0",
`                   "currentTemperature": 0,
`                    "currentRelativeHumidity": 0,
`                    "polling": [
`                        {
`                            "currentTemperature": 0,
`                            "currentRelativeHumidity": 0,
`                            "interval": 300,
`                            "timeout": 3000
`                        }
`                    ],
`                    "fakegato": {
`                        "eve": "room",
`                        "temp": "currentTemperature",
`                        "humidity": "currentRelativeHumidity",
`                        "storage": "fs"
`                    },
`                    "stateChangeResponseTime": 1,
`                    "state_cmd": "bash /home/pi/Cmd4Scripts/oregon.sh"
`                },

Similarly configured polling works for a thermostat though I don't use fakegato with it

Is there anything wrong in the config above?

**Comment by ztalbot2000** [comment]
Hi Tim,

  I'll have a peek later.  I'm sure your config is correct. It looks that
way.
  There was tons of redundant code in the first version that we worked on
together, spelling mistakes too.  Now everything is in a table that has
7000+ test cases against it.
  I assume that you checked the stored FakeGato history data to see that it
is changing.  I'll look at FakeGato to see if anything they did caused your
issue.

TTFN,
John

**Comment by ztalbot2000** [comment]
is  "storagePath":  ".homebridge/FakegatoStorage",
missing from your config.json file?  does HomeBridge-cmd4 say its missing?

ttfn,
John

**Comment by TimofeyK** [comment]
storagePath is optional for Fakegato spec, by default .homebridge is used

I found the issue after running debug mode for a while: polling is only called for currentRelativeHumidity so currentTemperature logged with the last known value. Was hard to notice that humidity logged actual values as it’s not changing as noticeable as temperature

Once I removed humidity from configured polling the temperature started getting polled (“Doing poll of index:38 characteristic:CurrentTemperature...” started showing in the log)

**Comment by TimofeyK** [comment]
Looks like polling only works for only one characteristic

**Comment by TimofeyK** [comment]
Aaah, my bad! I looked at the example of polling config in the readme and realised I did it wrong! I put both characteristics in the same brackets section

After fixing the config both characteristics showing in the debug log

**Comment by ztalbot2000** [comment]
Hi Tim,

  You are correct about the path being optional and the data written to
.homebridge.  I just found that out myself.
I'll check on polling for the one characteristic.  This should not be.

TTFN,
John

**Comment by ztalbot2000** [comment]
Hi Tim,

  I'm glad you figured it out.
I think one of the other things you used to worry about was that you had
two sensors and the serialNumber had to be unique.  I believe I allowed you
to specify your own Unique serialNumber in your config.json file. If you
don't, I still make it unique the old way.

TTFN,
John

**Comment by ztalbot2000** [comment]
hi Tim,

   I looked at the code for polling.  it kind of accepts what you did, but
would then only poll the second one defined.  I can either put a warning,
or fix it to accept what you did.  I prefer the warning, what would you
like?

John

**Comment by TimofeyK** [comment]
Warning should be fine, you can’t possibly cover all potential config errors anyway

Btw, I configured humidity as an extra characteristic of the temperature sensor. This must be weird from HAP point of view I guess and your log says that :) I think the expected configuration is an accessory with two services each having its own characteristics

Anyway, it works fine and even better - humidity is not showing as a separate device but still visible in Eve if I need it

Thank you again!

**Comment by ztalbot2000** [comment]
Hi Tim,

   I pushed out 2.2.2 that makes defining two characteristics for each
characteristic polling item an error.  I prefer it as an error, because
most do not look at the logs and I have been enforcing any configuration
problem to be an error so that people know right away there is a problem
and I get less issue reports.

  P.S. You will notice that when you restart home bridge, it will tell you
that there is a later version available.  A nice change since last time.

  I'm glad you enjoy.

ttfn,
John Talbot
