### ISSUE TITLE
how can i install state.js to complete homebridge cmd4 plugin?

### ISSUE THREAD

**Issue by veroled** [ztalbot2000/homebridge-cmd4#2]
Hi guys, I am trying to install homebridge-cmd4 link:https://www.npmjs.com/package/homebridge-cmd4, but I am hold on step3.

I first created mkdir .homebridge/Cmd4Scripts
then cp State.js .homebridge/Cmd4Scripts/State.js
But tell me it is a invalit file or directory.....

How Can I issue it?

**Comment by tilledminds** [comment]
You need to copy the State.js file from the Extras folder on GitHub.

**Comment by ztalbot2000** [comment]
This question was addressed and issue is closed.
thanks tilledminds for responding.
