### ISSUE TITLE
Unable to run .sh file

### ISSUE THREAD

**Issue by misanthrophy** [ztalbot2000/homebridge-cmd4#20]
Hi,

I want to run a .sh file, but I always get this error:

Apr 06 01:34:31 raspberrypi homebridge[6956]: [2019-4-6 01:34:31] [Cmd4] Cmd4 getGeneric On function for: PiHole cmd: bash /var/homebridge/cmd4/pihole.sh Get 'PiHole' 'On' failed.
Apr 06 01:34:31 raspberrypi homebridge[6956]: [2019-4-6 01:34:31] [Cmd4] { Error: Command failed: bash /var/homebridge/cmd4/pihole.sh Get 'PiHole' 'On'
Apr 06 01:34:31 raspberrypi homebridge[6956]: /var/homebridge/cmd4/pihole.sh: Zeile 7: Syntaxfehler beim unerwarteten Wort `newline'
Apr 06 01:34:31 raspberrypi homebridge[6956]: /var/homebridge/cmd4/pihole.sh: Zeile 7: `<!DOCTYPE html>'
Apr 06 01:34:31 raspberrypi homebridge[6956]:     at ChildProcess.exithandler (child_process.js:281:12)
Apr 06 01:34:31 raspberrypi homebridge[6956]:     at emitTwo (events.js:126:13)
Apr 06 01:34:31 raspberrypi homebridge[6956]:     at ChildProcess.emit (events.js:214:7)
Apr 06 01:34:31 raspberrypi homebridge[6956]:     at maybeClose (internal/child_process.js:915:16)
Apr 06 01:34:31 raspberrypi homebridge[6956]:     at Socket.stream.socket.on (internal/child_process.js:336:11)
Apr 06 01:34:31 raspberrypi homebridge[6956]:     at emitOne (events.js:116:13)
Apr 06 01:34:31 raspberrypi homebridge[6956]:     at Socket.emit (events.js:211:7)
Apr 06 01:34:31 raspberrypi homebridge[6956]:     at Pipe._handle.close [as _onclose] (net.js:561:12)
Apr 06 01:34:31 raspberrypi homebridge[6956]:   killed: false,
Apr 06 01:34:31 raspberrypi homebridge[6956]:   code: 2,
Apr 06 01:34:31 raspberrypi homebridge[6956]:   signal: null,
Apr 06 01:34:31 raspberrypi homebridge[6956]:   cmd: 'bash /var/homebridge/cmd4/pihole.sh Get \'PiHole\' \'On\'' }
Apr 06 01:34:31 raspberrypi homebridge[6956]: [2019-4-6 01:34:31] [Cmd4]
Apr 06 01:34:31 raspberrypi homebridge[6956]: [2019-4-6 01:34:31] [Cmd4] /var/homebridge/cmd4/pihole.sh: Zeile 7: Syntaxfehler beim unerwarteten Wort `newline'
Apr 06 01:34:31 raspberrypi homebridge[6956]: /var/homebridge/cmd4/pihole.sh: Zeile 7: `<!DOCTYPE html>'

The pihole.sh file looks like this: 

#!/bin/bash

if [ "$1" = "Get" ]; then
   # $2 would be the name 'PiHole'
   # $3 would be the charactersistic 'On'
   state=$(pihole status | grep -c Enabled)
   if [[ "$state" = "0" ]]; then
     echo "$state"
     exit 0
   elif [[ "$state" = "1" ]]; then
     echo "$state"
     exit 0
   fi
fi

if [ "$1" = "Set" ]; then
   # $2 would be the name 'PiHole'
   # $3 would be the the charactersistic 'On'
   # $4 would be '0' for 'Off', '1' for 'On'

   if [ $4 = true ]; then
      pihole enable
      exit $?
   elif [ $4 = false ]; then
      pihole disable
      exit $?
   fi
fi

exit -1

And my config.json looks like this: 

{
            "platform": "Cmd4",
            "name": "Cmd4",
            "accessories": [
                {
                    "type": "Switch",
                    "name": "PiHole",
                    "on": false,
                    "polling": true,
                    "interval": 5,
                    "timeout": 2000,
                    "state_cmd": "bash /var/homebridge/cmd4/pihole.sh"
                }
            ]
        },

Does anyone see where the issue is?

Thanks in advance!

**Comment by ztalbot2000** [comment]
Hi,

Run the command from the shell prompt.
Echo. $1 ... as a debug statement,

Let me know how you make out.

TTFN,
John

**Comment by ztalbot2000** [comment]
After a Set a Get is done.
I tired the Get, it seems okay.
The Set for $4 seems incorrect.
  The command sent would be:
     Set PiHole On true
or
    Set PiHole On false

There is a note in the README about Homebridge sending true, but
Homebridge-cmd4 interpreting the results as either 0 or 1.

 pihole enable
or pihole disable
must return 0 (Seccessful) according to your script.

I think you already did, but for debugging use:
DEBUG=* homebridge -D

I will check my mail tomorrow to see how you made out.

ttfn,
John

**Comment by misanthrophy** [comment]
Hi, I fixed it with another simpler way with the ssh plugin. So I will close this request. :)
