### ISSUE TITLE
Any plans to integrate new HomeKit TV integration to homebridge-cmd4?

### ISSUE THREAD

**Issue by MichlW** [ztalbot2000/homebridge-cmd4#21]
Hi contributors,

are there any plans to integrate the new HomeKit TV integration to homebridge-cmd4 in the next time?

Thanks to your great work in that.

Best regards.

**Comment by ztalbot2000** [comment]
I am working on the ability to add any characteristic to any accessory.
This is what a lot of other custom plugins do.
In my own dev tree I now have all characteristics available to Homebridge,
not just what is in Apple's Hap spec.  I hope to release this before next
Thursday.
  With this you could do just about anything.

Stay tunes ...

TTFN,
John

**Comment by ztalbot2000** [comment]
Placed in branch b_v2.0_dev.  Let me know what you think.

**Comment by ztalbot2000** [comment]
Now fixed in v2.0.   I have not yet made an npm module of it.
V2.0 should add increased stability and functionality too.
