### ISSUE TITLE
Switch no longer working

### ISSUE THREAD

**Issue by EugeneKallis** [ztalbot2000/homebridge-cmd4#24]
Cmd4 Warning: Unknown characteritic 'On' to update for accessory 'Server'

That's the error spammed in log. This was working up til about a couple weeks ago. I didnt change anything so i can only assume an update broke it.

config.json

```
       {
            "platform": "Cmd4",
            "name": "Cmd4",
            "accessories": [
                {
                    "type": "Switch",
                    "name": "Server",
                    "on": false,
                    "state_cmd": "sh /homebridge/Server.sh",
                    "polling": true,
                    "interval": 5,
                    "timeout": 2000
                }
            ]
        }
```

Server.sh

```
#!/bin/sh

if [ "$1" = "Get" ]; then
   # $2 would be the name 'PS4'
   # $3 would be the charactersistic 'On'
   ping -c 2 -W 1 192.168.1.90 | grep -i '2 packets received' >> /dev/null
   rc=$?
   if [ "$rc" = "0" ]; then
      echo "1"
      exit 0
   else
      echo "0"
      exit 0
   fi
fi

if [ "$1" = "Set" ]; then
   # $2 would be the name 'PS4'
   # $3 would be the the charactersistic 'On'
   # $4 would be '0' for 'On' and '1' for 'Off'

   if [ "$4" = "true" ]; then
      curl localhost:3001/api/commands/run/server_on
      exit $?
   fi
   if [ "$4" = "false" ]; then
      curl localhost:3001/api/commands/run/server_off
      exit $?
   fi
fi

exit -1

```

**Comment by ztalbot2000** [comment]
Strange!  I will look at it right away.  Are you running the latest 2.1.2?

TTFN,
John

**Comment by ztalbot2000** [comment]
You are correct.  For now, please use the new method for defining polling.
This works, as I just checked it.

"polling": [{"on": true, "interval": 540, "timeout":2000}

                           ]

**Comment by ztalbot2000** [comment]
fixed in 2.1.3, just pushed out

**Comment by EugeneKallis** [comment]
Hey thanks for the fast update/fix. I have to admit that you were right at first, i didnt have the latest version. I use this in a homebridge docker and i assumed that it updated the packages everytime it restarted but i was wrong. I have updated and now im seeing something different.


```
[5/22/2019, 9:56:28 AM] [Cmd4] { Error: Command failed: sh /homebridge/Server.sh Get 'Server' 'On'

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: 'sh /homebridge/Server.sh Get \'Server\' \'On\'' }
```
Then I connect to the docker and run it manually and get this.
```
/homebridge # ./Server.sh Get 'Server' 'On'
0
```

**Comment by ztalbot2000** [comment]
Hi,

   your state_cmd says 'sh /homebridge/Server.sh'
What you ran from the command line is not what Homebridges-cmd4 did.
What homebridge-cmd4 ran was
sh /homebridge/Server.sh 'Get' 'Server' 'On'

Is the path to Server.sh actually /homebridge/Server.sh     ???

I was working on a tool that would test peoples own scripts, because this
happens all the time.

Let me know how you make out.

ttfn,
John Talbot

**Comment by ztalbot2000** [comment]
I believe homebridge-cmd4 checks to see if the path of the state_cmd is
valid.  A warning would be generated and you would see this at the top of
the console.log.

ttfn,
John Talbot

**Comment by EugeneKallis** [comment]
Yes my current directory was in the /homebridge but i reran it from the root

```
/ # sh /homebridge/Server.sh 'Get' 'Server' 'On'
0
/ # 
```

**Comment by EugeneKallis** [comment]
I dont know if this helps but this was above the error message i posted earlier. 

`[5/22/2019, 2:21:46 PM] [Cmd4] getGeneric On function for: Server cmd: sh /homebridge/Server.sh Get 'Server' 'On' failed.`

**Comment by ztalbot2000** [comment]
Hi,

  If you paste that command exactly, from your home directory. What do you
get?

  The failure is because either the path to the command is wrong or the
script is wrong.  I do not see anything wrong with your script, so it has
to be the path.

ls /homebridge/Server.sh     Should pass.

John Talbot.

**Comment by EugeneKallis** [comment]
I just showed the exact command that its trying to run and the output which is 0. 

```
/ # sh /homebridge/Server.sh 'Get' 'Server' 'On'
0
/ # 
```

```
/homebridge # ls /homebridge/Server.sh 
/homebridge/Server.sh
```

**Comment by ztalbot2000** [comment]
I still cannot explain your problem.  Everything I try works here.

In github I just updated the README and added a tool called
CheckYourScript.sh.  It is not an npm module yet. You will have to get it
from GitHub.  I'm hoping if you give it a go it might flag your fault.  In
your case you would do:
cp CheckYourScript.sh $HOME/.homebridge/Cmd4Scripts
chmod 755 $HOME/.homebridge/Cmd4Scripts/CheckYourScript.sh
SHELL> cd $HOME
SHELL> '.homebridge/Cmd4Scripts/CheckYourScript.sh 'sh'
'/homebridge/Server.sh' 'Get' 'Server' 'On'

The quotes around everything is important to prevent globing.

Let me know if this helps you.

**Comment by ztalbot2000** [comment]
I tried my new CheckYourScript on your Server.sh and it passed :-(

Good news is I duplicated your problem.

Bad news is I'm beat for today.

**Comment by ztalbot2000** [comment]
hmmm,

   Could you change the timeout in your config.json to 20000.

Suddenly it worked for me afterwards.

ttfn,
John

**Comment by EugeneKallis** [comment]
I no longer get that message. Thank you!

**Comment by ztalbot2000** [comment]
Congrats!  What a lot of hassle for such a small solution.

Enjoy,,
John Talbot
