### ISSUE TITLE
Does not support carbonDioxideLevel of CarbonDioxideSensor?

### ISSUE THREAD

**Issue by Coro365** [ztalbot2000/homebridge-cmd4#25]
`CarbonDioxideDetected` works in my Home.app, but `carbonDioxideLevel` are not displayed.
Am I wrong?

![2019-06-05 23 35 47](https://user-images.githubusercontent.com/6727442/58965041-db214b00-87ea-11e9-85ad-2804ad05e439.png)

This is part of a config.txt.
```js
{
  "type": "CarbonDioxideSensor",
  "name": "CO2",
  "carbonDioxideDetected": 0,
  "carbonDioxideLevel": 0,
  "polling": false,
  "interval": 540,
  "stateChangeResponseTime": 3,
  "state_cmd": "ruby ~/.homebridge/cmd4.rb"
},
```

This is part of a ruby script.
```ruby
mode, acs_name, chara, value = ARGV
case acs_name
when "CO2"  
  field = "co2"
  ppm = current_value(field,location)
  case chara
  when "CarbonDioxideDetected"
    puts ppm > 1000 ? 1 : 0
  when "CarbonDioxideLevel"
    puts ppm
  end
  exit
```

Thank you for the great repository!

**Comment by ztalbot2000** [comment]
I'll have a look.

**Comment by ztalbot2000** [comment]
Hi,

  It is supported.  HomeBridge has it as an optional characteristic. I
would poll for it, as well as carbonDioxideDetected.
The latest version of cmd4 lets you poll for more than one characteristic.
See the default config file on how to do this. If you still have problems,
let me know.

TTFN,
John

**Comment by Coro365** [comment]
Thank you for your reply.
Succeeded using the latest version of node, homebridge and homebridge-cmd4.
I apologize to you for a fuss over.

![2019-06-07 15 51 38](https://user-images.githubusercontent.com/6727442/59086918-3879e100-893e-11e9-9977-e37387ab0470.png)

```
node: '6.16.0' => '10.16.0'
homebridge: '0.4.44' => '0.4.50'
homebridge-cmd4: '1.2.2' => '2.1.3'
```
Thank you for your polite support!

**Comment by ztalbot2000** [comment]
I'm glad it worked for you.  The latest designed is so much better and has
hundreds of unit tests that really killed a lot of possible sources of bugs.

Enjoy,
John Talbot
