### ISSUE TITLE
How to use the television?

### ISSUE THREAD

**Issue by Torac2** [ztalbot2000/homebridge-cmd4#26]
How do i use the television? I want to be able to switch inputs and turn it on and off with an command.

**Comment by ztalbot2000** [comment]
Good question!

   The characteristics are defined in
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/gen/
HomeKitTypes-Television.js

How you would put this into a script to control an actual TV, is beyond
me.There are other Homebridge modules that can be used to control specific
models. they could be combined with scripts, I assume. My Sony has this
capability, but IOS or Eve don't support it either.  putting it all
together would not be simple, but Cmd4 does now support the characteristics
for you to try.

ttfn,
John Talbot

**Comment by ztalbot2000** [comment]
Closed based on previous advice given.
