### ISSUE TITLE
CurrentPosition of WindowCovering is always 1% in the Home app

### ISSUE THREAD

**Issue by h8pewou** [ztalbot2000/homebridge-cmd4#27]
First of all, thanks for all the great work done so far! 

I'm using this plugin to control many different devices, including some shutters. Setting the shutters works fine, however the CurrentPosition value does not seem to be displayed correctly in the Home app. It looks fine in when the script is executed manually though:

```
/homebridge # sh /homebridge/Cmd4Scripts/franken.sh Set example_shutter TargetPosition 10
202
/homebridge # sh /homebridge/Cmd4Scripts/franken.sh Get example_shutter PositionState
2
/homebridge # sh /homebridge/Cmd4Scripts/franken.sh Get example_shutter CurrentPosition
10
```

The above example results in 1% shown in the app (instead of 10%).

![Screen Shot 2019-06-15 at 10 47 32 PM](https://user-images.githubusercontent.com/23012291/59556244-930ae100-8fbf-11e9-94ae-d7b0f65e2c0a.png)

**Comment by ztalbot2000** [comment]
I will have a look.  Can you make sure that homebridge-cmd4 is the latest.
Also send me your Franklin.sh script please.

Thanks,
John Talbot

**Comment by h8pewou** [comment]
Hello,

I’m on the latest. Here is the script (it’s not pretty):


#!/bin/sh

if [ "$1" = "Get" ]; then
   # $2 would be the name 'PS4'
   # $3 would be the charactersistic 'On'
   if [ "$3" = "PositionState" ]; then echo 2; exit 0; fi
   if [ "$3" = "CurrentPosition" ]; then
zipaposition=`node /homebridge/zipato_api/status.js $2`
echo "$(((zipaposition - 100) * -1))"
exit 0
   fi
   node /homebridge/zipato_api/status.js $2 | grep -q false
   rc=$?
   if [ "$rc" = "0" ]; then
echo "$rc"
exit 0
   else
echo "1"
exit 0
   fi
fi

if [ "$1" = "Set" ]; then
   # $2 would be the name 'PS4'
   # $3 would be the the charactersistic 'On'
   # $4 would be '0' for 'On' and '1' for 'Off'

if [ "$3" = "TargetPosition" ]; then
initialpos=$4
position="$(((initialpos - 100) * -1))"
node /homebridge/zipato_api/attribute.js $2 $position
exit $?
   fi
   if [ "$3" = "Brightness" ]; then
if [ "$4" != "0" ]; then node /homebridge/zipato_api/attribute.js $2 true; else node /homebridge/zipato_api/attribute.js $2 false; fi
exit $?
   fi
   if [ "$4" = "true" ]; then
node /homebridge/zipato_api/attribute.js $2 true
exit $?
   fi
   if [ "$4" = "false" ]; then
node /homebridge/zipato_api/attribute.js $2 false
exit $?
   fi
fi

exit -1

Thanks, Adam

**Comment by ztalbot2000** [comment]
Hi,

    I added to my config.json the following lines for WindowCovering

"polling": [{"currentPosition": "0",

                              "interval": 40,

                              "timeout": 4000

                             }],

My quick test with the home app and changing the stored value, did not
update the home up.  I tried it with the Eve app and it worked.
Can you try the Eve app. It is much better anyway.

I'm happy you are enjoying home bridge-cmd4

John Talbot

**Comment by ztalbot2000** [comment]
I did get it to update,  Here is my config.json

{

                 "type": "WindowCovering",

                 "name": "My_WindowCovering",

                 "targetPosition": 0,

                 "positionState": 2,

                 "holdPosition": 0,

                 "currentHorizontalTiltAngle": 0,

                 "targetHorizontalTiltAngle": 0,

                 "currentVerticalTiltAngle": 0,

                 "targetVerticalTiltAngle": 0,

                 "stateChangeResponseTime": 3,

                 "polling": [{"currentPosition": "0",

                              "interval": 40,

                              "timeout": 4000

                             },

                             {"obstructionDetected": "1",

                              "interval": 40,

                              "timeout": 4000

                             }],

                 "state_cmd": "node .homebridge/Cmd4Scripts/State.js"

              }

The stored value for the position is between 0 & 100.

Let me know how it goes.

John Talbot

**Comment by h8pewou** [comment]
The Home app shows the correct values until the first update is executed (same behavior as before the config.json update). The Eve app is better, there seem to be two values there, the first seem to be 0 or 1 and the second shows the actual position fairly reliably. 

Set to 0% in Home app shows up like this:

![IMG_0318](https://user-images.githubusercontent.com/23012291/59634615-7d2c2600-914f-11e9-8b55-c44a281cdd61.PNG)

Corresponding Eve values:

![IMG_0319](https://user-images.githubusercontent.com/23012291/59634673-9df47b80-914f-11e9-9cf0-638b93fecdd3.jpg)

One update later the Home app shows this:

![IMG_0317](https://user-images.githubusercontent.com/23012291/59634799-e01dbd00-914f-11e9-942d-e03881be5036.PNG)

Respective Eve values:

![IMG_0316](https://user-images.githubusercontent.com/23012291/59634827-f166c980-914f-11e9-8f62-964acfd6345c.jpg)

It is weird...

Thanks for the help so far!

**Comment by ztalbot2000** [comment]
I'm still not sure why the difference.  If you run in debug mode we can
check what values are being sent received. Try
DEBUG=* homebridge -D

Let me know if the values returned/sent are not what you expect.

Thanks,
John

**Comment by ztalbot2000** [comment]
closed for no return response and cannot duplicate.
