### ISSUE TITLE
How does it work in a Homebridge Docker Container

### ISSUE THREAD

**Issue by niveksan** [ztalbot2000/homebridge-cmd4#29]
I'm struggling with intallation of State.js
Did someone get this working in Homebridge running in a docker container?

**Comment by ztalbot2000** [comment]
I have not played with docker.  It should be installed just like any other
unix application.  The State.js file goes in a sub-directory of
.homebridge, called Cmd4Scripts.  You then can execute the State.js file as
indicated in the documentation.  My first question would be did you get
HomeBridge working in docker.

ttfn,
John Talbot
