### ISSUE TITLE
Trying to set up Kodi volume control.

### ISSUE THREAD

**Issue by zang74** [ztalbot2000/homebridge-cmd4#30]
I'm trying to set up the volume on my Kodi box as a virtual speaker (I use Kodi's built-in volume control on a dumb speaker system), but I'm having a hard time wrapping my head around how to go about it.

In my JSON, I have: 
```
{
	"platform": "Cmd4",
	"name": "Cmd4",
	"accessories": [
		{
			"type": "Speaker",
			"displayName": "Kodi",
			"mute": "0",
			"volume": 5,
			"name": "Kodi",
			"stateChangeResponseTime": 3,
			"state_cmd": "bash /var/lib/homebridge/scripts/kodivolume.sh"
		}
	]
},

```
and the kodivolume.sh script is as follows:

```
#!/usr/bin/env bash

if [ "$1" = "Get" ]; then
    if [ "$3" == "Volume" ] || [ "$3" == "Mute" ]; then
      	#get volume/muted info using curl
      	getinfo=$(curl -s -H 'Content-Type: application/json' -d '{"jsonrpc": "2.0", "method": "Application.GetProperties", "params": { "properties": [ "volume","muted" ] }, "id": 1 }' http://192.168.0.112:8080/jsonrpc )
		#parse the JSON for information
    	kodivolume=$(jq -r '.result.volume' <<<"$getinfo")
     	kodimuted=$(jq -r '.result.muted' <<<"$getinfo")
        if [ "$3" == "Volume" ]; then
        	echo "$kodivolume"
        	exit 0
        else
        	if [[ "$kodimuted" == "true" ]]; then
        		echo 1
        		exit 0
        	else
        		echo 0
        		exit 0
        	fi
        fi
    fi
fi

if [ "$1" = "Set" ] && [ "$3" == "Volume" ]; then
	#check if variable #4 exists, and that it is indeed a number (with optional percent sign)
 	if [ ! -z "$4" ] && [[ "$4" =~ ^[0-9]{1,2}%*$ ]]; then
 		json='{"jsonrpc":"2.0","method":"Application.SetVolume","params":{"volume":%s},"id":1}'
 		#filter out everything but the number
 		number=${4//[!0-9]}
 		#Join number to JSON string
 		jsonstring=$(printf "$json" "$number")
 		#Call JSON
 		curl -s -H 'Content-Type: application/json' -d $jsonstring http://192.168.0.112:8080/jsonrpc
 		exit 0
 	else
 		exit -1
        fi
  	echo 1
  	exit 0
fi
exit -1
```

If *feels* like this should work, but I'm new to homebridge.

[Edited to update with newer script, but it's still not working]

**Comment by ztalbot2000** [comment]
Hi,

   I just noticed your issue.  Start by running the script from the bash shell.  If you get that working, run:
DEBUG=* homebridge -D

It will show you what homebridge-cmd4 sends and receives.  

I have a Kodi box too. I ran your script from the command line.  It does not know what jq is.  You might need to specify the complete path to it. 

I also ran the CheckYourScript.sh and it said the same thing about jq.  Of course I'm running this on my Mac, but it is still a thought.

/usr/local/lib/node_modules/homebridge-cmd4/Extras/Cmd4Scripts/CheckYourScript.sh .homebridge/Cmd4Scripts/kodivolume.sh Get Kodi Volume

Let me know how you make out.  I'll close this, but continue to monitor your progress.

**Comment by zang74** [comment]
jq is a JSON parser, and I use it rather than just regex-ing the JSON results from Kodi. I do have jq installed on my system, and the script works fine from the command line. jq is in /usr/bin/, so I don't see it having an issue finding it.

Running the script
Is there more that needs to be in my config.json than what I have to support volume setting?

All a debug is showing for Cmd4 is:

```
[7/19/2019, 4:30:30 PM] [Cmd4] Doing Poll of index:75 characteristic:Mute for:Kodi timeout=4000 interval=5000
[7/19/2019, 4:30:30 PM] [Cmd4] getValue accTypeEnumIndex:(75)-'Mute' function for:Kodi cmd:bash /var/lib/homebridge/scripts/kodivolume.sh Get 'Kodi' 'Mute'
[7/19/2019, 4:30:30 PM] [Cmd4] getValue Mute function for:Kodi returned:0
[7/19/2019, 4:30:35 PM] [Cmd4] Doing Poll of index:75 characteristic:Mute for:Kodi timeout=4000 interval=5000
[7/19/2019, 4:30:35 PM] [Cmd4] getValue accTypeEnumIndex:(75)-'Mute' function for:Kodi cmd:bash /var/lib/homebridge/scripts/kodivolume.sh Get 'Kodi' 'Mute'
[7/19/2019, 4:30:35 PM] [Cmd4] getValue Mute function for:Kodi returned:0
```

I haven't set up any incrementation, just changing volume by value of 0-100. But the script works fine:

```
hoobs@hoobs:~ $ /var/lib/homebridge/scripts/kodivolume.sh Get 'Kodi' 'Mute'
0
hoobs@hoobs:~ $ /var/lib/homebridge/scripts/kodivolume.sh Get 'Kodi' 'Volume'
35
hoobs@hoobs:~ $ /var/lib/homebridge/scripts/kodivolume.sh Set 'Kodi' 'Volume' '45%'
{"id":1,"jsonrpc":"2.0","result":45}
hoobs@hoobs:~ $ /var/lib/homebridge/scripts/kodivolume.sh Get 'Kodi' 'Volume'
45
```

**Comment by ztalbot2000** [comment]
When you set the Volume from the command line, I see. You send '45%'.  I
know the result should be a number, without the percent sign.  Can you
check that your script is not returning the percent sign?

TTFN,
John

**Comment by zang74** [comment]
My script filters out the percent sign. “Set Kodi Volume 45%” achieves the same result as “Set Kodi Volume 45”. The percent sign isn’t sent to Kodi’s JSON-RPC.

**Comment by ztalbot2000** [comment]
Sorry, I really want to look at your script and set it up on my Pi with
Kodi, but I'm short for time at the moment.  Maybe later tonight.

ttfn,
John

**Comment by ztalbot2000** [comment]
Hi Zang,

  I had a few minutes.  I installed jq 1.6 on my Mac using home-brew.  I
used your config.json exactly except I put the path to kodivolume.sh in
.homebridge/Cmd4Scripts/
The Get and Set both work. Of course I only had to change the IP to my Kodi
box.   HomeKit does not recognize a Speaker, but Eve does.  Did you try
running Eve instead?
You can speed up your script by having the config.json file just say
.homebridge/Cmd4Scripts/kodivolume.sh
Then setting the kodivolume.sh to be executable.  This spawns one less
process.

As always, let me know how you fair out.

This is a nice script by the way.  I like it!



The config.json file I used was:

{

   "bridge":

   {

      "name": "MAC Test Homebridge",

      "username": "CC:22:3D:E3:CE:30",

      "port": 51826,

      "pin": "555-55-555"

   },

   "platforms" :

   [

      { "platform": "Cmd4",

        "name": "Cmd4",

        "accessories":

        [ {

            "type": "Speaker",

            "displayName": "Kodi",

            "mute": "FALSE",

            "volume": 5,

            "name": "Kodi",

            "stateChangeResponseTime": 3,

            "state_cmd": "bash .homebridge/Cmd4Scripts/kodivolume.sh"

          }

        ]

      }

   ]

}

**Comment by zang74** [comment]
Despite the preponderance of Apple products in our household, I’ve gone with Alexa as our voice gateway (Echo Dots were super cheap on Prime Day), primarily because I find the voice recognition much better. But the script doesn’t work with Alexa. 

As I’m relatively new to Homebridge and home automation in general, I’m wondering if there’s something I’m just not getting here. 

My assumption is that it’s like this:

I tell Alexa, “Set Kodi Volume 45%” and it passes that exactly onto the Cmd4 platform named “Kodi”. Cmd4 just tells Homebridge it’s a speaker so that it displays volume levels, etc., but will take any command words assigned to it and launch scripts tied to those words, no?

There isn’t some secret voodoo encantation that I need to be speaking, right?

**Comment by ztalbot2000** [comment]
Hi,

  I think we have gone into a different realm here.  If you try Eve, which
is just another IOS app, you will see your script works.  So now the tie
inn is just Alexa. Unfortunately, I do not know Alexa.  I have a Google
Home. I can see if that works and let you know.

What if you say to Alexa set the Kodi volume to 45?

I chose Google Home because it has better search capabilities. I find the
voice recognition excellent. It seems to get everyone's voice, without it
having to go through recognizing everyone first.

ttfn,
John

**Comment by ztalbot2000** [comment]
Hmm, Still poking.  I did find a homebridge-Alexa module.

**Comment by ztalbot2000** [comment]
Linking Google Home to HomeKit/HomeBridge seems to be just as nasty, but at
least Alexa seems possible.  Unfortunately I do not have an Alexa.  Even
worse, it seems Alexa makes you pay $17 dollars a month for AREK.
I do not know how much more I can help you, other than your script does
work.
There does seem to be a lot of incompatibility between the platforms of
Google, Alexa and Siri.  It does seem though that at least Alexa and
Homebridge should work. I just have no way of helping you.

If there is anything else I can do, let me know.

ttfn,
John

**Comment by zang74** [comment]
Yeah, I’m using the Homebridge-Alexa plugin as well. So far, it’s worked fine for switches using command2. It’s just Cmd4 that seems to be causing issues. Devices define the language required, right? And in this case if Cmd4 is acting as the device, I should be able to define what it uses, no? What I’m unsure about is what is whether the language of speakers needs to be something special. I’m working on an updated script, and doing some more research. So if I make more headways on either front, I’ll post back here. 

Jamie Nazaroff
zang@thetaoofzang.com

**Comment by ztalbot2000** [comment]
If you got cmdswitch2 going and I have proven your script with Eve, the
only thing I see is how Alexa is sending the number to Homebridge.  Did we
see from using Debug mode what was being sent when you use Alexa?

Ttfn,
John

**Comment by zang74** [comment]
Yeah, the problem was voice commands. I was trying too literal ("Set Kodi Volume 45", etc.), when I needed to go with a more natural language command ("Set the volume to 45 on Kodi"). The Alexa app doesn't show any characteristics on the device, but I am able to control the volume and mute.

That said, I'm experimenting with switching it's device type from a speaker to a television, so that I can access some of the media commands.

**Comment by ztalbot2000** [comment]
Hi Zang,
   Well, I'm glad you got things working.

   At the moment I'm trying to add http capabilities into Homebridge-Cmd4.
In this way, you would only need to define the properties in the
config.json file.  Your script was insightful as an example fo what would
be required.

take care,
John Talbot
