### ISSUE TITLE
SyntaxError at JSON.parse (<anonymous>) in github-version-checker

### ISSUE THREAD

**Issue by MichlW** [ztalbot2000/homebridge-cmd4#31]
SyntaxError: Unexpected token A in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.res.on (/usr/local/lib/node_modules/homebridge-cmd4/node_modules/github-version-checker/lib/check.js:64:21)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

When homebridge-cmd4 is installed in oznu/homebridge Docker Container i get the upper error message right after activating the first accessory. This happens nearly all the time, but in rare cases i managed to get it working, but i did not know why. My config.json is absolutely without errors.

That behavior was not the case in the past. I tried to use previous version 2.2.1 with rare success. I also tried to use newest Docker image of homebridge. Nothing helped. In the cases when it works a single restart sometimes is enough to break my installation by this error. Actually i spent hours to investigate with no success.

And finally i did not find any solution on Google.

Please help.

**Comment by MichlW** [comment]
Now i tried to install cmd4 by

`npm install -g git+https://github.com/ztalbot2000/homebridge-cmd4.git`

instead of npm with the same bad result.

**Comment by MichlW** [comment]
Without copying my existing content to config.json the problem is gone. I do not understand that, but i think i can close that ticket due to this "fix".

**Comment by ztalbot2000** [comment]
Usually HomeBridge spits out the message to try you config.json at:
https://jsonlint.com

json files can be tricky at times.  As specially one as big as the one for
Cmd4.  Try jsonlint, it gives a better idea of what is wrong.

ttfn,
John Talbot

**Comment by ztalbot2000** [comment]
GitHub-version-checker is still causing issues.  I removed it for a direct comparison of what is in npm.  New release is 2.2.5
