### ISSUE TITLE
How to use the TLV8 characteristics within Television accessory?

### ISSUE THREAD

**Issue by MichlW** [ztalbot2000/homebridge-cmd4#33]
Could someone please give me a hint how to use the TLV8 characteristics within the Television accessory? I have a Grundig TV with a single HDMI input from a Raspberry Pi running Kodi (passed through a denon receiver).

RasPi  --(HDMI)-->  Denon  --(HDMI)-->  TV

With this awesome homebridge plugin I have already implemented the following using only one Television accessory:
- Control the power state of my TV using HDMI CEC commands send from the Raspberry Pi
- Choose the audio input of my Denon receiver (Kodi or Apple AirPlay) using HTTP with curl
- Read out the actual input source of my Denon Receiver using HTTP with curl

Now I try to implement the functionality of the iOS built in Remote App to control my Kodi on Raspberry Pi for:
- currentMediaState and targetMediaState
- remoteKey PLAY, PAUSE, UP, DOWN, ...

My problem is, that I do not understand how to activate/enable the TLV8 options. What does the "... unless 'allowTLV8' is set, at your own peril." mean? I used it in config.json within my Television accessory but nothing happens.

I hope someone can point me in the right direction.

Thanks in advance.
Michael

**Comment by ztalbot2000** [comment]
Hi Micheal,

TLV8 is a structure of:
Type - 1 byte
Length - 1 byte
Value - variable the size of Length above.

There are lots of meanings to this.  At the time I did not delve further
into it.  Setting it without knowing what it consists of is why I seid set
at your own peril.

Have you found the HAP Spec? It does give these examples:

Byte 0: 0x06 (state)
Byte 1: 0x01 (1 byte value)
Byte 2: 0x03 (M3)
Byte 3: 0x01 (identifier)
Byte 4: 0x05 (5 byte value)
Byte 5: 0x68 (ASCII 'h')
Byte 6: 0x65 (ASCII 'e')
Byte 7: 0x6C (ASCII 'l')
Byte 8: 0x6C (ASCII 'l')
Byte 9: 0x6F (ASCII 'o')
Total:  10 bytes


Byte   0: 0x06 (state)
Byte   1: 0x01 (1 byte value)
Byte   2: 0x03 (M3)
Byte   3: 0x09 (certificate)
Byte   4: 0xFF (255 byte value)

Byte 5: 0x61 (ASCII 'a')

... 254 more bytes containing 0x61 (ASCII 'a') Byte 260: 0x09
(certificate...continuation of Byte 261: 0x2D (45 byte value)
Byte 262: 0x61 (ASCII 'a')
... 44 more bytes containing 0x61 (ASCII 'a') Byte 307: 0x01
(identifier...new TLV item) Byte 308: 0x05 (5 byte value)
Byte 309: 0x68 (ASCII 'h')
Byte 310: 0x65 (ASCII 'e')
Byte 311: 0x6C (ASCII 'l')
Byte 312: 0x6C (ASCII 'l')
Byte 313: 0x6F (ASCII 'o')
Total: 314 bytes


With this you can see why I say set at your own peril.  The Hap spec gives
much more information.  From a command line perspective, it is difficult to
set.

If I can help you further. let me know.
ttfn,
John Talbot

**Comment by ztalbot2000** [comment]
As per conversation
