### ISSUE TITLE
version check error causes homebridge instance to exit

### ISSUE THREAD

**Issue by huongminh** [ztalbot2000/homebridge-cmd4#35]
the plugin worked well for me until I restart homebridge and could not get it run again. Found this in the log:

SyntaxError: Unexpected token A in JSON at position 0 Oct 10 10:46:42 raspberrypi homebridge[27444]: at JSON.parse (<anonymous>:null:null) Oct 10 10:46:42 raspberrypi homebridge[27444]: at IncomingMessage.res.on (/var/homebridge/node_modules/homebridge-cmd4/node_modules/github-version-checker/lib/check.js:64:21)

I had to downgrade to version 2.1 and it works well

**Comment by ztalbot2000** [comment]
I found the issue in github-version-checker.  They fixed it in
github-version-checker 2.1.2.   For some reason, npm does not update the
github-version-checker package.  Try re-installing the latest CMD4. Doing
so should fix the problem.  Let me know how you make out.

John Talbot

**Comment by ztalbot2000** [comment]
I just pushed 2.2.4.   There are no code changes (2.2.3 pushed
incorrectly).  This will hopefully force a pickup of the latest
github-version-checker to fix the issue.

TTFN,
John Talbot

**Comment by huongminh** [comment]
Thank you for the quick fix. First I reinstall the plug in and still got the below error. Then, I tried to uninstall the plugin and reinstall it. And it works! Thank you for your great plugin. I am using it to mirror my Xiaomi fan (homekit fan v2) to the homebridge - google home which only support homekit fan v1.

--------------
SyntaxError: Unexpected token A in JSON at position 0
Oct 12 18:03:57 raspberrypi homebridge[31592]:     at JSON.parse (<anonymous>)
Oct 12 18:03:57 raspberrypi homebridge[31592]:     at IncomingMessage.res.on (/var/homebridge-extra/node_modules/github-version-checker/lib/check.js:64:21)
Oct 12 18:03:57 raspberrypi systemd[1]: homebridge-extra.service: Main process exited, code=exited, status=255/n/a
Oct 12 18:03:57 raspberrypi systemd[1]: homebridge-extra.service: Unit entered failed state.
Oct 12 18:03:57 raspberrypi systemd[1]: homebridge-extra.service: Failed with result 'exit-code'.

**Comment by ztalbot2000** [comment]
GitHub-version-checker is still causing issues.  I removed it for a direct comparison of what is in npm.  New release is 2.2.5
