### ISSUE TITLE
Television 

### ISSUE THREAD

**Issue by aecom** [ztalbot2000/homebridge-cmd4#37]
Hi trying to add tv to the plugin just  need  on, off , state , through url or curl 
Thanks

**Comment by ztalbot2000** [comment]
Hi,
  The purpose ofCMD4 is to run scripts.  In your case, have a look at the
PS4.sh and add your curl on command and your curl off command in the
appropriate places.

There are examples in the README and others issues that have been closed
with similar requests.

TTFN,
John Talbot

**Comment by aecom** [comment]
Hi thanks for replay
Could not Understand which line in the script is 
On —- it is curl command
Off —— it’s curl command
State —- ping command

Can you help
Thanks

Eliran Moshe®
sent from my iPhone Pr⭕️ Ma❌

**Comment by ztalbot2000** [comment]
Send me your two curl command, one for on and the other for off.

**Comment by aecom** [comment]
On.  http://192.168.1.9:8080/redeye/rooms/0/devices/126/commands/send?commandId=128

Off. http://192.168.1.9:8080/redeye/rooms/0/devices/126/commands/send?commandId=129
State. 192.168.1.45

Thanks 🙏 

Eliran Moshe®
sent from my iPhone Pr⭕️ Ma❌

> ‫ב-17 בנוב׳ 2019, בשעה 9:02, ‏‏John Talbot ‏<notifications@github.com> כתב/ה:‬
> 
> ﻿Send me your two curl command, one for on and the other for off.
>

**Comment by aecom** [comment]
I use it blaster for commands 
And IP adress of tv for state


Eliran Moshe®
sent from my iPhone Pr⭕️ Ma❌

> ‫ב-17 בנוב׳ 2019, בשעה 9:02, ‏‏John Talbot ‏<notifications@github.com> כתב/ה:‬
> 
> ﻿Send me your two curl command, one for on and the other for off.
>

**Comment by ztalbot2000** [comment]
the curl command should be more like this.

curl -s -H 'Content-Type: application/json' -d '{"jsonrpc": "2.0",
"method": "Application.GetProperties", "params": { "properties": [
"volume","muted" ] }, "id": 1 }' http://192.168.2.53:8080/jsonrpc

you need to send ne the exact curl statement as af you were doing it
yourself on the command line.

**Comment by aecom** [comment]
On.  http://192.168.1.9:8080/redeye/rooms/0/devices/126/commands/send?commandId=128

Off. http://192.168.1.9:8080/redeye/rooms/0/devices/126/commands/send?commandId=129

State. 192.168.1.45
Thanks

Eliran Moshe®
sent from my iPhone Pr⭕️ Ma❌

> ‫ב-17 בנוב׳ 2019, בשעה 9:34, ‏‏John Talbot ‏<notifications@github.com> כתב/ה:‬
> 
> ﻿the curl command should be more like this.
> 
> curl -s -H 'Content-Type: application/json' -d '{"jsonrpc": "2.0",
> "method": "Application.GetProperties", "params": { "properties": [
> "volume","muted" ] }, "id": 1 }' http://192.168.2.53:8080/jsonrpc
> 
> you need to send ne the exact curl statement as af you were doing it
> yourself on the command line.
> 
>

**Comment by ztalbot2000** [comment]
CMD4 only does shell commands.  You have to wrap the curl command into a script, such as PS4.sh.  I can only help you if you provide me with the curl command you would execute on the command line, not in a browser.  I suggest you google curl and go from there.

**Comment by aecom** [comment]
on_cmd": "curl  http://192.168.1.22:8080/redeye/rooms/0/devices/414/commands/send?commandId=531",
       "off_cmd": "curl http://192.168.1.22:8080/redeye/rooms/0/devices/414/commands/send?commandId=531",
       "state_cmd": "ping -c 2 -W 1 192.168.1.28 | grep -i '2 received'",





Eliran Moshe®
sent from my iPhone Pr⭕️ Ma❌

**Comment by ztalbot2000** [comment]
I'm surprised that works for you.  Send me the output of the curl command to get the state of the device.  I need to know what it is so it can be parsed.  
If you also send me the link to the product you are trying to control, I'll dig further.

**Comment by aecom** [comment]
Hi

There is no output it sends command to ir bluster that I have and that turn on my tv
The ping is for the tv ip so it sees if it is alive 
This way I turn on and the tells if it on or off as the on and off commands are the same 
It is not for one tv it is for few tvs I have from other brands that don’t have ability of a smart app 
And this way I can control everything when I am not at home 

Thanks

**Comment by aecom** [comment]
I think this can help for state but don’t know where to put it



Thanks 😊 
Eliran Moshe®
sent from my iPhone Pr⭕️ Ma❌

**Comment by ztalbot2000** [comment]
So I was thinking about this and I possibly know why you are having problems because I can't believe that you could not substitute those two curl commands into PS4.sh in the appropriate places.
The very first issue I ever faced in the HomeKit world was my incorrect concept of 'State'.  When tap on a device on any App to turn it on or off, the App does not remember the State it put it.  It always sends a Get to determine what State it is in.  So just providing an On or Off command is not enough.  While it will send the command, the fact that there is no State response the App will either show Off/On or Unavailable.

We can fix this in our PS4.sh to return the last known State, but it will out of Sync with the device if it were to be actually turned On/Off b normal methods.

I will create a script that will do this for you and get back to you later today.

You still may wish to try something like the original curl commands I suggested, because you may be actually surprised what you could get back from the device.  The one I had written asked for volume for instance. You also might be able to query what all commands it responds to.

TTFN,
John

**Comment by aecom** [comment]
Thanks !!!!!

Can’t you change the state to get it from ping command ??

Eliran Moshe®
sent from my iPhone Pr⭕️ Ma❌

**Comment by ztalbot2000** [comment]
Yes, I will.  It is already done somewhere, just got to find it in one of the other questions

**Comment by ztalbot2000** [comment]
I was correct, someone did ask for the same thing.  Issue #24 did the exact same. Have a look at it if you need to.
 The script is below anyway.
to run it from the command line do:
./PS4.sh Get PS4 On
or
./PS4.sh Set PS4 On 0
./PS4.sh Set PS4 On 1

Make sure it runs correctly before attempting it in CMD4.

The script does not check the name of the device, so you can use any name='xxxx' in your .config file.  both the README and issue #24 goes into details.

#!/bin/sh
if [ "$1" = "Get" ]; then
   # $2 would be the name 'PS4'
   # $3 would be the charactersistic 'On'
   ping -c 2 -W 1 192.168.1.22 | grep -i '2 packets received' >> /dev/null
   rc=$?
   if [ "$rc" = "0" ]; then
      echo "1"
      exit 0
   else
      echo "0"
      exit 0
   fi
fi

if [ "$1" = "Set" ]; then
   # $2 would be the name 'PS4'
   # $3 would be the the charactersistic 'On'
   # $4 would be '0' for 'On' and '1' for 'Off'
   if [ "$3" = "On" ]; then
      if [ "$4" = "true" ]; then
         # On command using Curl
         curl http://192.168.1.22:8080/redeye/rooms/0/devices/414/commands/send?commandId=531
         exit $?
      else
         # Off command using Curl
         curl http://192.168.1.22:8080/redeye/rooms/0/devices/414/commands/send?commandId=531
         exit $?
      fi
   fi
fi


exit -1




ttfn,
John

**Comment by aecom** [comment]
Hi thanks !!!

The commands works 😊😊
But the state is always off 
When I test the script it error on the -1 in the end 
Delete -1  
Still the same 

Any idea ?

Eliran Moshe®
sent from my iPhone Pr⭕️ Ma❌

**Comment by aecom** [comment]
Hi fixed it


if [ "$1" = "Get" ]; then
#$2 would be the name 'PS4'
#$3 would be the charactersistic 'On'
IP='192.168.1.28'
if ping -c 1 -w 1 $IP  > /dev/null;
then echo 1
else echo 0
exit 0
fi
fi

**Comment by aecom** [comment]
Hi can add volume control on the same way 
Curl commands ???

Thanks for all your help 

Eliran Moshe®
sent from my iPhone Pr⭕️ Ma❌

**Comment by ztalbot2000** [comment]
I'm glad you got it working.  For Volume just add another check where characteristic = "Volume"
Also add to your config.json file "volume": 0,

ttfn,
John Talbot

**Comment by aecom** [comment]
Hi can you 
Show me how ??

Thanks

Eliran Moshe®
sent from my iPhone Pr⭕️ Ma❌

**Comment by aecom** [comment]
Hi can you  send me the exact command I should add for volume  Please 

Thanks

Eliran Moshe®
sent from my iPhone Pr⭕️ Ma❌

**Comment by ztalbot2000** [comment]
Send me the curl commands.

**Comment by aecom** [comment]
http://192.168.1.22:8080/redeye/rooms/0/devices/414/commands/send?commandId=534

Vol up

http://192.168.1.22:8080/redeye/rooms/0/devices/414/commands/send
?commandId=535
Vol off




Eliran Moshe®
sent from my iPhone Pr⭕️ Ma❌

> ‫ב-18 בנוב׳ 2019, בשעה 22:54, ‏‏John Talbot ‏<notifications@github.com> כתב/ה:‬
> 
> ﻿Send me the curl commands.
> 
> Sent from Zarf’s iPad Air 2
>

**Comment by aecom** [comment]
Vol up
Curl http://192.168.1.22:8080/redeye/rooms/0/devices/414/commands/send?commandId=534

Vil down
Curl http://192.168.1.22:8080/redeye/rooms/0/devices/414/commands/send?commandId=535

Thanks 😊 

Eliran Moshe®
sent from my iPhone Pr⭕️ Ma❌

> ‫ב-18 בנוב׳ 2019, בשעה 22:54, ‏‏John Talbot ‏<notifications@github.com> כתב/ה:‬
> 
> ﻿Send me the curl commands.
> 
> Sent from Zarf’s iPad Air 2
>

**Comment by ztalbot2000** [comment]
Hi,

  we are getting into territory I have not tried.  you sent me volume up and down.  HomeKit supports it, but I've only tried absolute values.

your config.json is going to have
{
   "type": "Television",
   "volumeControlType": 1,
   "volumeSelector": 0,
...
}
I'm assuming the VolumeControlType of 1 means up and down.  I don't know if the fact that you have no Get for volume that it will work.

See how the script has changed so that if you need further changes you can do it yourself.

#!/bin/sh
if [ "$1" = "Get" ]; then
   # $2 would be the name 'PS4'
   # $3 would be the charactersistic 'On'
   if [ "$3" = "On" ]; then
      ping -c 2 -W 1 192.168.1.28 | grep -i '2 packets received' >> /dev/null
      rc=$?
      if [ "$rc" = "0" ]; then
         echo "1"
         exit 0
      else
         echo "0"
         exit 0
      fi
   fi
   if [ "$3" = "VolumeControlType" ]; then
      # 0 is for NONE
      # 1 is for RELATIVE
      # 2 is for RELATIVE_WITH_CURRENT
      # 3 is for ABSOLUTE
      echo "1"
      exit 0
   fi
fi

if [ "$1" = "Set" ]; then
   # $2 would be the name 'PS4'
   # $3 would be the the charactersistic 'On'
   # $4 would be '0' for 'On' and '1' for 'Off'
   if [ "$3" = "On" ]; then
      if [ "$4" = "true" ]; then
         # On command using Curl
         curl http://192.168.1.22:8080/redeye/rooms/0/devices/414/commands/send?commandId=128
         exit $?
      else
         # Off command using Curl
         curl http://192.168.1.22:8080/redeye/rooms/0/devices/414/commands/send?commandId=129
         exit $?
      fi
   fi
   if [ "$3" = "VolumeSelector" ]; then
      if [ "$4" = "0" ]; then
         # INCREMENT
         curl http://192.168.1.22:8080/redeye/rooms/0/devices/414/commands/send?commandId=534
         exit $?
      else
         # DECREMENT
         curl http://192.168.1.22:8080/redeye/rooms/0/devices/414/commands/send?commandId=535
         exit $?
      fi
   fi
fi


exit -1





   
}

**Comment by ztalbot2000** [comment]
I just realized that when you change it to Television, the config.json changes for "on" to "active".  this means the shell script I sent you "On" must also change to "Active".   you can see all the parameters for a Television in the default config.json file. Both "on" and "active" send 0 or 1 for on/off.  no changes there.
