### ISSUE TITLE
Homebridge show CoAP Server no cached entry found

### ISSUE THREAD

**Issue by veroled** [ztalbot2000/homebridge-cmd4#38]
CoAP Server no cached entry found

**Comment by veroled** [comment]
Did some have this same problem??

how to solve it?


CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:15 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:15 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:17 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:17 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:22 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:22 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:30 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:30 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:30 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:30 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:32 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:32 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:37 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:37 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:45 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:45 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:45 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:45 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:46 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:46 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:46 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:46 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:46 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:46 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:46 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:46 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:46 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:46 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:47 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:47 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:24:52 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:24:52 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:00 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:00 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:01 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:01 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:01 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:01 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:01 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:01 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:01 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:01 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:01 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:01 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:01 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:01 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:02 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:02 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:07 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:07 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:07 raspberrypi homebridge[7893]: [2019-11-19 22:25:07] [LED Pensile] LED Pensile  - Power from State ON
Nov 19 22:25:08 raspberrypi homebridge[7893]: [2019-11-19 22:25:08] [Caffe] Caffe  - Power from State OFF
Nov 19 22:25:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:17 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:17 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:22 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:22 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:32 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:32 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:37 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:37 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:46 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:46 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:46 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:46 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:46 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:46 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:46 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:46 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:46 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:46 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:46 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:46 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:46 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:46 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:47 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:47 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:25:52 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:25:52 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:01 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:01 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:01 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:01 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:01 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:01 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:01 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:01 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:01 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:01 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:01 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:01 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:01 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:01 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:02 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:02 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:06 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:06 GMT EventedHTTPServer [::ffff:192.168.1.158] Sending HTTP event 'keepalive' with data: {"characteristics":[]}
Nov 19 22:26:07 raspberrypi homebridge[7893]: [2019-11-19 22:26:07] [LED Pensile] LED Pensile  - Power from State ON
Nov 19 22:26:08 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:08 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:08 raspberrypi homebridge[7893]: [2019-11-19 22:26:08] [Caffe] Caffe  - Power from State OFF
Nov 19 22:26:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:17 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:17 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:23 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:23 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:32 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:32 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:38 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:38 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:46 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:46 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:46 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:46 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:46 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:46 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:46 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:46 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:46 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:46 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:46 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:46 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:46 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:46 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:47 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:47 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:26:53 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:26:53 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:01 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:01 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:01 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:01 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:01 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:01 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:01 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:01 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:01 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:01 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:01 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:01 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:01 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:01 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:02 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:02 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:07 raspberrypi homebridge[7893]: [2019-11-19 22:27:07] [LED Pensile] LED Pensile  - Power from State ON
Nov 19 22:27:08 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:08 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:08 raspberrypi homebridge[7893]: [2019-11-19 22:27:08] [Caffe] Caffe  - Power from State OFF
Nov 19 22:27:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:16 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:16 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:17 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:17 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:23 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:23 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:31 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:31 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:32 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:32 GMT CoAP Server no cached entry found, emit request to upper layer
Nov 19 22:27:38 raspberrypi homebridge[7893]: Tue, 19 Nov 2019 21:27:38 GMT CoAP Server no cached entry found, emit request to upper layer

**Comment by ztalbot2000** [comment]
Are you using homebridge-cmd4?  I've never seen this error message.  have you changed anything from the defaults? if so you will need to send me your config.json file and any scripts you have.
I'll close this for now, but continue to follow your issue as so far I see nothing that is cmd4 related.

**Comment by ztalbot2000** [comment]
I googled the message.  It is not specifically part of homebridge, but of the http protocol used by homebridge.  Could you please send me what model Pi you are running on, the distro your running on and its release. If the distro is not up to date you will have to send me the exact versions of node, python ...  
if you have changed any part of cmd4, ill need those as well to try and reproduce it.
if your worried it is to low of an event for me to figure out, then let me alleviate them by saying that the first thing the ping command does is send out an arp request for the Mac address of the IP address given and even lower where the ethernet devices bit that a packet is ready to send has been set.
