### ISSUE TITLE
On/Off action

### ISSUE THREAD

**Issue by Tommrodrigues** [ztalbot2000/homebridge-cmd4#4]
Hi there!

I really appreciate the work you've put into this plugin as it's made adding different types of accessories far easier and customisable. However, I'm having one slight problem which I'm hoping you could help me out with. I've managed to add a number of accessories to my home app which is great but where in the config.json file I've put both an `"on_cmd": "<executable>"` and an `"off_cmd": "<executable>"` with `<executable>` being the command I wish the accessory to carry out but so far this does nothing. Despite the fact that when I click the accessory in the app and it correctly changes state to show either on or off, it does not actually carry out the respective command. 
I apologise if the solution is glaringly obvious but would really appreciate it if someone could point me in the right direction to have the accessory actually carry out a command.

Thank you in advance,
Tom

**Comment by ztalbot2000** [comment]
Hi Tom,

   HomeBridge-cmd4 executes whatever script you define in the state_cmd.  There is only ONE script per accessory name as defined in your .homebridge/config.json file.  Options are passed to the script as arguments, this being On or Off for a light.  Examples are in the State.js file. 

In the other plugin (HomeBridge-cmd) there were two different scripts, one for on_cmd and another for off_cmd.  This does not make sense with HomeBridge-cmd4 as there are at least a hundred possible options that are possible as the devices get more complex.
So just create one script for each accessory and then pay attention to its receiving ARGC,ARGV.

Thanks for using home bridge-cmd4
John

**Comment by Tommrodrigues** [comment]
Hi John thanks for your reply,

I've had a fiddle around with what you said and I still can't seem to get it to work. I apologise once again if this is obvious however I'd really appreciate if you could walk me through how I'd get a command to be run when the accessory is controlled. I tried looking through the State.js file but I'm not great with code and wasn't able to find one. I understand that cmd4 dosnt allow for On and Off scripts but rather one for both and that's fine for what I need but I still don't quite understand whether you mean I'd need to integrate the command into the State.js file itself or make a new one. 

Thanks once again,
Tom
