### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by baseship** [ztalbot2000/homebridge-cmd4#40]
Hi, i'm trying to install this plugin under raspbian buster & homebridge installation guide from smartapfel.de
i cannot install the state.js
<img width="810" alt="Bildschirmfoto 2019-12-23 um 15 28 45" src="https://user-images.githubusercontent.com/11758521/71363303-fbeb9b00-2598-11ea-8160-26e00d7336a9.png">

**Comment by ztalbot2000** [comment]
Something is funny with either npm or github.  There never was a homebridge-cmd.  It is homebridge-cmd4

Try it instead and let me know how you make out

**Comment by ztalbot2000** [comment]
I think you have mixed up different repositories.  There is one called homebridge-cmd.  I can't explain your log as one does not use the other.  Your log clearly says you typed homebridge-cmd while the log says homebridge-cmd4.  Which one were you trying to do?

**Comment by ztalbot2000** [comment]
Closed for now, but I'm here if you need me

**Comment by baseship** [comment]
Thank you, i found the issue:
node_modules is installed in /usr/local/lib
