### ISSUE TITLE
Fan Accessory Question

### ISSUE THREAD

**Issue by mitch7391** [ztalbot2000/homebridge-cmd4#41]
Hi, I was wondering if any of the fan accessories in cmd4 accommodate a fan that has speeds low, medium high and auto? I have not been able to find out whether Homekit itself allows this, so no doubt it is a limitation of Homekit if anything :) If so can you show me how the config would differ from the example already in your sample config? Thanks in advance :)

**Comment by ztalbot2000** [comment]
Hi ,

  No the fan speed is only 0-100.  The spec does not allow you to change
it. At best you might be able to fake it. I'm not sure it would work. As
you increase the speed, instead of returning what was set, you could return
either 33, 66, 100.

Merry Christmas,
John Talbot.

**Comment by mitch7391** [comment]
Thanks John, I’ll have a think about a work around :) merry Christmas and happy new year!
