### ISSUE TITLE
Telnet also?

### ISSUE THREAD

**Issue by houser42** [ztalbot2000/homebridge-cmd4#42]
Will this plugin work with telnet commands? Many thanks!

**Comment by ztalbot2000** [comment]
It will run anything that you can put on a command line or in a script.

The device type must exist in HomeKit, but as a switch device type,
anything can be turned on or off.

Happy New Year
John Talbot

**Comment by houser42** [comment]
Many thanks. I will give it a go then..

**Comment by ztalbot2000** [comment]
I hope you did okay.  Closed for previous response.
