### ISSUE TITLE
hi thermostat q

### ISSUE THREAD

**Issue by aecom** [ztalbot2000/homebridge-cmd4#43]
is there way for cmd4 to have thermostat accessory that has only 3 func  heat cold off  on http  post commands ?

thanks

**Comment by ztalbot2000** [comment]
Hmmm,
   If you set the requested temperature to max and the current temp to
less, Eve will say Heating. in reverse it would say cooling, though the
exact temperature would be incorrect.  active would be set to ON.  That
gets you three states..
Your shell script would have to use curl for http.  There are one or two
examples of this in others issues that you may get ideas from

TTFN,
John

**Comment by aecom** [comment]
Hi thanks
Can I get exemplar of script
Thanks 🙏 

Eliran Moshe®
sent from my iPhone Pr⭕️ Ma❌

> ‫ב-10 בינו׳ 2020, בשעה 23:21, ‏‏John Talbot ‏<notifications@github.com> כתב/ה:‬
> 
> ﻿Hmmm,
> If you set the requested temperature to max and the current temp to
> less, Eve will say Heating. in reverse it would say cooling, though the
> exact temperature would be incorrect. active would be set to ON. That
> gets you three states..
> Your shell script would have to use curl for http. There are one or two
> examples of this in others issues that you may get ideas from
> 
> TTFN,
> John
>

**Comment by ztalbot2000** [comment]
This was someone else's Curl example.  modify it as you so wish.  I think
the paste may have caused funny formatting.  sorry about that.

#!/bin/sh
if [ "$1" = "Get" ]; then
   # $2 would be the name 'PS4'
   # $3 would be the charactersistic 'On'
   ping -c 2 -W 1 192.168.1.22 | grep -i '2 packets received' >> /dev/null
   rc=$?
   if [ "$rc" = "0" ]; then
      echo "1"
      exit 0
   else
      echo "0"
      exit 0
   fi
fi

if [ "$1" = "Set" ]; then
   # $2 would be the name 'PS4'
   # $3 would be the the charactersistic 'On'
   # $4 would be '0' for 'On' and '1' for 'Off'
   if [ "$3" = "On" ]; then
      if [ "$4" = "true" ]; then
         # On command using Curl
         curl
http://192.168.1.22:8080/redeye/rooms/0/devices/414/commands/send?commandId=531
         exit $?
      else
         # Off command using Curl
         curl
http://192.168.1.22:8080/redeye/rooms/0/devices/414/commands/send?commandId=531
         exit $?
      fi
   fi
fi


exit -1

**Comment by aecom** [comment]
Hi thanks but there is only 2 commands here I need 3 cool heat off

Eliran Moshe®
sent from my iPhone Pr⭕️ Ma❌

> ‫ב-11 בינו׳ 2020, בשעה 8:45, ‏‏John Talbot ‏<notifications@github.com> כתב/ה:‬
> 
> ﻿This was someone else's Curl example. modify it as you so wish. I think
> the paste may have caused funny formatting. sorry about that.
> 
> #!/bin/sh
> if [ "$1" = "Get" ]; then
> # $2 would be the name 'PS4'
> # $3 would be the charactersistic 'On'
> ping -c 2 -W 1 192.168.1.22 | grep -i '2 packets received' >> /dev/null
> rc=$?
> if [ "$rc" = "0" ]; then
> echo "1"
> exit 0
> else
> echo "0"
> exit 0
> fi
> fi
> 
> if [ "$1" = "Set" ]; then
> # $2 would be the name 'PS4'
> # $3 would be the the charactersistic 'On'
> # $4 would be '0' for 'On' and '1' for 'Off'
> if [ "$3" = "On" ]; then
> if [ "$4" = "true" ]; then
> # On command using Curl
> curl
> http://192.168.1.22:8080/redeye/rooms/0/devices/414/commands/send?commandId=531
> exit $?
> else
> # Off command using Curl
> curl
> http://192.168.1.22:8080/redeye/rooms/0/devices/414/commands/send?commandId=531
> exit $?
> fi
> fi
> fi
> 
> 
> exit -1
> 
>

**Comment by ztalbot2000** [comment]
What is there is an example of a curl command.  Specifically for on and
off.
The big State.js file has every possible command and option, as well as an
explanation of their meaning.  you will have to piece together the ones I
previously mentioned.  There is also an unmagnified config.json file which
is heavily commented to match the State.js file.

have fun,
John

**Comment by ztalbot2000** [comment]
How are you making out?

   The process might seem overwhelming, but forget about CMD4.  Create a
curl command that sets your thermostat to cooling and another to heating
and on.  If you get this, then add it to CMD4.   If you are still stuck,
send me a link to the thermostat you have and I will see what I can do..

ttfn,
John Talbot

**Comment by aecom** [comment]
Can’t seem to make it work
Cool http://192.168.1.22:8080/redeye/rooms/0/devices/414/commands/send?commandId=531

Heat http://192.168.1.22:8080/redeye/rooms/0/devices/414/commands/send?commandId=532

Off http://192.168.1.22:8080/redeye/rooms/0/devices/414/commands/send?commandId=533

Thanks

Eliran Moshe®
sent from my iPhone Pr⭕️ Ma❌

> ‫ב-12 בינו׳ 2020, בשעה 23:39, ‏‏John Talbot ‏<notifications@github.com> כתב/ה:‬
> 
> ﻿How are you making out?
> 
> The process might seem overwhelming, but forget about CMD4. Create a
> curl command that sets your thermostat to cooling and another to heating
> and on. If you get this, then add it to CMD4. If you are still stuck,
> send me a link to the thermostat you have and I will see what I can do..
> 
> ttfn,
> John Talbot
>

**Comment by ztalbot2000** [comment]
Can you send me the link to your thermostat product.  I'll have a look at
what it can do and how to talk to it.

TTFN,
John

**Comment by aecom** [comment]
Hi 
It is ir blaster thet sends the command.....

Eliran Moshe®
sent from my iPhone Pr⭕️ Ma❌

> ‫ב-13 בינו׳ 2020, בשעה 7:23, ‏‏John Talbot ‏<notifications@github.com> כתב/ה:‬
> 
> ﻿Can you send me the link to your thermostat product. I'll have a look at
> what it can do and how to talk to it.
> 
> TTFN,
> John
>

**Comment by ztalbot2000** [comment]
There are many types of IR blasters, Sony has one, So does Samsung as well
as many programmable remote controls.  Even my car key fob has one.  I need
a link to exactly which product.

Thanks,
John
