### ISSUE TITLE
Window cover still open

### ISSUE THREAD

**Issue by rLaLe** [ztalbot2000/homebridge-cmd4#44]
Hi!

First of all, thanks for your tool.
I have a small issue. I set up two window covers but if the cover is closed or open the homekit still highlight the ikon and notify my that 2 blind are open.
Please help me...

<img width="368" alt="Screenshot 2020-01-12 at 19 14 41" src="https://user-images.githubusercontent.com/47868281/72223505-d76b5900-356f-11ea-86bb-32600771eb3a.png">

**Comment by ztalbot2000** [comment]
I have a quick thought.  I remember someone else seing similar things with
multiple devices of the same type and I really thought we solved this.  Try
adding an element for each similar device entry as:
"UUID": "SomeUniqueNumber",
for example:

{
   "type": "WindowCovering",
   "displayName": "DiningCovering",
  "name": "DiningCovering",
  "UUID": 12345,
  ...
},
{
   "type": "WindowCovering",
  "displayName": "KitchenCovering",
  "name": "KitchenCovering",
  "UUID": 54321,
   ...
} ....


Let me know how it goes.

ttfn,
John Talbot

**Comment by rLaLe** [comment]
Unfortunatelly it didn't help. But if I remove the "obstructionDetected" parameter from config, it helps.
Thanks for you answer.
