### ISSUE TITLE
NPM readme contains inaccurate instructions

### ISSUE THREAD

**Issue by NewsGuyTor** [ztalbot2000/homebridge-cmd4#45]
Just wanted to let you know that the NPM readme contains old instructions, I was halfway through it when I discovered that it was referring to an old version titled homebridge-cmd.

https://www.npmjs.com/package/homebridge-cmd4

**Comment by NewsGuyTor** [comment]
Nevermind, the issue was that the instructions were incorrect for me, my folder location is /usr/local/lib/node_modules/homebridge-cmd4/ (not /usr/lib/node_modules/homebridge-cmd4)

**Comment by NewsGuyTor** [comment]
BTW, the copy config.json step is kind of stupid, as it overwrites the previous Homebridge configuration without any warning. 

Thankfully Homebridge makes frequent config.json backups, but I shouldn't have to restore my config just after following the installation steps while tired.

**Comment by ztalbot2000** [comment]
Thanks for the tip.  I'll have a look.

TTFN,
John
