### ISSUE TITLE
Motion Sensor notification

### ISSUE THREAD

**Issue by Catta1997** [ztalbot2000/homebridge-cmd4#47]
Hi, I added some motion sensors and enable notifications for them. They work if the Home app is open, because when I open the app all the sensors are updated. How can I automatically update the added motion sensor with cmd4 in the background so that I always receive notifications?

**Comment by ztalbot2000** [comment]
Hi,

   It's amazing in these times people are finding different things to do.
I can go months without a question and then suddenly I have a few.

Polling is how Cmd4 sends out status updates of sensor data.  If the App is
not open though, it will not be updated. At least that is the way Apple has
there's.  I personally like Eve better.  I don't know if it has background
fetch.

Take care and stay safe,

John
