### ISSUE TITLE
Thermostat/HeaterCooler without cooling function

### ISSUE THREAD

**Issue by MervinDelfin** [ztalbot2000/homebridge-cmd4#49]
Hi, can I have Thermostat that only supports heating. Can I disable the cooling mode and hide it in the home app?
I have seen HomeKit devices that have only heating mode in home app.

**Comment by ztalbot2000** [comment]
I understand what your looking for, but I seem to be drawing a blank. A private company can register their product with apple (UUID0. That would mean they could define their own service and its characteristics.  These are the generic ones given by Apple. you might have to put up with an unusable switch.  sometimes Eve is more flexible.  you can try that too.

**Comment by MervinDelfin** [comment]
Hi, I'm still playing with the Thermostat and based on apple's [documentation](https://developer.apple.com/documentation/homekit/hmcharacteristictypecurrentheatingcooling) there should be an "AUTO" option for "[currentHeatingCoolingState](https://github.com/ztalbot2000/homebridge-cmd4/blob/b5b08866bf0e75c120303065d342ee14d7b9b5d6/Extras/config.min.json#L370)".

**Comment by ztalbot2000** [comment]
Hi Mervin,

  it is listed

> 136: { type: "TargetHeaterCoolerState",
>
>              characteristic: Characteristic.TargetHeaterCoolerState,
>
>              props: {format: Characteristic.Formats.UINT8,
>
>                      maxValue: 2,
>
>                      minValue: 0,
>
>                      perms: [Characteristic.Perms.READ,
>
>                              Characteristic.Perms.WRITE,
>
>                              Characteristic.Perms.NOTIFY
>
>                             ]
>
>                     },
>
>              validValues:
>
>                 {"AUTO": Characteristic.TargetHeaterCoolerState.AUTO,
>
>                  "HEAT": Characteristic.TargetHeaterCoolerState.HEAT,
>
>                  "COOL": Characteristic.TargetHeaterCoolerState.COOL
>
>                 }
>
>
>

**Comment by MervinDelfin** [comment]
I'm talking about Thermostat not HeaterCooler. Where did you get such explanation of "TargetHeaterCoolerState"? I don't see it in your repo.

**Comment by ztalbot2000** [comment]
the index.js file has all those that are possible,

**Comment by MervinDelfin** [comment]
ok, found where the explanation was.
I was talking about this:

https://github.com/ztalbot2000/homebridge-cmd4/blob/b5b08866bf0e75c120303065d342ee14d7b9b5d6/index.js#L694-L721

**Comment by ztalbot2000** [comment]
it is another way of looking at
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js

**Comment by ztalbot2000** [comment]
It describes those in Accessories.js, in the same director.

**Comment by MervinDelfin** [comment]
Does this mean that there is a mistake in homebridge ?

**Comment by ztalbot2000** [comment]
The one you sent me is mine. Mine pulls together what is in Homebridge, the
Characteristcs and Accessory.js file paths that I sent you, just in a way
that ties them together to be searchable.

Neither are wrong.

TTFN,
John

**Comment by MervinDelfin** [comment]
So why there an "auto" value in apple's [documentation](https://developer.apple.com/documentation/homekit/hmcharacteristicvalueheatingcooling) that isn't present in homebridge?

**Comment by ztalbot2000** [comment]
So there has been a lot done to homebridge and HAP-NodeJS since I last
looked at this. Mainly the change to Typescript.  In HomeKit.ts on
line 4809 you will see that the validValues are 0,1,2.  No Auto.  The
developer documentation for HMCharacteristicTypeCurrentHeatingCooling does
have values HMCharacteristicValueHeatingCooling that includes Auto. So you
are correct. I do believe there is a problem with HAP-NodeJS.
I can understand how this happened as the original HomeKit documentation
was not available to anyone.
I can add this, but I do not know how Homebridge will handle this.  You
should put a ticket in with them as well.

**Comment by MervinDelfin** [comment]
ok, I will create an issue on the homebridge project.

**Comment by MervinDelfin** [comment]
https://github.com/homebridge/HAP-NodeJS/issues/815#issuecomment-619046396

So I guess it is correct after all.

**Comment by ztalbot2000** [comment]
I disagree.  You are correct.  The spec on the page you sent is correct and
it does make sense.  The state of Auto is for both Target and Current
State.  I'll put a comment in the Hap-Spec as well and see if we can battle
it out..

**Comment by ztalbot2000** [comment]
Hi,

  I don't know if HAP will fix their stuff or not. As for yours though, if
you want to set the current target to Auto in Homebridge-cmd4 you can do
that right now by setting it to 3.  It will not understand the string
'AUTO', but it means the same thing. Both CMD4 and HAP do not care about
this.  HomeKit, Eve and Config-UI-X will show 'AUTo' for the value of 3.

I hope this helps and sorry for all the hassle.  I'll get an update in soon
for the string value.

TTFN,
John Talbot
