### ISSUE TITLE
Command

### ISSUE THREAD

**Issue by davidhonly** [ztalbot2000/homebridge-cmd4#5]
Hey please could you point me in the right direction of how to add a command that would be performed when an accessory is controlled as I can't see anything about it in your README.
Thanks for your help, David

**Comment by ztalbot2000** [comment]
Hi David,

  HomeBridge-Cnd4 comes with everything you need.  There is is fully
populated config.json in the Extras subdirectory and a fully populated
State.js file in the Extras/Cmd4Scripts directory.  You could use these as
is or cut and paste arts of either into your own .homebridge/config.json
file.  If you have never used home bridge before, I would suggest starting
there and then modify them as needed.

ttfn,
John Talbot

**Comment by ztalbot2000** [comment]
Talk about typos
HomeBridge-Cmd4 comes with everything you need.  There is is fully
populated config.json in the Extras subdirectory and a fully populated
State.js file in the Extras/Cmd4Scripts directory.  You could use these as
is or cut and paste parts of either into your own .homebridge/config.json
file.  If you have never used home bridge before, I would suggest starting
there and then modify them as needed.

**Comment by davidhonly** [comment]
Thank you for your quick reply! I'm fairly new to homebridge and am not an expert on coding. On other CMD plugins it seems you just put the On/Off commands under the relevant names in the config.json file but I've tried this with CMD4 and it doesn't seem to work. I have also tried replacing the "state_cmd" which usually calls node .homebridge/Cmd4Scripts/State.js with my command but this causes errors. Am I right in believing that it is necessary to keep the State.js file for the plugin to work properly? If so, then where would I need to input my command for this to work? Would it need to go in the config.json file or in the State.js file? If it goes into the State.js file please could you explain how I would implement this as I'm not too familiar with the "programming language" that the State.js file uses.
Thank you very much for your work and your help, I really appreciate it.
David

**Comment by ztalbot2000** [comment]
Hi David,

  The problem with Homebridge-Cmd was that it did not support other
options,  so while an on or off command is simple, it is not practical to
have a command for every option.  So there is just one command and that
command is passed arguments of what is to be done.  The State.js file has
all possible combinations.

The State.js file could be any other executable file.  For example
"DoIt.sh"..  instead of the reference to State.js in the
homebridge/config.json file.  The DoIt.sh file would be passed the same
arguments that the State.js file would receive, just parsed differently
according to shell syntax.

So whatever script you call in the config.json file, ie State.js or
DoIt.sh, make sure it is executable.  The one thing that is nice about a
single script file, it is easy to test in a terminal window.  I.e. node
State.js MyLamp ON

It looks like you are going to have fun understanding arguments to
scripts.  Have a look at the State.js file.  It will tell you a lot.

Take care,
John

**Comment by davidhonly** [comment]
Thanks once again for your reply,

I have created an executable script called "Dotty.sh" with the simple script inside:
`#!/bin/bash`
`open -a iTunes`

My config file is now configured like this:
<img width="462" alt="screen shot 2018-03-26 at 19 56 31" src="https://user-images.githubusercontent.com/37807951/37923654-f5766dea-312f-11e8-8854-c90cb17ee059.png">

However, when I even open the Home app I receive the following error in terminal:
<img width="571" alt="screen shot 2018-03-26 at 19 53 39" src="https://user-images.githubusercontent.com/37807951/37923696-14503ac0-3130-11e8-9c8e-3a66f6f52204.png">

I assume this is to do with the fact that there is no "State" data inside the file. I apologise as this is about the extent of my programming knowledge.
My question is; how exactly would I include the executable whilst retaining the standard behaviour of the accessory with the executable only being executed when the state of the accessory is changed.

Quick note: Whilst the terminal does show this error, the executable is carried out when I open the app but this is unprompted and does not allow for direct execution when I attempt to change the state within the app afterwards which is not desired.

Thank you once again,
Kind regards, David

**Comment by ztalbot2000** [comment]
Hi David,

  My first thought without even digging deep is that your config.json file
has the command as ~/Dolly.sh.  The problem is that the Tilda character is
only expanded by your shell.  So Dolly.sh will never be found.   if
Dolly.sh is in your home directory then use use "Dolly.sh" or to be sure
the exact path as in "/Users/zarf/Dolly.sh".

I hope this helps.
John

**Comment by ztalbot2000** [comment]
Hi,

  A Get command expects a return value from your script to be written to
stdout.  Try:: node State.js Get My_GarageDoorOpener CurrentDoorState
and you will see what I mean.  Your script would have to accept the same
parameters and respond accordingly.

  A Set by the way also does a Get afterwards to check if it is done.

Also look into homebridge debugging.  You can start the server in debug
mode and then you will see the exact commands homebridge-cmd4 is sending,
which you can try on the command line.  Basically they are what is in the
State.js file.

ttfn,
John

**Comment by ztalbot2000** [comment]
hi David,

  Since you are new to homebridge have you tried homebridge-cmd4 by itself,
because there is everything you need inttt cake to get what is on the
screenshot.

ttfn,
John

**Comment by davidhonly** [comment]
Hi John,

What you said about the Get and Set commands makes sense but I don't think I am proficient enough in code to get that to work on my own. I've also just had a go at running homebridge in debugging mode but I'm not really sure what im meant to do with the information. I've included a screenshot incase you're interested:
<img width="815" alt="screen shot 2018-03-27 at 00 18 12" src="https://user-images.githubusercontent.com/37807951/37936087-7b8cb820-3154-11e8-84da-16d0e1407e36.png">

Yes, I have tried homebridge-cmd4 by itself before this and I really like it! I was really happy when I found this plugin as it's one of the only ones that I could get to work how I wanted with the GarageDoorOpener accessory in particular which I really appreciate! However as you know I'm now trying to work out how to get this to actually control my garage door as I'm currently using cmd2  to do this but it only comes up as a switch in the app which is annoying aesthetically but also as I do not receive a notification when the state changes as it's just a switch. 

It may be too much to ask but would you be able to add a file in the Extras folder which functions the same as the State.js file but has a space in it where people can add a terminal command for it to execute? 

P.S. If you are able to make an example file which includes an area to input a terminal command, is it possible to have two commands; one for the On/Open position and one for the Off/Closed position?

Kind Regards,
David

**Comment by ztalbot2000** [comment]
Sorry, it took awhile to write a SHELL Script.  I hope it helps.  As for
the log, nothing appears to be homebridge-cmd4 related as I don't see
homebridge-cmd4 debug statements.

This script only has one device, a garage door opener that would be defined
in your config.json file as "GarageDoorOpenner".  It can be expanded if you
would like but I would have just chopped most of the State.js file.  Ce La
Vie

John




#!/bin/bash

# Example 1
# ./State.sh Get GarageDoorOpenner CurrentDoorState

# Example 2
# ./State.sh Set GarageDoorOpenner CurrentDoorState 0

set -e

# Exit immediately for unbound variables.
set -u


length=$#
device=""
io=""
characteristic=""
option=""

if [ $length -le 1 ]; then
   printf "Usage: Status.sh Get <AccessoryName> <characteristic>\n"
   printf "Usage: Status.sh Set <AccessoryName> <characteristic> <Value>\n"
   exit -1
fi

# printf "args =$#\n"   # debug
# printf "arg1 =$1\n"   # debug

if [ $length -ge 1 ]; then
    io=$1
    # printf "io=$io\n"   # debug
fi
if [ $length -ge 2 ]; then
    device=$2
    # printf "device = ${device}\n"   # debug
fi
if [ $length -ge 3 ]; then
    characteristic=$3
    # printf "Characteristic = ${characteristic}\n"   # debug
fi
if [ $length -ge 4 ]; then
    option=$4
    # printf "option = ${option}\n"   # debug
fi

if [ "${io}" == "Get" ]; then
   if [ "${device}" == 'GarageDoorOpenner' ]; then
      case $characteristic in
         'CurrentDoorState')
            # These are descriped in the HAP spec and also listed in
            # State.js
            printf "0\n"         # Door is open
            # printf "1\n"         # Door is closed
            # printf "2\n"         # Door is openning
            # printf "3\n"         # Door is closing
            # printf "4\n"         # Door is stopped
            exit 0
            ;;
         'TargetDoorState')
            printf "0\n"
            exit 0
            ;;
         'ObstructionDetected')
            printf "0\n"
            exit 0
            ;;
         'LockCurrentState')
            printf "0\n"
            exit 0
            ;;
         *)
            printf "Unknown Get GarageDoorOpenner Characteristic
${characteristic}\n"
            exit -1
            ;;
       esac
   fi
   printf "Unknown Get Device: ${device}\n"
   exit -1
fi
if [ "${io}" == 'Set' ]; then
   if [ $device == 'GarageDoorOpenner' ]; then
      case $characteristic in
         'CurrentDoorState')
            # Tell you garage to set current State to $option
            exit 0
            ;;
         'TargetDoorState')
            exit 0
            ;;
         'ObstructionDetected')
            exit 0
            ;;
         'LockCurrentState')
            exit 0
            ;;
         *)
            printf "Unknown Set GarageDoorOpenner Characteristic
${characteristic}"
            exit -1
            ;;
       esac
   fi
   printf "Unknown Set Device: ${device}\n"
    exit -1
fi
printf "Unknown io command ${io}\n"
exit -1

**Comment by davidhonly** [comment]
Hi John,

Thank you very much for taking the time to write this SHELL script for me I am very thankful. 

This morning I have tried to implement the code into homebridge as you can see from the screenshot of my config.json below: (The accessory names GarageDoorOpenner with the state command "node ~/Desktop/State2.js" refers to your new script and the accessory below that is the original State.js one)

<img width="638" alt="screen shot 2018-03-27 at 11 25 40" src="https://user-images.githubusercontent.com/37807951/37959164-c2d37814-31b2-11e8-99f3-bd829042b15c.png">

I've had quite some fun playing around trying to get this to work but have a few small issues which may be down to my inexperience in JS coding.
The main problem is that when using the prefix "node" in the config file, the accessory shows "No Response" and in the terminal window I receive the following error:

<img width="566" alt="screen shot 2018-03-27 at 11 25 37" src="https://user-images.githubusercontent.com/37807951/37959466-703bf904-31b3-11e8-9f6d-47c64c0f3a3e.png">

Once again, I'm not very proficient in JS but I believe this is due to the first few lines of your script which reads: 

`#!/bin/bash`

`# Example 1`
`# ./State.sh Get GarageDoorOpenner CurrentDoorState`

`# Example 2`
`# ./State.sh Set GarageDoorOpenner CurrentDoorState 0`

`set -e`

`# Exit immediately for unbound variables.`
`set -u`

However I'm not sure if this is what is causing it so any guidance would be much appreciated :)

My final question was just if the way to implement my terminal commands would be to put the "open" one where you have written `./State.sh Get GarageDoorOpenner CurrentDoorState` and the closed one where you have written `./State.sh Set GarageDoorOpenner CurrentDoorState 0`.

Thank you ever so much once again,
David

**Comment by ztalbot2000** [comment]
Hi David,

  Since this is a shell script and not a JavaScript  script, you no longer
need the state_cmd to have node execute the State.sh. The state_cmd would
just be: .homebridge/Cmd4Scripts/State.sh

node executes JavaScript  scripts. Being more specific node can execute
JavaScript  node.js scripts.
bash executes shell scripts, like the State.sh file I made for you.

Technically you could say /usr/bin/bash State.sh Get GarageDoorOpenner
CurrentDoorState
but you do not have to if the top of the script contains #!/usr/bin/bash
and the permissions of the script are executable.
The xterm window that you are in is running the bash shell. It gives you
your bash command line prompt.  Similarly you can get into the node.js
command line interface by typing: nodejs
There are many types of shells. Python, TCL, bash, ,sh, csh and ksh to name
a few.  I was surprised you wanted a bash script, but now I understand why
you thought you needed one.

As for the question about Open;  Homebridge-Cmd4 will never send an Open
command and you cannot make it do so.  It sends the commands based on the
HAP Spec, which homebridge is built upon.  All the characteristics like
CurrentDoorState are defined there and given to you in the State.js file.
Even in the State.sh fille I made for you the values of 1-5 represent the
meaning of each DoorState.  This is all based on the HAP Spec.

It might be easier for you to stick with the original homebridge-cm2 if you
just want on or off. Otherwise alter the State.sh script I gave you and for
put all the responses together so you essentially just have an on off.

I.e.

If io = Get
    Return  0   # if door is closed
    return 1  # if door is open
If

If io = Set and option = 0
    # close the door
fi
If io = Set and option = 1
   # open the door
If


I wish I could help you more but my time too is up.
Ttfn,
John

**Comment by davidhonly** [comment]
John,

Thank you for all your support, you have been more than helpful! I believe I understand how this all works now which is great and I've had fun working with your plugin.

Thank you ever so much,
David

**Comment by ztalbot2000** [comment]
Your very welcome Dave,

  I think I had seen your working on a pi.  Do you know about the new
pi3B+. I have been hard at work trying to build a CnC with mine.  Also
check out Khodi on the Pi. There is just so much to play with and it's
practically free.

Ttfn,
John

**Comment by davidhonly** [comment]
Ah yes I have heard about the new Pi3B+ it's very interesting! I wish you luck with your CNC project, that'll be really cool if you get that working. I've seen a similar project on the Make channel which you might want to check out if you haven't already: https://www.youtube.com/watch?v=u35L0jGCqFc

Kodi is a lifesaver but fortunately I've got an Apple TV set up with both that and PopcornTime which I really recommend.

I have to say, I have fallen in love with my raspberry pi after only have discovered them at the end of last year! As you know, my current project with it is home automation which I am having a lot of fun with but I'm always open to new ideas!

Kind regards,
David

**Comment by ztalbot2000** [comment]
HHi David,

     I did the automation thing last year, hence Homebridge-cmd4.  I run it
on my headless MacMini.
The best about the pi3B+ is the faster wifi speed, being 802.11ac.

take care,
John

**Comment by sam-ams** [comment]
Hi John,
congratulations to the great work of the cmd4 plugin! I like it very much. I try to implement the garageopener on a Raspberry Pi and use your posted sh-script above. I played with it for 4 days and it executes my script for opening / closing the garage, but I have the problem to set the correct status/state (opening, closind, open, closed). Maybe you could be be so pleasant to give me a hint for the implementation… I think I have not understood the architecture of Homebridge/HomeKit/CMD4.

My script is called garage_mitte.sh garageopener is called Mittelgarage

`#!/bin/bash

length=$#
device=""
io=""
characteristic=""
option=""

if [ $length -le 1 ]; then
   printf "Usage: Status.sh Get <AccessoryName> <characteristic>\n"
   printf "Usage: Status.sh Set <AccessoryName> <characteristic> <Value>\n"
   exit -1
fi

 printf "args =$#\n"   # debug
 printf "arg1 =$1\n"   # debug
 printf "arg2 =$2\n"
 printf "arg3 =$3\n"
 printf "arg4 =$4\n" 

if [ $length -ge 1 ]; then
    io=$1
     printf "io=$io\n"   # debug
fi
if [ $length -ge 2 ]; then
    device=$2
     printf "device = ${device}\n"   # debug
fi
if [ $length -ge 3 ]; then
    characteristic=$3
     printf "Characteristic = ${characteristic}\n"   # debug
fi
if [ $length -ge 4 ]; then
    option=$4
     printf "option = ${option}\n"   # debug
fi

if [ "${io}" == "Get" ]; then
   if [ "${device}" == 'Mittelgarage' ]; then
      case $characteristic in
         'CurrentDoorState')
            # These are descriped in the HAP spec and also listed in
            # State.js
             printf "0\n"         # Door is open
            # printf "1\n"         # Door is closed
            # printf "2\n"         # Door is openning
            # printf "3\n"         # Door is closing
            # printf "4\n"         # Door is stopped
            exit 0
            ;;
         'TargetDoorState')
            printf "0\n"
            exit 0
            ;;
         'ObstructionDetected')
            printf "0\n"
            exit 0
            ;;
         'LockCurrentState')
            printf "0\n"
            exit 0
            ;;
         *)
            printf "Unknown Get Mittelgarage Characteristic
${characteristic}\n"
            exit -1
            ;;
       esac
   fi
   printf "Unknown Get Device: ${device}\n"
   exit -1
fi

 if [ "$4" = "1" ]; then
      /var/homebridge/runter_mitte.sh
printf "arg4 =$4\n"
/var/homebridge/garage_mitte.sh Set Mittelgarage CurrentDoorState 3
      exit $?
   fi

 if [ "$4" = "0" ]; then
      /var/homebridge/rauf_mitte.sh
/var/homebridge/garage_mitte.sh Set Mittelgarage CurrentDoorState 2
printf "arg4 =$4\n"
      exit $?
   fi

if [ "${io}" == 'Set' ]; then
   if [ $device == 'Mittelgarage' ]; then
      case $characteristic in
         'CurrentDoorState')
            # Tell you garage to set current State to $option
 if [ "$4" = "1" ]; then
/var/homebridge/runter_mitte.sh
fi 
 if [ "$4" = "0" ]; then
/var/homebridge/rauf_mitte.s
            exit 0
fi
            ;;
         'TargetDoorState')
            exit 0
            ;;
         'ObstructionDetected')
            exit 0
            ;;
         'LockCurrentState')
            exit 0
            ;;
         *)
            printf "Unknown Set GarageDoorOpenner Characteristic
${characteristic}"
            exit -1
            ;;
       esac
   fi
   printf "Unknown Set Device: ${device}\n"
    exit -1

fi
printf "Unknown io command ${io}\n"

exit -1`

The scripts for opening and closing are rauf_mitte.sh / runter_mitte.sh. It  switches a relay that is connected with the remote control of the garageopener. 
I hope you can support me in understanding the cmd4 and finding a way to solve the probs...

Thanks in advance and greetings from Germany!
Arne
