### ISSUE TITLE
Ability to run PowerShell commands?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [ztalbot2000/homebridge-cmd4#52]
Does this plugin allow us to run PowerShell commands? I have homebridge installed on both Windows and Ubuntu. Both support PowerShell. Is there a way to run PowerShell commands/scripts allowing me to control different things?

**Comment by ztalbot2000** [comment]
It will execute anything that you could from a command prompt; be it bash,
Python, Java, whatever...

TTFN,
John Talbot

**Comment by PrzemyslawKlys** [comment]
I see, well I tried to play with it trying to "display" something to see how it reacts but wasn't getting much results. What is the best way to "debug" this? Like defining command and seeing if it gets executed properly?

**Comment by PrzemyslawKlys** [comment]
Thank you, figured it out.

**Comment by ztalbot2000** [comment]
Good for you!

**Comment by PrzemyslawKlys** [comment]
I spoke a bit too soon. Whatever I do set doesn't work. I press button and it doesn't seem to execute PowerShell at all. With get status it doesn't have a problem, and it notices the changes I do in the script.

```powershell
$Config = "C:\Support\HomeBridge\test.json"

$Device = @{
    Status = $false
}

if ($args[0] -eq 'Get') {
    if (Test-Path $Config) {
        $Device = Get-Content -Path $Config | ConvertFrom-Json
        $Device.Status
    } else {
        $Device.Status
    }
} elseif ($args[0] -eq 'Set') {

    $args

    if ($args[2] -eq 'On') {
        if ($args[3] -eq $true) {
            $Device.Status = $true
            $Device | ConvertTo-Json -Depth 5 | Set-Content -Path $Config
            #$Device.Status
            #Write-Output "Crazy4"
        } else {
            $Device.Status = $false
            $Device | ConvertTo-Json -Depth 5 | Set-Content -Path $Config
            #$Device.Status
            Write-Output "Crazy3"
        }
    } else {
        Write-Output "Crazy1"
    }

} else {
    Write-Output "Crazy2"
}
```

If I move $args to top it shows 

![image](https://user-images.githubusercontent.com/15063294/82139083-bec4c580-9825-11ea-84f1-db76fd4d8ac7.png)

Every 5 seconds which is great. Any status change outside of Homebridge via file or PowerShell script changes the state. But when I press the button with moved $args to the top which show a similar warning as I get for Get, nothing happens. 

Maybe I need to set something? I tried setting "on" to true, tried playing with polling, tried changing type to lightbulb but nothing helped. Get works, Set doesn't work. 

```json
        {
            "platform": "Cmd4",
            "name": "Cmd4",
            "outputConstants": true,
            "accessories": [
                {
                    "type": "Switch",
                    "name": "PowerShellTest",
                    "on": false,
                    "state_cmd_prefix": "pwsh -File",
                    "state_cmd": "C:\\Support\\Homebridge\\test.ps1",
                    "polling": true,
                    "interval": 5,
                    "timeout": 4000
                }
            ]
        }
```

It's like I'm missing some configuration or concept. I am not sure what "on" in config means as well. Is it a default state for device when homebridge starts?

**Comment by ztalbot2000** [comment]
What happens when you run your script from the command Line.  Ie
Whatever your prefix + cmd is?

**Comment by ztalbot2000** [comment]
Is there supposed to be an exit status of power shell?

**Comment by ztalbot2000** [comment]
Besides the exit status, is the script slow? Increase the timeout.

**Comment by PrzemyslawKlys** [comment]
```
pwsh.exe -File 'C:\\Support\\Homebridge\\test.ps1' set one on false
pwsh.exe -File 'C:\\Support\\Homebridge\\test.ps1' set one on true  
```

The status of the accessory changes just fine. I can see it turn off / turn on when executed from cmdline.

There seems to be Exit command. The script is very basic just to write status to JSON and read it. It takes less than 1second to execute. But just not seeing the "SET" part.

**Comment by PrzemyslawKlys** [comment]
> Use the command Exit $LASTEXITCODE at the end of the powershell script to return the error codes from the powershell script.
> 
> $LASTEXITCODE holds the last error code in the powershell script. It is in form of boolean values, with 0 for success and 1 for failure.
> Exit <custom error codes> will return custom return codes from the script

Do I need the Exit command at the end?

**Comment by ztalbot2000** [comment]
Absolutely you need a script exit status

**Comment by ztalbot2000** [comment]
If set does not work from the command line, you still have a script problem

**Comment by PrzemyslawKlys** [comment]
hah! 

![image](https://user-images.githubusercontent.com/15063294/82139552-dcdff500-9828-11ea-9a8d-648255793715.png)

It seems to work with Exit being added. What are the Exit codes? 0 good, 1 bad, -1 super bad?

**Comment by ztalbot2000** [comment]
Having cmd4 send the string true or false is different than sending zero or
one.  Your script may be interpreting them differently.. test what you are
really getting and sending.  This would make the string compare to be false
if compared to a 0.
I hope you get that drift.

TTFN,
John

**Comment by ztalbot2000** [comment]
When cmd4 receives a string of true/false it will change it internally to
0/1.  Sending. Is by default numeric, unless specified in your config.json
file.

Night,
John

**Comment by PrzemyslawKlys** [comment]
But I do need to return both true or false and Exit code of 0 right? If I switched get to return only Exit 0 or Exit 1 it was failing. So now I return true/false and Exit with 0 for get. 

For Set, I'm having random results, I can't pinpoint it yet

**Comment by PrzemyslawKlys** [comment]
Ok, i found one issue the command is actually Set 'PowerShellTest' 'On' and 'true' including quotes. So i need to check for 'On' not for On.

**Comment by PrzemyslawKlys** [comment]
Now it works. It was the quotes playing tricks with me and lack of Exit. 

The following code adds one button with file and keeps status True / False. What I also see is that Homebridge UI X is acting weird. When I execute the "script" from Homekit via the button the update is instant. When I do it from Homebridge UI X, it sometimes acts, sometimes doesn't - mainly doesn't. Is it possible it returns something else to your script when pressed via GUI?

```powershell
$Config = "C:\Support\HomeBridge\test.json"

$Device = @{
    Status = $false
}

if ($args[0] -eq 'Get') {
    if (Test-Path $Config) {
        $Device = Get-Content -Path $Config | ConvertFrom-Json
        $Device.Status
    } else {
        $Device.Status
    }
    Exit 0
} elseif ($args[0] -eq 'Set') {
    if ($args[2] -eq "'On'") {
        if ($args[3] -eq "'true'") {
            $Device.Status = $true
            $Device | ConvertTo-Json -Depth 5 | Set-Content -Path $Config
            $Device.Status
        } else {
            $Device.Status = $false
            $Device | ConvertTo-Json -Depth 5 | Set-Content -Path $Config
            $Device.Status
        }
        Exit 0
    } else {
        Write-Output "Not supported $($args -join ' ')"
        Exit -1
    }
} else {
    Write-Output "Not supported $($args -join ' ')"
    Exit -1
}
```
