### ISSUE TITLE
Inconsistencies in config names, and lacking documentation

### ISSUE THREAD

**Issue by jsiegenthaler** [ztalbot2000/homebridge-cmd4#53]
Hi ztalbot2000

Great plugin, I'm starting to configure mine for the first time.

I'm setting up a Switch for my Samsung Home Theater HT-D5500
I have set my config as follows (snippet):
                    "type": "Switch",
                    "displayName": "Samsung_HT5500",
                    "on": "FALSE",
                    "name": "Samsung Stereo",
                    "manufacturer": "Samsung",
                    "model": "HT-D5500",
                    "SerialNumber": "12345",

All names are lower case except SerialNumber: that must be mixed case. Lower case fails. You should make it the same as the others (lower case, or case-insensitive)

The documentation does not state that you can set manufacturer, model and SerialNumber for each device. This is a great feature, but I found it by trial and error. Perhaps you could update the documentation.

**Comment by ztalbot2000** [comment]
Hi,

  I'm just getting to my emails.  There are tons of options and I thought I
documented most of them in the config.min.json file.  While Manufacturer,
Model and SerialNumber are there for a TV, it is not for the others.  I
will add it.

As for upper/lower case.  It is not documented, but Cmd4 does not care
about the case sensitivity of the first letter of the config option.  I
made this mistake so many times, I just made it the default.

I'll update the config.min.json file and get back to you.

ttfn,
John Talbot

**Comment by ztalbot2000** [comment]
Hmm, forgot.  You can already add polling per characteristic, so it would
be just a matter of adding the field you requested.  Investigating further
....

**Comment by jsiegenthaler** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	margin-bottom:.0001pt;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}

**Comment by ztalbot2000** [comment]
fixed under ccd726a2c4022adac966ffceaf00e3eab802cf80
