### ISSUE TITLE
[Question] Custom device to show power state

### ISSUE THREAD

**Issue by bluefangs** [ztalbot2000/homebridge-cmd4#57]
Hi,

I'm a novice at homebridge and I recently discovered cmd4. I see it's very powerful in terms of executing custom scripts. 

I have the homebridge run as a docker container inside a pi. I would like to create a device that tells me if we have a power outage / restoration. My basic idea is to have another pi that is NOT connected to my UPS. I can execute a simple command such as ping from the homebridge pi to the other pi and have it serve as a heartbeat mechanism. 

1. How do you think I should show this device as? I know some devices send out push notifications to the apple home app but I do not know which all devices do that.

2. I went through the exhaustive list of the config files to understand how to define devices. I had initially set up a roborock-vaccume as a fan. Tapping on it actually shows a fan  +  switch + sensor. Is there a provision to get this behaviour? (like the first screenshot [here](https://homekitnews.com/wp-content/uploads/2019/06/UI-SETTINGS-HOME2-IOS13.jpg))

Thanks!

**Comment by bluefangs** [comment]
Update: 

My config looks like below:

```
{
            "platform": "Cmd4",
            "name": "Cmd4",
            "outputConstants": false,
            "accessories": [
                {
                    "type": "Switch",
                    "displayName": "Power Supply",
                    "on": "FALSE",
                    "name": "Power_Supply_Switch",
                    "polling": [
                        {
                            "on": "FALSE",
                            "interval": 60,
                            "timeout": 8000
                        }
                    ],
                    "state_cmd": "sh /homebridge/cmd4-scripts/ping-power-outlet.sh"
                },
                {
                    "type": "OccupancySensor",
                    "displayName": "Power Sensor",
                    "occupancyDetected": "OCCUPANCY_NOT_DETECTED",
                    "statusActive": "TRUE",
                    "statusFault": "NO_FAULT",
                    "statusTampered": "NOT_TAMPERED",
                    "statusLowBattery": "BATTERY_LEVEL_NORMAL",
                    "name": "Power_Supply_Sensor",
                    "stateChangeResponseTime": 3,
                    "state_cmd": "sh /homebridge/cmd4-scripts/ping-power-outlet.sh"
                }
            ]
        }
```

ping-power-outlet.sh

```
#!/bin/bash
IP='192.168.0.1'
if ping -c 1 -w 1 $IP > /dev/null; 
then echo 1
else echo 0
fi

exit 0
```

**Comment by ztalbot2000** [comment]
Have a look at other issues.  Start from newest to oldest.  I remember two
of them have ping examples for power.

TTFN,
John

**Comment by bluefangs** [comment]
Thanks. I have a fair idea now. I also went through the issue list.

However, I still am not sure as to how to get the multiple devices to show up under one device. Similar to how TV_combo is. You have a tv on/off + a remote of some kind nested within the TV appliance. I am still wondering how to do that with a Switch + light bulb slider or switch + occupency sensor.

**Comment by ztalbot2000** [comment]
Cmd4 supports linked accessories like you mentioned and there is an example in the config.json file.  I don't know how different apps would show a linked configuration as you mentioned, but you could try it and see.
