### ISSUE TITLE
homebridge on windows change home directory

### ISSUE THREAD

**Issue by gprsnlty** [ztalbot2000/homebridge-cmd4#59]
hi im running homebridge on windows and keep getting this error. 
how/where can i change the home directory?

Error: Cannot find module 'C:\Program Files\nodejs\.homebridge\Cmd4Scripts\State.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by ztalbot2000** [comment]
Hi,

   This file is included in the package.  You need to copy it from the
install directory as the installation instructions state.

Take care,
John Talbot

**Comment by gprsnlty** [comment]
thanks for your quick response!

Okay in short my solution is just not run Homebridge as a service then State.js directory is as installation instructions state.

in detail when i run Homebridge as a Service on windows the plugin is looking for State.js in
'C:\Program Files\nodejs.homebridge\Cmd4Scripts\State.js'
And it wants to create the Cmd4States folder in 'C:\WINDOWS\system32\config\systemprofile\.homebridge\Cmd4Scripts\Cmd4States'
(according to error messages)

I then tried to put the State.js as well as created the Cmd4States folder at the given locations.
But even after adjusting folder permissions the state_cmd still failed.

Is it possible to run Homebridge as a service on windows with this plugin by changing the expected home directory?

**Comment by ztalbot2000** [comment]
Hi,

   Sorry I have not worked with Windows in years and cannot help you in
that respect.  I created Cmd4 as a plug-in to HomeBridGe which reads the
config.json file from $HOME/.homebridge, so the State.js file would be put
in the directory Structure beyond that.  Why windows would think it is
trying to access system32 is beyond me.
  I can suggest that you make sure Homebridge is first installed and
started from their recommended directories.  After that Homebridge should
run the CMD4 plugin just like any other.
  The State.js file is the script that creates the Cmd4States directory to
hold files containing device state information.  This is just temporary
data.  If you edit the script you may be able to change the location to
something more accessible like maybe /temp.
   Hopefully this helps,

John Talbot
