### ISSUE TITLE
Temperature from DHT22

### ISSUE THREAD

**Issue by elkorleone** [ztalbot2000/homebridge-cmd4#6]
I'm trying to use the thermostat accesory with data from a DHT22, what have to change into the code?

**Comment by ztalbot2000** [comment]
Hi,

   Interesting project and perfect for HomeBridge-Cmd4.

I assume that you already have HomeBridge-Cmd4 running on some target like
a Pi or Beaglebone, it does not matter so long as you see what is in the
screenshots of HomeBridge-Cmd4.  You can create your own command script or
alter the included State.js script.
Where you see My_TemperatureSensor, for each of the Characteristics of (Get
& Set) you would call something like readDHT and output the values as
described by the HAP spec that is shown.
For example:

         case "My_TemperatureSensor":

         {

            //==============================

            //    TEMPERATURE SENSOR (GET)

            //

            // UUID: 0000008A-0000-1000-8000-0026BB765291

            // Type: public.hap.service.sensor.temperature

            //==============================

            switch(characteristic)

            {

               readDHT();

               case "CurrentTemperature":

               {

                   console.log(dht.readTemperature());

                   process.exit(0);

                   break;

               }

               case "StatusActive": // Optional

               {

                   if(innan(tempHumi) || isnan(tempTemp)

                   {

                      console.log(1);    // Fault

                   } else {

                      console.log(0);   // No Fault

                  }

                  process.exit(0)

                  break;

              }

              case "StatusLowBattery": // Optional

               {

                    ....

              }

          }


  I  hope this helps you.

  John Talbot
