### ISSUE TITLE
A number of typos in the Documentation

### ISSUE THREAD

**Issue by jsiegenthaler** [ztalbot2000/homebridge-cmd4#61]
There's a number of typos on this page:
https://www.npmjs.com/package/homebridge-cmd4

I've detailed them for you below.

Section "About the Cmd4 Plugin" 
Typo in "**Similiar** to other command plugins,"
**Similiar** is wrong. It should be **Similar**

Typo in "but now they can appear as a Garage Door **openner**"
**openner** is wrong. It should be **opener**

Typo in "and you can **cntrol** all of their characteristics too."
**Cntrol** is wrong. It should be **control**

Section "Features"
Typo in "Cmd4 supports, Lights, Garage Door **Openners**"
**Openners** is wrong. It should be **Openers**

Typo in "so that accessories like a garage door is updated in HomeKit after it was closed or **openned**."
**openned** is wrong. It should be **opened**

Typo in "Cmd4 can be configured to respond to actual devices directly or by **modofying** the script file it calls"
**modofying** is wrong. It should be **modifying**

Section "Whats new in 2.2"
Typo in "This release also defines constants for all **thecharacteristics** "
**thecharacteristics** is wrong. It should be **the characteristics**

Section "Installation"
Typo in Step 5 "SHELL> **homebrige**"
**homebrige** is wrong. It should be **homebridge**

Typo in Step 6 "The gist of it is that you **entet** the manual code"
**entet** is wrong. It should be **enter**

Section "Troubleshooting"
Typo in Step 1 "is expected to run from a **users** home "
**users** is wrong. It should be **user's**

Section "Adding in fakegato-history"
Typo in Step 3 "enable polling and interval for the **accesory**"
**accesory** is wrong. It should be **accessory**

Typo in Step 3 "according to the fakegato-**hitory** documents "
**hitory** is wrong. It should be **history**

Section "Raspbian-Stretch"
Typo in Step 2 "Os.tmpDir() is **depricated**"
**depricated** is wrong. It should be **deprecated**

Typo in Step 3 "**commentiing** out the others and save the file"
**commentiing** is wrong. It should be **commenting**

Typo in Step 4 "Update sources or you **wil** not be able to download "
**wil** is wrong. It should be **will**

Typo in Step 5 "It **ahould** return >=8.11.1"
**ahould** is wrong. It should be **should**

Section "Unit Testing"
Typo in Step 1 "This is done **seperate** from the"
**seperate** is wrong. It should be **separate**

Typo in Step 3 "Install homebridge-cmd4 development **dependancies**"
**dependancies** is wrong. It should be **dependencies**

Section "Rationale"
Typo in Step 3 "If you were wondering what **happenned** to version 3"
**happenned** is wrong. It should be **happened**

**Comment by ztalbot2000** [comment]
Hi,

   My wife thanks you!  I will fix them shortly.  I should add spell check
to my vi sessions.

John

**Comment by ztalbot2000** [comment]
Fixed under commit 3f36727.   I'm not actually that bad.  I do need an operation on my eyes, but I would not let the surgeon go near them. So I'll blame it on that.  I do very much appreciate you checking it though. Thanks again.

**Comment by jsiegenthaler** [comment]
You are welcome. I had both eyes operated over the last few years. Scary but better afterwards.

**Comment by ztalbot2000** [comment]
You are braver than I was.  I was in the chair with one eye clamped open
and then bailed as they were bringing the scraper towards my eyeball.

TTFN,
John
