### ISSUE TITLE
Change Logs and Fix Readme for Config-UI-X

### ISSUE THREAD

**Issue by mitch7391** [ztalbot2000/homebridge-cmd4#62]
Hey @ztalbot2000  I was wondering if you can make your change logs appear in config-ui-x? Some plugins when updated on config UI X have a pop-up box that lists the latest updates to the plug-in :) I believe all you need to do is move the Changelog from README.md to the CHANGELOG.md file. 

I have noticed when updating your plug-in from config UI X, that the readme file comes up before clicking continue, but the last two updates it still shows three updates ago about changes to suffix commands or something like that. Last time I figured it may have been a glitch but I saw it again with your not recent update.

**Comment by ztalbot2000** [comment]
Hi,

It is the notes written directly in postinstall.js.  It is crudely
triggered only when major changes occur to warn of things you must know
about.  Minor changes like spelling errors are unimportant.  It kind of
depends what version you came from and too.

TTFN,
John

**Comment by mitch7391** [comment]
Oh ok, I guess for someone who doesn’t know that, it almost appears as if you are installing the same version again. I’ll keep that in mind in future.

**Comment by ztalbot2000** [comment]
Hi,

   just released 2.4.0. it is mainly a refactor, but it does move everything to a ChangeLog file.  The postinstall.js file now just gives a kind of Welcome message.
I hope this helps any confusion you may have had.

ttfn,
John Talbot

**Comment by mitch7391** [comment]
Thanks John :)
