### ISSUE TITLE
What is polling exactly?

### ISSUE THREAD

**Issue by hunhejj** [ztalbot2000/homebridge-cmd4#64]
Great plugin! However I struggle to understand what polling is exactly for, when to use, when not to use.

I guess it is only needed if a device works async? How to configure a normal device then, that works sync and should set the state once the command was handled e.g. with `State.js`?

**Comment by ztalbot2000** [comment]
Hi,

  By default HomeKit only gets the status of any device when you access the App.  This is the closest you can get to push notifications.  I hope that helps.

TTFN,
John
