### ISSUE TITLE
hi television icon won't show

### ISSUE THREAD

**Issue by aecom** [ztalbot2000/homebridge-cmd4#66]
after iOS 14 upgrade 
any idea?

**Comment by ztalbot2000** [comment]
Hi,

  Have you upgraded to the latest HomeBridge and Homebridge_Cmd4?  Have you
restarted Homebridge since the upgrade?   Have you tried running Homebridge
in debug mode?
If you have tried all these, send me your config.json file.
Are you using Eve or Apples Home App?
I have been using IOS 14 for some time now and have not seen any issues.  I
was also on the Best program and all was well.

TTFN,
John Talbot

**Comment by aecom** [comment]
Hi every thing is up to date have another phone with iOS 13 it is working 


IOS 14





> ‫ב-26 בספט׳ 2020, בשעה 12:43, ‏‏John Talbot ‏<notifications@github.com> כתב/ה:‬
> 
> ﻿
> Hi,
> 
> Have you upgraded to the latest HomeBridge and Homebridge_Cmd4? Have you
> restarted Homebridge since the upgrade? Have you tried running Homebridge
> in debug mode?
> If you have tried all these, send me your config.json file.
> Are you using Eve or Apples Home App?
> I have been using IOS 14 for some time now and have not seen any issues. I
> was also on the Best program and all was well.
> 
> TTFN,
> John Talbot
>

**Comment by ztalbot2000** [comment]
Interesting.   Have you tried rpowering on/off the IOS 14 device?
I would still appreciate your config.json file as well.

Thanks,
John

**Comment by aecom** [comment]
{
            "platform": "Cmd4",
            "name": "Cmd1",
            "accessories": [
                {
                    "type": "television",
                    "name": "JVCTV",
                    "on": false,
                    "state_cmd": "sh /var/lib/homebridge/CMD4SCRIPTS/PS4.sh",
                    "polling": true,
                    "interval": 5,
                    "timeout": 2000
                },
                {
                    "type": "television",
                    "name": "MAG",
                    "on": false,
                    "state_cmd": "sh /var/lib/homebridge/CMD4SCRIPTS/MAG.sh",
                    "polling": true,
                    "interval": 5,
                    "timeout": 2000
                }
            ]
        },

**Comment by ztalbot2000** [comment]
There are two TV's in your config.json.  Do they both not show?

**Comment by aecom** [comment]
Yes both of Theo it happens on my iPad on iOS 14

**Comment by ztalbot2000** [comment]
I'll have to look at it in the morning.  I just happen to be up.

TTFN,
John

**Comment by aecom** [comment]
Ok thanks good night

**Comment by ztalbot2000** [comment]
Hi,

   I really have not had the time to spend on this as it deserves.  I took
your config.json file and applied it to a fresh install of homebridge and
homebridge-cmd4.  Clearly homebridge has done something that automatically
defines values for required characteristics.  This may be an issue.  The
log is attached.  I will have to look at it some more.  It is possible that
multiple accessories with the same type could have the same default value.
Just a thought.

I did find one error in a debug log of mine.  It is corrected in this log.
If you run it you will see that it says "for %s".  It is not a major issue,
but I will fix it after I determine how it got there.

I did change the PS4.sh file to accurately look like the original cmdSwitch
version.  I do not know if the path you are referring to in your
config.json file is this one.  What I was planning to do was put a
collection of scripts, like the PS4.sh into the distribution for others to
look at.

Hopefully I will have more time tomorrow.

ttfn,
John Talbot

**Comment by denzel1994** [comment]
With iOS 14 TVs need to be an unbridged accessory from the homebridge to show up with the TV icon.

**Comment by ztalbot2000** [comment]
Thanks Denzel !

**Comment by ztalbot2000** [comment]
I did find that if ConfiguredName was not provided and multiple devices of the same type were in the config.json file (In your case 2 TV's) then only one of them was showing in IOS 14.  I just submitted https://github.com/ztalbot2000/homebridge-cmd4/commit/4a4fd5255fdc5eeffac2b9246414af80a8d1356d which addresses this.  Download the index.js file of the latest changes to your installation and give it a try. I'm closing this as resolved with this update.

**Comment by MichlW** [comment]
This is not closed by installing latest index.js file.

Televisions are still displayed as house icon.

**Comment by ztalbot2000** [comment]
Hey Mitch,

   Your beating me to it.  Can you send me your config.json file please.

Thanks,
John

**Comment by MichlW** [comment]
Hey John,

here it is:

```
{
            "platform": "Cmd4",
            "name": "Cmd4",
            "accessories": [
                {
                    "type": "Television",
                    "displayName": "Fernseher",
                    "active": "ACTIVE",
                    "activeIdentifier": 1234,
                    "configuredName": "Fernseher",
                    "sleepDiscoveryMode": "ALWAYS_DISCOVERABLE",
                    "brightness": 8,
                    "closedCaptions": "DISABLED",
                    "displayOrder": 0,
                    "currentMediaState": "STOP",
                    "targetMediaState": "STOP",
                    "pictureMode": "STANDARD",
                    "remoteKey": "SELECT",
                    "Manufacturer": "GRUNDIG",
                    "Model": "50VLE931BL",
                    "SerialNumber": "31002357",
                    "polling": [
                        {
                            "active": "ACTIVE",
                            "interval": 5,
                            "timeout": 5000
                        },
                        {
                            "currentMediaState": "STOP",
                            "interval": 5,
                            "timeout": 5000
                        }
                    ],
                    "stateChangeResponseTime": 1,
                    "state_cmd": "sh /homebridge/Television.sh"
                }
            ]
        }
```

My Homebridge runs in Docker container.

Function is fully given, but Icon is wrong...

**Comment by MichlW** [comment]
Hey John,

Glad that you find another problem with handling UUIDs ;-)

But I think you misunderstood something... It is not a question of devices not being displayed at all. The point here is that TVs are displayed with a wrong icon in the Home app. In iOS 13 TVs were displayed with a TV icon and that has changed only by upgrading to iOS 14.

You should have a look at this:

> With iOS 14 TVs need to be an unbridged accessory from the homebridge to show up with the TV icon.

Other plugins might have a solution to fix that with `publishAllTVAsExternalAccessory` option, but I do not really know what that means and if you should change some code or if I should do some configuration of my Homebridge.

Best regards
Michael
