### ISSUE TITLE
Multiple options switch

### ISSUE THREAD

**Issue by arkadicolson** [ztalbot2000/homebridge-cmd4#67]
I'm looking for "security alarm"-like switch with 4 options free to customize by the status script. Anybody knows if it's already available somewhere in the current list of accessories? Is could not find it. Or can it be developed?

**Comment by ztalbot2000** [comment]
Hi,

   You will have to write your own scripts.  As for options that are
available, look at the provided config.json file for security.  Each option
is described as the HomeKit documentation does in the provided State.js
file.
   CMD4 supports every option possible, but the scripts you need to write
yourself. Some example scripts are also provided in the installed Extras
path.

Thanks for considering CMD4

**Comment by arkadicolson** [comment]
Hi, thanks for the quick response. I already looked at the security 
plugin but for example it's not possible to change the labels of the 4 
states... And I will get the security confirmation on the phone because 
it's a security device...

I'm actually looking for an accessory to control my 4 state ventilation 
system (OFF, LOW, MEDIUM and HIGH). Currently using the fan accessory 
which is working but I had to create a script which takes care of the 
conversion from percentage values to my ESP board relays. It would be 
nicer to just have 4 steps. Is it perhaps possible to add a MIN and MAX 
value in the fan accessory?

**Comment by ztalbot2000** [comment]
Hi,

   I had to refresh my memory on this one.  Unfortunately your stuck with the pre-defined characteristic attributes. The reason for this is that even if you did create on/off/médium/high ... The Home App would not know what to do with them.  Manufacturers create their own Apps, getting certification from Apple to do things like you want.
What you have done to mimic this with speed ranges is the accepted solution.  If you search yourself, this is what you will find.

So unfortunately, nothing can be done to create on/off/high/low and I will close the ticket as what you have already implemented is the correct and only solution.

**Comment by arkadicolson** [comment]
Ok, thanks for looking into this. It's clear to me...

Arkadi
