### ISSUE TITLE
StatelessProgrammableSwitch

### ISSUE THREAD

**Issue by arkadicolson** [ztalbot2000/homebridge-cmd4#68]
How can I access a StatelessProgrammableSwitch? Do I have to make some http calls to somewhere?

**Comment by ztalbot2000** [comment]
Hi,

   The characteristics for Stateless programmable switch are listed in the
config.json, with an script being parsed in State.js.
If your scripT needs to use http, then iT will be very complicated as you
have command line options of wget, curl and mosquitto. Mosquitto is very
difficult.
  Please remember that CMD4 executes shell scripts, so whatever you can do
on the command line is what CMD4 can do.
Sorry, probably not the answer you are looking for.  Scripting can be easy,
but also very very difficult,.

TTFN,
John

**Comment by arkadicolson** [comment]
I understand that but when I add the switch to homebridge I get a button 
in Homekit. When I click on that button I immediately get the 
configuration screen for the button where you can configure one click, 
two clicks and long press. So cmd4 is only doing Get's for this 
accessory. I cannot trigger a set anywhere in the homekit app. So I was 
thinking perhaps there a http server listening somewhere to trigger the 
Set actions. Or do I misunderstand this accesory?


Arkadi

**Comment by ztalbot2000** [comment]
Hi,

   Sorry, I did not get a chance to delve further today. I would run Homebridge in debug mode and see what it is receiving/sending to understand the accessories behavior.  I certainly do't know what each attribute is and would have to figure it out how I just mentioned.

Sorry, time is the only thing you cannot buy and don't have enough of.  Maybe I will have a chance tomorrow.

TTFN,
John

**Comment by ztalbot2000** [comment]
Hi,

  So I duplicated what you did and it's behavior.  All I can say is that I really do not understand what HomeKit believes a StatelessProgrammableSwitch should do.  It seems to trigger or be triggered by a scene.  I will have to read up on it to see what it is.
  CMD4 does handle all accessories and their all their characteristics, that is not to say that I know what each are.
Your other question I have not looked into yet.  Do you prefer this one or the other as more important?

**Comment by ztalbot2000** [comment]
I did some quick research.  A Stateless programmable Switch is not what you and I thought it was.  Here is a nice blurb from: https://github.com/NRCHKB/node-red-contrib-homekit-bridged/wiki/Example-Stateless-Programmable-Switch


The stateless programmable switch is meant to replicate the function of a button similar to Logitech Pop or Phillips Hue Remote. It can be used to set scenes in the Home app. In a setup with mixed Node-RED HomeKit devices and authentic HomeKit devices, this setup can be used to control the official HomeKit devices from within Node-RED.

So with that being said. I will close the issue as it does what it is supposed to.

**Comment by arkadicolson** [comment]
I believe it's made to be triggered be something, I only don;t now how 
and if it's build in with the cmd4 plugin.

Arkadi

**Comment by arkadicolson** [comment]
Ok, thanks for the information...

Arkadi

**Comment by ztalbot2000** [comment]
Me neither.  I guess I could look into it further.

TTFN,
John
