### ISSUE TITLE
Help wanted: LockMechanism through GPIO OUT with problems

### ISSUE THREAD

**Issue by MichlW** [ztalbot2000/homebridge-cmd4#69]
Hey guys,

I wired a simple door opener through GPIO OUT and tried to use your plugin to expose it as LockMechanism to HomeKit. Now I think I did not completely understood the scheme on how to use this plugin.

The opener does not support any opened/closed-state and only need an impulse to get opened and then automatically gets closed after round about 2 seconds.
(To clarify what it is: [https://www.amazon.de/summer-türöffner/s?k=summer+türöffner](https://www.amazon.de/summer-türöffner/s?k=summer+türöffner))

What I actually want to achieve is, that the Device gets the short impulse to open (100ms) but in HomeKit it should be displayed as "unlocked" for 2 seconds (thats the time the physical opener "hums") and then automatically gets closed.
In HomeKit it should be shown as "normally closed".

So, at first I configured it in config.json:
```
{
	"platform": "Cmd4",
	"name": "Cmd4",
	"accessories": [
		{
			"type": "LockMechanism",
			"displayName": "Haustür",
			"lockCurrentState": "SECURED",
			"lockTargetState": "SECURED",
			"name": "Haustür",
			"polling": [
				{
					"lockTargetState": "UNSECURED",
					"interval": 1,
					"timeout": 500
				}
			],
			"stateChangeResponseTime": 1,
			"state_cmd": "sh /homebridge/DoorLock.sh"
		}
	]
}
```
Then I created the script DoorLock.sh:
```
#!/bin/sh

if [ "$1" = "Get" ]; then
	case $3 in
		"LockCurrentState")
			echo 1
		;;
		"LockTargetState")
			echo 1
		;;
	esac
	exit 0
fi

if [ "$1" = "Set" ]; then
	case $3 in
		"LockTargetState")
		if [ "$4" = "0" ]; then
			echo 1 > /sys/class/gpio/gpio24/value
			sleep 0.1
			echo 0 > /sys/class/gpio/gpio24/value
		fi
		;;
	esac
	exit 0
fi

exit 66
```

In principle it works, but there are two problems:

**1. Problem:**
When opened through Home app the state "unlocking..." (with that small rotating circle) is displayed for 1-2 seconds and then the device gets closed.

From this:
![image](https://user-images.githubusercontent.com/49558935/96987444-4cb68200-1523-11eb-8f55-508eba131060.png)
To this:
![image](https://user-images.githubusercontent.com/49558935/96987195-f5b0ad00-1522-11eb-91f8-3b7862ec0762.png)
To this:
![image](https://user-images.githubusercontent.com/49558935/96987444-4cb68200-1523-11eb-8f55-508eba131060.png)

-> It seems, that it never reach the state "unlocked" before it gets locked again.
Is this normal?
Can this be achieved to avoid "dead times" or "waiting times"?

**2. Problem:**
When opened through Siri by "Hey Siri, please open the Door", it gets opened but then Siri says: "Sorry, I wasn't able to lock your Door. For more details, check the Home app."

![image](https://user-images.githubusercontent.com/49558935/96987374-35779480-1523-11eb-942f-1e24d00f2220.png)

Is this caused by logical issues in my DoorLock.sh ?

I found [this](https://github.com/maximkulkin/esp-homekit-demo/issues/321#issuecomment-610570020) that describes differences in HomeKit if used by the Home app or through Siri.
Do you handle that correctly in your plugin?

Thanks in advance.

And if it hasn't been said often enough: Your plugin is amazing. Thanks for all your work on that!

**Comment by ztalbot2000** [comment]
Hi Mitch,

  I sort of lost your email and thought it was about another person I was
talking to.  His name is also Mitch. ;-)
I kind have have an idea, but I want to check it out first before I fully
respond.

Ttyl today,
John Talbot

**Comment by ztalbot2000** [comment]
Hi Mitch,

  Again I apologize for missing your email and not replying sooner.

So the first thing I notice is that the state_cmd has the path to DoorLock.sh as "sh /homebridge/DoorLock.sh". This seems odd in that do you really have this shell script located in the root directory of your filesystem being '/' ?  
When you run homebridge, is there a warning message from CMD4 saying that the shell script cannot be found? 
....
[10/25/2020, 10:31:27 AM] [Cmd4] The script /homebridge/DoorLock.sh does not exist, It is highly likely the state_cmd will fail. Hint: Do not use wildcards that would normally be expanded by a shell.
....
Maybe you meant this to be "sh .homebridge/DoorLock.sh".  That is what I had to do to test your script.

I ran homebridge in debug mode to test this using:
DEBUG=* homebridge -D

After correcting the path It does seem to do what you want for the Get:
[10/25/2020, 10:33:36 AM] [Cmd4] getValue accTypeEnumIndex:(70)-'LockTargetState' function for:Haustür cmd:sh .homebridge/DoorLock.sh Get 'Haustür' 'LockTargetState'
[10/25/2020, 10:33:36 AM] [Cmd4] getValue LockTargetState function for:Haustür returned:1

From the "Home" App I did see an icon for Bedroom Haustur Locked. Tapping it toggles it back and forth between states very quickly.  The logs show:
  HAP-NodeJS:Accessory [MAC Test Homebridge E1A5] Setting Characteristic "Lock Target State" to value 0 +0ms
[10/25/2020, 10:43:39 AM] [Cmd4] setValue LockTargetState function for:Haustür cmd:sh .homebridge/DoorLock.sh Set 'Haustür' 'LockTargetState' '0'
[10/25/2020, 10:43:40 AM] [Cmd4] Doing Poll of index:70 characteristic:LockTargetState for:Haustür timeout=500 interval=1000
[10/25/2020, 10:43:40 AM] [Cmd4] getValue accTypeEnumIndex:(70)-'LockTargetState' function for:Haustür cmd:sh .homebridge/DoorLock.sh Get 'Haustür' 'LockTargetState'
[10/25/2020, 10:43:40 AM] [Cmd4] getValue LockTargetState function for:Haustür returned:1


So after correcting the path issue.  I do not see a problem.  If you are still having issues please let me know. I'll close this for now and you can re-open it if needed. I suggest you run in DEBUG mode to find any issues you may have in your environment.

ttfn,
John Talbot

**Comment by MichlW** [comment]
Hey John,

thanks for your reply.

In my setup Homebridge runs inside Docker container and therfore /homebridge/DoorLock.sh is correct. The configuration and the script works as its should. Setup is (was) not my problem.
Sorry that I did not mentioned these in my first message.

Yesterday I found a solution for my problems - in fact I better understand the principles of HomeKit when working with your plugin.

1) The first problem is solves by setting `"stateChangeResponseTime": 0.1` - I assumed that the smallest value had to be 1 second - that was wrong. By this the State "Locking..." switches to "Locked" much quicker than before without that annoying rotating circle.

2) The second problem with Siri I fixed by a Workaround. Every time the Lock in HomeKit was automatically be closed after 1 second Siri failed, because "she wondered" why it is closed, although she has just opened it. By increasing the polling for LockTargetState and LockCurrentState Siri now works also. The lock only closes when Siri has finished her work.

```
"polling": [
	{
		"lockCurrentState": "SECURED",
		"interval": 5,
		"timeout": 4900
	},
	{
		"lockTargetState": "SECURED",
		"interval": 5,
		"timeout": 4900
	}
],
```

The Lock will now be closed after 5 seconds at the latest. These are not the 2 seconds after which the physical lock actually closes again, but that's ok for me.

In slow network conditions when I am outside from my home the 5 seconds can still be too short, but thats nothing we can fix. Siri just can not handle Locks that gets automatically gets locked after a amount of time.

Thank you again.

greets
Michael (not Mitch ;-)

**Comment by ztalbot2000** [comment]
Hi Mitch,

  I'm glad you got it to work.

I liked your script so much I put it as an example in the next version of
Cmd4.  It's in GitHub right now, yet to be released.

I started collecting examples so others could use.  Yours was a good one.
It's all about sharing ideas. Thanks for yours.

TTFN,
John

**Comment by MichlW** [comment]
I also updated the script so that it remembers the last state and that it resets the GPIO out more times, even when the script fails for some reasons when setting LockTargetState.

```
#!/bin/sh

STATE_FILE="/homebridge/DoorLock.state"

if [ ! -f "$STATE_FILE" ]; then
        echo 1 > $STATE_FILE
fi

STATE=$(cat $STATE_FILE)

if [ "$1" = "Get" ]; then
        case $3 in
                "LockCurrentState")
                        echo $STATE
                ;;
                "LockTargetState")
                        echo $STATE
                        echo 1 > $STATE_FILE
                ;;
        esac
        echo 0 > /sys/class/gpio/gpio24/value
        exit 0
fi

if [ "$1" = "Set" ]; then
        case $3 in
                "LockTargetState")
                if [ "$4" = "0" ]; then
                        echo 0 > $STATE_FILE
                        echo 1 > /sys/class/gpio/gpio24/value
                        sleep 0.1
                fi
                ;;
        esac
        echo 0 > /sys/class/gpio/gpio24/value
        exit 0
fi

exit 66
```

**Comment by ztalbot2000** [comment]
Hi Mich,

  Any reason you do not get the state of the gpio directly from the gpio
instead of it being stored in a file?

ttfn,
John

**Comment by MichlW** [comment]
Hey John,

It is mostly because I do not want to have the locked state already after 100ms when the gpio will set to low.

The virtual state will be set to low only after the polling time configured in cmd4:
```
"LockTargetState")
   echo $STATE
   echo 1 > $STATE_FILE
;;
```

This is needed so that Siri can deal with the states correctly when you control the lock with "Hey Siri, open the door". If it closes too early, Siri thinks an error has occurred.

Greetings
Michael

**Comment by ztalbot2000** [comment]
Thanks for the reply about the GPIO.  I'll note this in the script when I
add it.

TTFN,
John

**Comment by andreapellegrin** [comment]
### Hi John, hi Michael,
Similar situation here!
My opener is unlocked when I give power (or better GND cause my relay is inverted) on GPIO pin and is locked when it isn't.

**I've 2 possibilities:**

### First
![Schermata 2020-12-28 alle 14 36 30](https://user-images.githubusercontent.com/8282987/103217932-1548c500-491a-11eb-81e1-12236ae5dc02.png)
Opener is locked and so it is showed on Home app.
When I click on it, the GPIO pin is "powered" and so my door is unlocked: now you have the time to fisically open the door.
This is the icon showed on HomeKit, for few seconds (like 2 for example) [Door is unlocked]
![Schermata 2020-12-28 alle 14 39 37](https://user-images.githubusercontent.com/8282987/103218135-838d8780-491a-11eb-8512-2314de7c1770.png)
And here everything ok. The problems is that I don't know if i can update again the state to show the opener as locked.
That's would be the better solution and the most correct, also Siri I think shouldn't have particular trouble.

I think in this case I should set `"stateChangeResponseTime": 0.1` and should work fine.
But how can I update again HomeKit status? There's a way?

### Second
**Imitate Michael solution**
I've tried to follow Michael solution, but I can't make it work.

I've made a Python script and I'm using GPIO pin status, not a file like Michael.
So I think this should be the result:
Door locked, you click, door is unlocking, door is locked again. (Without using unlocked state, right?)
![Schermata 2020-12-28 alle 14 36 30](https://user-images.githubusercontent.com/8282987/103217932-1548c500-491a-11eb-81e1-12236ae5dc02.png)
![Schermata 2020-12-28 alle 14 48 18](https://user-images.githubusercontent.com/8282987/103218598-ba17d200-491b-11eb-958f-23b19269663d.png)

**That's my Python script**
```import RPi.GPIO as GPIO
import argparse
import time

parser = argparse.ArgumentParser()
parser.add_argument("pin", type=int)
parser.add_argument("mode") # Get / Set
parser.add_argument("characteristicString")
args = parser.parse_args()

pin = args.pin;

GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO.setup(pin, GPIO.OUT)

if (args.mode == "Get"):
    if (args.characteristicString == "LockCurrentState"):
        if (GPIO.input(pin)) == 0: # Do better condition for use all possible states
            print(0) # Unsecured
        else:
            print(1) # Secured
    elif (args.characteristicString == "LockTargetState"):
        if (GPIO.input(pin)) == 0:
            print(1)
        else:
            print(1) # Should be 0 but here lock is always locked (is wrong?)
elif (args.mode == "Set"):
    if (args.characteristicString == "0"):
        GPIO.output(pin, GPIO.LOW)
        time.sleep(1.5) # Time opener is unlocked
    GPIO.output(pin, GPIO.HIGH)
```

**Possible values for LockMechanism**
"lockCurrentState":
    0 - "UNSECURED"
    1 - "SECURED"
    2 - "JAMMED"
    3 - "UNKNOWN"

"lockTargetState":
    0 - "UNSECURED"
    1 - "SECURED"

Here my config.plist file:
```
{
            "platform": "Cmd4",
            "name": "Cmd4",
            "outputConstants": false,
            "accessories": [
                {
                    "type": "LockMechanism",
                    "displayName": "My_LockMechanism",
                    "lockCurrentState": "SECURED",
                    "lockTargetState": "SECURED",
                    "name": "Porta",
                    "Manufacturer": "Andrea Pellegrin",
                    "Model": "1",
                    "SerialNumber": "1",
                    "stateChangeResponseTime": 2,
                    "state_cmd": "python /home/pi/.homebridge/lock.py 17",
                    "polling": [
                        {
                            "lockCurrentState": "SECURED",
                            "interval": 5,
                            "timeout": 4900
                        },
                        {
                            "lockTargetState": "SECURED",
                            "interval": 5,
                            "timeout": 4900
                        }
                    ]
                }
            ]
        }
```

In this case I set `"stateChangeResponseTime": 2`.
Here problem is Siri, I didn't understand how Michael fix it, and how polling works exactly, it always says the same annoys message.

With older version of cmd-accessory everything was working fine. 😭 

Hope to fix,
Thanks everyone :)
Andrea Pellegrin
