### ISSUE TITLE
Homebridge 1.3.0-beta shows Warning for Cmd4: Cmd4 will throw errors in Homebridge in the future

### ISSUE THREAD

**Issue by jsiegenthaler** [ztalbot2000/homebridge-cmd4#71]
Seen today when I upgraded Homebridge to v1.3.0-beta.33

[21/12/2020, 09:26:26] Received warning for the plugin 'homebridge-cmd4' from the characteristic 'Name': characteristic was supplied illegal value: number instead of string. Supplying illegal values will throw errors in the future!

**Comment by ztalbot2000** [comment]
Hi,

  Wow what a find!  Thanks I will have a look.

I've been working hard on Cmd4 for a while. I've pretty much rewrote
everything except the libs all because of IOS 14 and Homebridge's latest
changes.  Just doing documentation now.  I will definitely check this out.

Thanks again,
John Talbot

**Comment by jsiegenthaler** [comment]
Hmmm... wierd... looks like the Homebridge update to 1.3.0 renamed a number of my Cmd4 plugins to numeric values, even though the config file has the right names
Worthwhile you having a look though.

**Comment by jsiegenthaler** [comment]
FYI: Issues occurs on 1.3.0 only. v1.2.4 is OK

**Comment by ztalbot2000** [comment]
Hi,

 In the beginning I checked if the value received was numeric, it processed
it as such.  Yesterday I wrote a routine that checks the characteristic
type given bY homeBridge and it will convert any received value to that
type.  It  passed the unit TesTs and I encorporated it inTo Cmd4.  I've
still got some real testing to do. The changes will be in Cmd4 3.0.  I've
yet to push the changes to my dev branch.

Thanks again!
John

**Comment by jsiegenthaler** [comment]
@ztalbot2000 great to hear, glad to have been of assistance

**Comment by ztalbot2000** [comment]
Hi,

  If you are up for an adventure try the Cmd4 on branch b_IOS14_dev.  You
would need all the files in lib and utils as well as the index.js.

The config.json is 100% backward compatible except now each entry is a
platform and to have the accessory as an external platform you would add
"publishExternally": true. This is useful for TV's. Also for TV's you would
add "category": "TELEVISION". This was a big change that affected TV icons
not showing.

CMD4 now follows the recommended API as described on
https://developers.homebridge.io/#/.  A duplicate config.json file can then
be created exactly for https://developers.homebridge.io/#/service/Television
and
https://developers.homebridge.io/#/api/accessory-plugins.

Now that all accessories are platforms, to create a standard accessory
accessory (double words intended) you would add "accessory": "Cmd4".  It's
a little tricky without proper documentation, which I'm working on now.

Version 3.0 also adds in a couple of dozen new accessory types and over 50
new characteristics.  You would be the first to peak at it and anything you
find would be much appreciated.

TTFN,
John

**Comment by ztalbot2000** [comment]
Oh, and your fix is in there too

**Comment by ztalbot2000** [comment]
Fixed in dev branch b_IOS14_dev
