### ISSUE TITLE
 .

### ISSUE THREAD

**Issue by andreapellegrin** [ztalbot2000/homebridge-cmd4#74]

**Comment by andreapellegrin** [comment]
Fixed reading older issues, sorry.

**Comment by ztalbot2000** [comment]
Hi,

  Don't be sorry,  sometimes writing it down helps.

Merry Christmas,
John Talbot

**Comment by andreapellegrin** [comment]
Hahah! You're right.

Merry Christmas too.
Andrea Pellegrin
