### ISSUE TITLE
Characteristic polling syntax

### ISSUE THREAD

**Issue by arkadicolson** [ztalbot2000/homebridge-cmd4#75]
Hi

Since the last update I got the warning about the characteristics change. So I changed my config like the snippet below:
However I still got the warning.
[Cmd4] Cmd4Platform didFinishLaunching
[1/12/2021, 8:48:09 AM] [Cmd4] Restoring existing accessory from cache: Ventilatie
[1/12/2021, 8:48:11 AM] [Cmd4] Characteristic polling has changed
[1/12/2021, 8:48:11 AM] [Cmd4] from: <characteristic>:<default value>
[1/12/2021, 8:48:11 AM] [Cmd4] to: "Characteristic": <characteristic>
[1/12/2021, 8:48:11 AM] [Cmd4] Please update your config.json for Ventilatie accordingly to
[1/12/2021, 8:48:11 AM] [Cmd4] remove this message; As in the future, this warning will be an error.
[1/12/2021, 8:48:11 AM] [Cmd4] Sorry for the inconvenience.
[1/12/2021, 8:48:11 AM] [Cmd4] Restoring existing accessory from cache: Laadstation
Any idea what's wrong?

        {
            "platform": "Cmd4",
            "name": "Cmd4",
            "outputConstants": false,
            "accessories": [
                {
                    "type": "Fan",
                    "displayName": "Ventilatie",
                    "on": "TRUE",
                    "rotationDirection": "CLOCKWISE",
                    "rotationSpeed": 100,
                    "name": "Ventilatie",
                    "Manufacturer": "VENTRO",
                    "Model": "VENTRO-275",
                    "polling": [
                        {
                            "characteristic": "rotationDirection",
                            "interval": 9999,
                            "timeout": 2000
                        },
                        {
                            "characteristic": "on",
                            "interval": 30,
                            "timeout": 3000
                        },
                        {
                            "characteristic": "rotationSpeed",
                            "interval": 10,
                            "timeout": 9000
                        }
                    ],
                    "SerialNumber": "12345",
                    "outputConstants": true,
                    "stateChangeResponseTime": 3,
                    "state_cmd": "/opt/ventilatie.sh"

**Comment by ztalbot2000** [comment]
Hi,

  Yeah, things are cached as well.   Homebridge remembers what it last
was.  There are instructions in the README. The easiest is the rm-rf of
$HOME/.Homebridge/accessories.

Homebridge wants you to actually delete and re-add it, but that's just
painful.

You can also get rid of caching with restartRestore: false.

TTFN,
John

**Comment by mitch7391** [comment]
I had this same issue and figured maybe I had updated the config incorrectly when I still saw those warnings. Just to double check your above comment is not a typo @ztalbot2000, in your README it say `restartRecover: false` and above you have said `restartRestore: false`; which one is the correct one to use? And does it go here in this part of the config?

```
 {
        "platform": "Cmd4",
        "name": "Cmd4",
        "outputConstants": false,
        "restartRecover": false,
        "accessories": [ ]
}
```

**Comment by arkadicolson** [comment]
restartRecover worked for me.

**Comment by ztalbot2000** [comment]
RestartRecover is correct.  Sorry, it was like 2 a.m. All the strings are
listed in cmd4Constants. To avoid typos like I just made.

ttfn,
John

**Comment by ztalbot2000** [comment]
To avoid confusion and close this issue,

RestartRecover is correct and it belongs in the section of
"platform": "Cmd4",
"name": "Cmd4",
"restartRecover": false,      // Default is true ( Try to recover )

If there are cached accessories from a previous run, you should see the message:
"Removing *ALL* cached accessories as: restartRecover is set to false"
