### ISSUE TITLE
Cannot set values, always logs:  setValue: outputConstants: false

### ISSUE THREAD

**Issue by jsiegenthaler** [ztalbot2000/homebridge-cmd4#83]
Cmd4 seems to be broken, cannot Set values
Homebridge logs:
setValue: outputConstants: false

But nothing happens
Even in debug mode, I see no values getting Set

The polling works and I can see the switch state change with a Get.
Using homebridge-cmd4 v3.0.12

**Comment by ztalbot2000** [comment]
Hi,

  I need a lot more information, like your config.json and any scripts you
wrote and the complete logs. Otherwise I'm blind as I and others have this
working for over a week.

ttfn,
John Talbot

**Comment by jsiegenthaler** [comment]
Config:
                {
                    "type": "Switch",
                    "displayName": "Samsung HT-D5500",
                    "on": "FALSE",
                    "name": "Samsung Stereo",
                    "manufacturer": "Samsung",
                    "model": "HT-D5500",
                    "serialNumber": "HTB-D6500EUB-1023.1",
                    "polling": true,
                    "interval": 5,
                    "timeout": 4000,
                    "state_cmd_prefix": "bash",
                    "state_cmd": "./Cmd4Scripts/Stereo.sh",
                    "state_cmd_suffix": ""
                },

**Comment by ztalbot2000** [comment]
Can I have /Cmd4Scripts/Stereo.sh

The config looks fine.

**Comment by jsiegenthaler** [comment]
Been working rock solid for nearly a year

Running my bash script manually works:
bash Stereo.sh Set Stereo On true
Returns 1 = on, 0 = off

**Comment by jsiegenthaler** [comment]
Every time I toggle the switch it logs in Homebridge (first 2 lines are from other plugins resp. Homebridge UI):
[01/02/2021, 20:48:34] [Movement 15min Delay Timer] Starting the Timer
[01/02/2021, 20:49:57] [Homebridge UI] Terminal session ended.
 setValue: outputConstants: false
 setValue: outputConstants: false
 setValue: outputConstants: false
 setValue: outputConstants: false

It's the Cmd4 plugin which is logging "setValue: outputConstants: false". My bash script doesn't log anything, just returns 1 or 0

**Comment by jsiegenthaler** [comment]
I can mail you the bash script but I don't want to post it here

**Comment by ztalbot2000** [comment]
Yeah,

  Theres a long story behind it, but I believe your script should respond
to:
 Stereo.sh Set Stereo On 1         or
Stereo.sh Set Stereo On 0

Try that and let me know what happens.
John

**Comment by ztalbot2000** [comment]
Even better, put an or around it checking for 0 or false and 1 and true.

**Comment by jsiegenthaler** [comment]
That fixed it! 
I changed...
if [ "$4" = "true" ]; then
...to...
if [ "$4" = "1" ]; then
...and now it works. Thanks!
You can close the issue

**Comment by jsiegenthaler** [comment]
HOWEVER: it still logs this message
 setValue: outputConstants: false

**Comment by ztalbot2000** [comment]
I'll close it, but I don't like the fact that it changed. Others thought it was always 0 | 1 and I caved.

**Comment by jsiegenthaler** [comment]
Still logs the erroneous message:
setValue: outputConstants: false

**Comment by ztalbot2000** [comment]
Hi,  yeah, 'I have that fixed here.  Sorry

**Comment by jsiegenthaler** [comment]
Found it in
https://github.com/ztalbot2000/homebridge-cmd4/blob/master/Cmd4Accessory.js

this line:
 console.log(" setValue: outputConstants: %s", self.outputConstants );

**Comment by ztalbot2000** [comment]
3.0.14 fixes this.
