### ISSUE TITLE
Missing some accessory types

### ISSUE THREAD

**Issue by jsiegenthaler** [ztalbot2000/homebridge-cmd4#84]
Missing some accessory types
See here:
https://developers.homebridge.io/#/categories

34-36 are new

You might want to add them to 
https://github.com/ztalbot2000/homebridge-cmd4/blob/master/lib/CMD4_DEVICE_TYPE_ENUM.js

**Comment by ztalbot2000** [comment]
Those are categories, not accessory types

**Comment by jsiegenthaler** [comment]
oops, ok

**Comment by jsiegenthaler** [comment]
not an issue ;)
