### ISSUE TITLE
[Feature Request] Cmd4 Issue Templates

### ISSUE THREAD

**Issue by mitch7391** [ztalbot2000/homebridge-cmd4#85]
I have a nice simple one for you John that hopefully may help you in the long run; issue templates! I have 'stolen' mine mostly from `homebridge` and `homebridge-config-ui-x` repos as I really thought they were handy; just slightly tweaked them to be more relevant to my repos. Have a look at my repos or the homebridge ones I mentioned and I think it might help people set you up for success quicker :)

**Comment by ztalbot2000** [comment]
Hey Mitch,

   If you look at the new Cmd4 GitHub pages Cmd4 GitHub Pages
<https://ztalbot2000.github.io/homebridge-cmd4/autoGenerated/CMD4_AccessoryDescriptions.html>
You
will see I have some new templates there.   I'm trying to make this a
portal for all which is Cmd4.  It is all autoGenerated.  If you think of
more stuff you would like there, please let me know.
I want to get rid of State.js which is so error prone and that is what
provoked this.

ttfn,
John

**Comment by mitch7391** [comment]
I think you may have misunderstood me John :) I am not talking about templates for accessories/services/etc.; I am talking about [Issue Templates.](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) Here is what one of mine look like:

![image](https://user-images.githubusercontent.com/40288237/106745177-b1719480-665b-11eb-9b90-c9bbd6c81c00.png)

![image](https://user-images.githubusercontent.com/40288237/106745205-ba626600-665b-11eb-9644-75560af12f2b.png)

**Comment by ztalbot2000** [comment]
Hi,

  Yup, totally misunderstood you!

I love your template!  I thought you just used some sort of GitHub issue
nicety. I love yours.  I do not know how to make it available for those to
use.  Any further help would be helpful ;-) if you can describe how or want
to fork Cmd4 and I'll merge anything you back anything you create. Either
is good.

TTFN,
John

**Comment by mitch7391** [comment]
I can't take all the credit as I copied the format off `homebridge` and `homebridge-config-ui-x` repos; but I really do like the format and think they would be quite handy for you. I will give it a go forking your repo and making the changes myself for my own learnings!

**Comment by ztalbot2000** [comment]
Hey Mitch,

  Thank you very much !  I have taken much from HomeBridge.  While the Cmd4
GitHub pages are auto generated and that process is all mine, the
underlying css format is theirs. I've always been told that copying can
also be a compliment too.

All learning is good ( as well as mistakes ).  You do not need a
prestigious school to learn and those who learn on their own are better
off.  I really do appreciate all your efforts. Your employer is very lucky
to have you as I find there are few who can think for themselves.

TTFN,
John

**Comment by ztalbot2000** [comment]
I am a little better this morning.  Just getting under way.  I looked at the templates you created.  I did not even know you could do that so I really do appreciate the effort. Thank-you ever so much.

John Talbot

**Comment by mitch7391** [comment]
Glad you are happy with them John :)
