### ISSUE TITLE
[Feature Request] Accessory Logging in Homebridge Logs

### ISSUE THREAD

**Issue by mitch7391** [ztalbot2000/homebridge-cmd4#88]
**Is your feature request related to a problem? Please describe:**

N/A

**Describe the solution you'd like:**

Considering a lot of users would be using their own scripts to create accessories through cmd4 in lieu of a dedicated plug-in for their device; I assume like me they do not have accessory statuses in their Homebridge logs. If it is possible could we get an option to have the accessory interactions (Thermostat set to cool, TV set to off, etc.) to populate in the Homebridge logs like any other plug-in's accessories would. I believe currently cmd4 only logs platform based events, warnings and errors.

**Describe alternatives you've considered:**

Find a way to do this through my own shell scripts.

**Additional context:**

Maybe it might be best to add a way to activate or de-activate, as not all users might want these logs.

**Comment by ztalbot2000** [comment]
Yeah, I wanted to do that too

**Comment by mitch7391** [comment]
Nice :) glad to hear!

**Comment by ztalbot2000** [comment]
hi Mitch,

 Sorry I got side tracked.  I just released Cmd4 v3.1.0 which addresses this feature.  
For the first time I used npm run release:minor which uses my new generateChangeLog tool picking up the commit style messages I was talking about.
The sidetrack was trying to figure out how to publish to both GitHub and NPM or NPM and GitHub depending on the starting point. anyway, for the time I could spend on it, I did not get it done, which was delaying your feature..

**Comment by mitch7391** [comment]
Hey John, don't stress! I do not know any other developer who gets tasks sorted so quickly! :) On first glance this looks quick good, I will monitor it over the next few days and let you know what I think. Thanks for getting to this one.
