### ISSUE TITLE
No support for decimal temperatures.

### ISSUE THREAD

**Issue by dylanstone96** [ztalbot2000/homebridge-cmd4#9]
iOS 12 adds support for viewing decimal temperatures in Home. When I pass a decimal temperature to a cmd4 accessory it always rounds down. For reference, homebridge-dht22 does not round and shows decimal temperatures in Home.

**Comment by ztalbot2000** [comment]
I will have a look.  The shell script that cmd-4 provides passes whatever
it gets back to homebridge-cmd4.  If you are using the cmd4 shell script,
please let me know.  I have IOS 12on my iPad so I can have a look, but I do
not believe it is generally available yet. Thanks for the heads up.

Ttfn,
John

**Comment by dylanstone96** [comment]
Yeah, I ran a node command to manually check the temperature of the sensor and it relays the decimals present in the text file, but they don't get passed to Home.

**Comment by ztalbot2000** [comment]
homebridge-cmd4 receives a string.   It checks if it is numeric (including floats) but then uses parseInt resulting in the value being rounded down.  I will change this to parseFloat if the string is a float.  I will fix this in a day or two after testing.

**Comment by dylanstone96** [comment]
Awesome, thank you so much.

**Comment by ztalbot2000** [comment]
Fixed in v1.22.   Submitted also to npm.  Any device that returns a float is fixed as homebridge-cmd4 now passes any float back to homebridge.

**Comment by zimmerman80** [comment]
Hi, just curious about this when Homekit converts to Fahrenheit.  I have cmd4 setup and working well as a temperature sensor, with a script I wrote returning temperatures in celsius and with a decimal.  However, on my IOS device (in the United States), it rounds to F and rounds to the whole degree.  Any way to encourage a single decimal place?  Or use Fahrenheit all the way through?

**Comment by ztalbot2000** [comment]
Hi,

   In the IOS Home App, if I click on My_Thermostat there is a settings
button which you can change to Celsius or Fahrenheit .  The resolution is
totally up to the App to display.

Even though I am in Canada, I do not like Celsius. The resolution is 2 1/2
degrees which is a big difference if it is 78 or 80 degrees Fahrenheit
outside.  Though Celsius does get it right for below zero.  I tend to use
Fahrenheit during the summer and Celsius during the winter. -10 Celsius is
still cold!

There are other Home apps. Eve is better.  You may wish to try it and see
if it does what you want.

TTFN,
John Talbot

**Comment by zimmerman80** [comment]
I’m afraid I don’t see that option... but it sounds like I’m stuck with whole degree resolution in Fahrenheit. I’ll take a look at Eve. Thanks! 

Jesse
