### ISSUE TITLE
homebridge-cmd4 terminates homebridge process unsafely

### ISSUE THREAD

**Issue by oznu** [ztalbot2000/homebridge-cmd4#92]
**Describe The Bug:**

This plugin is using `process.exit` in the plugin code rather than handling with errors gracefully. Terminating the process in this way means the whole bridge is unusable when there are issues with just this plugin and not very friendly in a shared environment with other plugins running.

This also does not give Homebridge a chance to log "which" plugin caused the issue, or to safely save the accessory cache on shutdown.

**To Reproduce:**

Create an accessory without a `name` attribute, the process is killed by this bit of code ([and a few other places](https://github.com/ztalbot2000/homebridge-cmd4/search?p=2&q=process.exit)):

https://github.com/ztalbot2000/homebridge-cmd4/blob/253d41bd67e7232231285443885943b083818941/utils/getAccessoryUUID.js#L25

The log message is just the following, without any indication which plugin is causing the problem:

```
You must have a 'name' per accessory.
```

**Expected Behaviour:**

Plugins should not kill the entire process. You should log the error and not load your plugin any further.

Use the `log.error` method provided to log error messages so users know which plugin to check.

**Comment by ztalbot2000** [comment]
This was always my intent and only happens during setup because there are so many options that continuing was problematic. The person was always like "what happened when and why?" I can understand that now with configUI-x it may be not the greatest thing to do, but since Cmd4 always did it this way, if you must, raise it as a feature.

**Comment by ztalbot2000** [comment]
Hi,

Just to let you know, As of Cmd4 v5.1.0; All process.exit calls have been changed to throw new Error.
I have not seen a difference for the bridge, but for Unit testing I can now easily catch the thrown error, which in v5.1.0 all thrown errors are also now unit tested.

take care,
John Talbot
