### ISSUE TITLE
change iid: 9 to iid: 10

### ISSUE THREAD

**Issue by shungo27** [ztalbot2000/homebridge-cmd4#98]
The Homebridge accessory is on / off at iid:10. But the cmd4 accessory is iid:9.

Can I change it to iid:10?

from
{"characteristics":[{"aid":7,"iid":9,"value":0}]} <-- on/off
{"characteristics":[{"aid":7,"iid":10,"value":"Smart plug"}]} <--???
to
{"characteristics":[{"aid":7,"iid":10,"value":0}]} <--on/off

This specification can be inconvenient when scripting on the homebridge. get iid: 9 and iid: 10 of all accessories and check their values. If cmd4 changes iid: 10, I can skip this process.

homeScript.py does not work well with cmd4 due to this.

**Comment by ztalbot2000** [comment]
Hi,
I don't own HomeScript.py.  I would not use the iid number either as it can and has changed in the past.  All they have to do is add another ahead of the one you want and your toast.  Cmd4 does not make public its internal index. If it happens to come close to an iid, that is just by luck. I cannot change it either.  Doing so would mean that everyone else's cached data would not match to the existing index. Frankly I wish I had not used an array at all, but an associative array instead.  
Cmd4 only communicates to devices by their device name, and characteristic name;  internally to Homebridge by their UUID.  
I did see that the device name and type  is available from HomeScript.py.   You might want to see how you can manage it that way. Unfortunately this is not within what I see a future of Cmd4 and it is not a part of Cmd4.

**Comment by ztalbot2000** [comment]
I tried Homezscript.pay.  It doesn't even work for me.  It drops an
exception to a file that does not exist anywhere on my system.
I do not have time to play with such things.

TTFN,
John
